### ISSUE TITLE
Tortoise TTS: Length and Repetition Penalty at low values makes text too long?

### ISSUE THREAD

**Issue by MiYakuGaming** [rsxdalv/tts-generation-webui#101]
When I put Length and Repetition values at a lower value, command line tells me I need to shorten my text, but I barely put any in.
Is there a way to fix this?

**Comment by rsxdalv** [comment]
Maybe there is, but I'm not sure if it's not the intended outcome. Since
you lower the maximum length, you are more likely to exceed it with text.
Could you give me an example of the three values you are using?

**Comment by rsxdalv** [comment]
Now there are options to do generate longer texts piece-by-piece, so if the text is too long it can be divided into chunks.
Although there still might be a problem with the parameters just being hard for the AI to use.
