### ISSUE TITLE
issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by MrMondragon** [rsxdalv/tts-generation-webui#112]
Got another on the same tab but, this time, using musicgen. 

  File "C:\MusicGen\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 241, in _s_validate_and_normalize_key
    elif issubclass(key_type, Enum):
TypeError: issubclass() arg 1 must be a class

**Comment by rsxdalv** [comment]
I haven't seen this one unfortunately. Could you provide a screenshot and some system into please?

Also let me know if you used any custom installation steps.

**Comment by MrMondragon** [comment]
Sorry. My pc must be acting out. Last night I tried a few times with no success. Now it works fine. Thanks for the reply, though. You have an amazing project here!

**Comment by rsxdalv** [comment]
No worries, I have seen Python fail unpredictably many times, so I understand the feeling.
