### ISSUE TITLE
Other language generate weird output

### ISSUE THREAD

**Issue by BankNatchapol** [rsxdalv/tts-generation-webui#113]
I was using https://git.ecker.tech/mrq/ai-voice-cloning this repo for training a model of my language. 
I can load it to this webui, but the output is very weird. 

The processes i did was,
I copy my pth model that i trained to `tts-generation-webui/data/models/tortoise/my_language/autoregressive.pth`
and then copy the other default models from `~/.cache/tortoise/models` to  `tts-generation-webui/data/models/tortoise/my_language/`
then run.

Not sure if i did something wrong or it's because the tokenizer doesnt have my language character token.

**Comment by rsxdalv** [comment]
Hmm, have your tried your model before?

I know that tortoise makes everything into ASCII, perhaps I need to make
this filter optional?

That could be the issue why it's happening.

**Comment by BankNatchapol** [comment]
It's working really great in the original repo code. In the original repo i only change the tokenzer from english characters only to english + my language characters and english cleaner -> basic cleaner.

**Comment by rsxdalv** [comment]
Great, then I can just make it work.

**Comment by BankNatchapol** [comment]
Thank you so much!!🙏

**Comment by BankNatchapol** [comment]
It's work ok now after i manually change tokenizer.json and cleaner in tokenizer.py

**Comment by rsxdalv** [comment]
Ok, I finally fixed tortoise and added the UI for tokenizer.
