### ISSUE TITLE
Tortoise error please help 

### ISSUE THREAD

**Issue by Tykwha** [rsxdalv/tts-generation-webui#115]
![image](https://github.com/rsxdalv/tts-generation-webui/assets/132142270/80db5a0e-d59a-45eb-b94f-b144f27255e2)

What i need to do with this ?

**Comment by rsxdalv** [comment]
cmd_windows.bat

Then
`pip install transformers==4.29.2`

**Comment by rsxdalv** [comment]
Details also here https://github.com/rsxdalv/tts-generation-webui/issues/106

**Comment by Tykwha** [comment]
> Details also here #106

Ty so much, it works now!!!

**Comment by rsxdalv** [comment]
Should be fixed with the regular install now
