### ISSUE TITLE
How to change the default .cache folder to another drive for all the automatic downloading files?

### ISSUE THREAD

**Issue by Thinker786** [rsxdalv/tts-generation-webui#129]
I successfully installed tts-generation-webui to a drive with plenty of free space but while trying out BARK, right after installation, I ran out of memory as the process was downloading files in .cache folder in the C drive which is nearly full.
I am very new to this and have no coding skills, but can follow instructions. Can anyone tell me what settings or files I need to edit to make sure no files get downloaded or installed in the C drive?

Thank you.

**Comment by rsxdalv** [comment]
Hi, thanks for the question!

Did you try the model location options?

**Comment by Thinker786** [comment]
> 

Thank you, I feel stupid as somehow I missed that setting. Problem solved now.

**Comment by rsxdalv** [comment]
No worries, perhaps there should be more tutorials for the UI.
