### ISSUE TITLE
[META] Trying to get in contact for RVC

### ISSUE THREAD

**Issue by kalomaze** [rsxdalv/tts-generation-webui#131]
Hey, sorry to contact you like this, but I couldn't find any external contact information on your page.
There is the [Mangio RVC fork ](https://github.com/Mangio621/Mangio-RVC-Fork) that adds a lot of new features and has been working on optimizations for inference and etc, and it also includes RMVPE training (I don't believe this is in mainline yet?)

We would greatly appreciate if you could help us get the Mangio fork up to speed for DirectML support and also help implement other changes where possible.
Thanks

**Comment by rsxdalv** [comment]
I actually wanted to ask you about this: is there a holdout that prevents the original repo from being improved?

**Comment by kalomaze** [comment]
Language barriers make PRing the original RVC repository a bit difficult for us. There are also certain things that are still exclusive to Mangio's fork, especially what https://github.com/alexlnkp has been working on with the customizable pitch range, and my upcoming inference GUI reworks

![image](https://github.com/rsxdalv/tts-generation-webui/assets/66376113/fefeb75c-ed19-49b1-8c05-6e2886c034ac)

**Comment by rsxdalv** [comment]
Got it.
