### ISSUE TITLE
models folder empty

### ISSUE THREAD

**Issue by Lmears** [rsxdalv/tts-generation-webui#132]
there are no models. instructions are very unclear on how to get this webui working with the new audiocraft models. am i supposed to just clone the audiocraft repo and copy and paste over the python files?

**Comment by Lmears** [comment]
note: this is after trying to just use the one click installer (it doesn't have the correct permissions to work)

**Comment by rsxdalv** [comment]
Thanks for checking in!

No, to get it working you just need to run the one click installer and open the musicgen-audiogen tab. Trying to generate will download the models automatically.

Models folder _should_ be empty. Audiocraft downloads the models to hugging face cache automatically (user/.cache folder).

**Comment by rsxdalv** [comment]
If you were to install it manually, then you can check the webui.py from the installer and the conda activate command from start_webui.bat

What it does is - create a new conda environment with python 3.10, install git within conda, then install dependencies such as torch 2.0.0 for CUDA 11.8 and torchaudio and ninja, etc. Next it clones this repo, runs pip install requirements for each requirements file and finally does python server.py

**Comment by Lmears** [comment]
Thanks for the prompt response! I was able to install everything except audiocraft. I am on a macbook m1 to clarify. I get this message

ERROR: Could not find a version that satisfies the requirement xformers==0.0.19 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.20, 0.0.21.dev580, 0.0.21.dev581)
ERROR: No matching distribution found for xformers==0.0.19

**Comment by Lmears** [comment]
considering xformers is not available on mac, is there another way to use audiocraft here? perhaps leveraging mps?

**Comment by rsxdalv** [comment]
I know that they used to just straight up not support Mac for audiocraft, but that might have changed. 
Also that's why the installer is modular.

I feel like _someone_ must have used xformers on a Mac, but I haven't found a working solution yet.
