### ISSUE TITLE
Bark Voice Clone section is not working

### ISSUE THREAD

**Issue by Razbolt** [rsxdalv/tts-generation-webui#137]
Hi everyone, I have encountered a problem in the section of Bark Voice Clone. I have used this program via google colab and it seems I can not train a voice. When I clicked a generate voice button, I saw errors in the right hand side. 
Any ideas about this error ?
 
![bark_error](https://github.com/rsxdalv/tts-generation-webui/assets/69273456/b0822cdc-685b-4914-bdb5-2c19c57b8caf)

**Comment by rsxdalv** [comment]
I tried it just now, and it seemed to work.

Here's my output from the final cell:
```
Env file not found. Creating default env.
Config file not found. Creating default config.
2023-08-17 13:43:00.541047: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading extensions:
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded extension: empty_extension
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.
Failed to load musicgen demo
Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
/content/tts-generation-webui/src/rvc_tab/rvc_tab.py
Gradio share mode enabled
Starting Gradio server...
Gradio interface options:
  inline:               False
  inbrowser:            True
  share:                True
  debug:                False
  enable_queue:         True
  max_threads:          40
  auth:                 None
  auth_message:         None
  prevent_thread_lock:  False
  show_error:           False
  server_name:          0.0.0.0
  server_port:          None
  show_tips:            False
  height:               500
  width:                100%
  favicon_path:         None
  ssl_keyfile:          None
  ssl_certfile:         None
  ssl_keyfile_password: None
  ssl_verify:           True
  quiet:                True
  show_api:             True
  file_directories:     None
  _frontend:            True
Running on local URL:  http://0.0.0.0:7860/
Running on public URL: https://977b8e304587923d2c.gradio.live/
/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py:176: UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
Downloading HuBERT base model
Downloaded HuBERT
Downloading HuBERT custom tokenizer
Downloading (…)rt_base_ls960_14.pth: 100% 104M/104M [00:00<00:00, 200MB/s]
Downloaded tokenizer
Downloading: "https://dl.fbaipublicfiles.com/encodec/v0/encodec_24khz-d7cc33bc.th" to /root/.cache/torch/hub/checkpoints/encodec_24khz-d7cc33bc.th
100% 88.9M/88.9M [00:01<00:00, 80.7MB/s]
/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py:171: UserWarning: Trying to convert audio automatically from float32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
```

Could you post some logs from the google colab, please? Or perhaps save and send the colab?

**Comment by Razbolt** [comment]
Thanks, now I re-checked and it worked. However, this model is inconsistent with my audio. I wonder are there any updates for the Turkish language? I am trying to find a tokenizer for Turkish language however in the cloning version I could not find a proper instructors for it. Do you have any ideas 

> I tried it just now, and it seemed to work.
> 
> Here's my output from the final cell:
> 
> ```
> Env file not found. Creating default env.
> Config file not found. Creating default config.
> 2023-08-17 13:43:00.541047: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> Loading extensions:
> Loaded extension: callback_save_generation_ffmpeg
> Loaded extension: callback_save_generation_musicgen_ffmpeg
> Loaded extension: empty_extension
> Loaded 2 callback_save_generation extensions.
> Loaded 1 callback_save_generation_musicgen extensions.
> Failed to load musicgen demo
> Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
> /content/tts-generation-webui/src/rvc_tab/rvc_tab.py
> Gradio share mode enabled
> Starting Gradio server...
> Gradio interface options:
>   inline:               False
>   inbrowser:            True
>   share:                True
>   debug:                False
>   enable_queue:         True
>   max_threads:          40
>   auth:                 None
>   auth_message:         None
>   prevent_thread_lock:  False
>   show_error:           False
>   server_name:          0.0.0.0
>   server_port:          None
>   show_tips:            False
>   height:               500
>   width:                100%
>   favicon_path:         None
>   ssl_keyfile:          None
>   ssl_certfile:         None
>   ssl_keyfile_password: None
>   ssl_verify:           True
>   quiet:                True
>   show_api:             True
>   file_directories:     None
>   _frontend:            True
> Running on local URL:  http://0.0.0.0:7860/
> Running on public URL: https://977b8e304587923d2c.gradio.live/
> /usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py:176: UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
>   warnings.warn(warning.format(data.dtype))
> Downloading HuBERT base model
> Downloaded HuBERT
> Downloading HuBERT custom tokenizer
> Downloading (…)rt_base_ls960_14.pth: 100% 104M/104M [00:00<00:00, 200MB/s]
> Downloaded tokenizer
> Downloading: "https://dl.fbaipublicfiles.com/encodec/v0/encodec_24khz-d7cc33bc.th" to /root/.cache/torch/hub/checkpoints/encodec_24khz-d7cc33bc.th
> 100% 88.9M/88.9M [00:01<00:00, 80.7MB/s]
> /usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py:171: UserWarning: Trying to convert audio automatically from float32 to 16-bit int format.
>   warnings.warn(warning.format(data.dtype))
> ```
> 
> Could you post some logs from the google colab, please? Or perhaps save and send the colab?

**Comment by rsxdalv** [comment]
There might not be a version for Turkish. The original one is for English, and some other languages have been done as well so far.

These are the officially published ones, but there is no Turkish there yet: https://github.com/gitmylo/Voice-cloning-quantizers/blob/main/models.json
