### ISSUE TITLE
Google Colab Bark models folder

### ISSUE THREAD

**Issue by TheLocalLab** [rsxdalv/tts-generation-webui#145]
Where exactly are the Suno Bark models placed after download in the Google Colab directories. I searched through almost every directory and for the life of me, just can't  seem to locate the models. Colab tends to delete everything after you shut down the runtime including all the models unless its also saved on google drive so I would guess it would be in a temporary folder of some sort. I know in windows, they would normally be placed in the User/.cache/ folder but not too sure for Colab. Any ideas??

**Comment by rsxdalv** [comment]
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/2b02b3d8-8160-4a40-9e6c-9dfbc973f403)
Enable "hidden files" (eye icon) and check for the /root/.cache/ that's the User/.cache/ folder for this machine.

**Comment by TheLocalLab** [comment]
Your awesome, thanks.
