### ISSUE TITLE
starting does not work

### ISSUE THREAD

**Issue by Username69992872** [rsxdalv/tts-generation-webui#15]
After executing the start_windows.bat, everything looked fine, but theres an error:

```
Loading Bark models
        - Text Generation:               GPU: Yes, Small Model: Yes
        - Coarse-to-Fine Inference:      GPU: Yes, Small Model: Yes
        - Fine-tuning:                   GPU: Yes, Small Model: No
        - Codec:                         GPU: Yes
Traceback (most recent call last):
  File "D:\**************\tts-generation-webui\tts-generation-webui\server.py", line 132, in <module>
    settings_tab_gradio(save_config_gradio, reload_config_and_restart_ui, gradio_interface_options)
  File "D:\**************\tts-generation-webui\tts-generation-webui\settings_tab_gradio.py", line 34, in settings_tab_gradio
    "inline": gr.Checkbox(label="inline: Display inline in an iframe", value=gradio_interface_options["inline"]),
KeyError: 'inline'

Done!
Drücken Sie eine beliebige Taste . . .

```

always appears when starting the start_windows.bat now How to solve ?

**Comment by rsxdalv** [comment]
Might be an issue with config.json upgrade, try renaming config.json (or deleting). Then it would regenerate and should work.

**Comment by Username69992872** [comment]
Just tried, didnt solved it

**Comment by Username69992872** [comment]
```
{
  "model": {
    "text_use_gpu": true,
    "text_use_small": true,
    "coarse_use_gpu": true,
    "coarse_use_small": true,
    "fine_use_gpu": true,
    "fine_use_small": false,
    "codec_use_gpu": true,
    "load_models_on_startup": true
  },
  "gradio_interface_options_ui": {
    "inline": false,
    "inbrowser": true,
    "share": false,
    "debug": false,
    "enable_queue": true,
    "max_threads": 40,
    "auth": null,
    "auth_message": null,
    "prevent_thread_lock": false,
    "show_error": false,
    "server_name": "0.0.0.0",
    "server_port": null,
    "show_tips": false,
    "height": 500,
    "width": "100%",
    "favicon_path": null,
    "ssl_keyfile": null,
    "ssl_certfile": null,
    "ssl_keyfile_password": null,
    "ssl_verify": true,
    "quiet": true,
    "show_api": true,
    "file_directories": null,
    "_frontend": true
  },
  "load_models_on_startup": true
}
```

**Comment by rsxdalv** [comment]
Thank you! Yes, that was the issue, pushed a commit to generate config.json with the correct gradio_interface_options.

**Comment by Username69992872** [comment]
works! thx for the fast reply. Just testing now with a rtx4090

![grafik](https://github.com/rsxdalv/tts-generation-webui/assets/96194225/bcfb6d74-576f-4b58-a060-9ad1df10924e)

**Comment by Username69992872** [comment]
Sometimes I get this, even the generation seems to be successfull. Got the same error with another bark webui yesterday.
![cmd_1iQqCRCAir](https://github.com/rsxdalv/tts-generation-webui/assets/96194225/8f82dc06-4e47-4ffc-b393-91177fbbd64e)

**Comment by Username69992872** [comment]
copy thx. By the way the "Generate" Button would be better to move bit more up in the UI, because always need to scroll down when doing changes for speaker, no big deal though - just bit faster to use especially if testing at the beginning, which people for sure do alot :)

**Comment by Username69992872** [comment]
If the waveform would be bit smaller for single generation, that would solve the problem I guess
![grafik](https://github.com/rsxdalv/tts-generation-webui/assets/96194225/a9d8d430-ff53-4eb2-a15c-ce1dcb0e26d9)

**Comment by Username69992872** [comment]
After setting CVVP Amount to 1, error occoured. Now after restarting start_windows.bat:
![cmd_OnvqvPIJST](https://github.com/rsxdalv/tts-generation-webui/assets/96194225/85436b51-d8c3-4e34-8039-dfd1e48f5d09)

**Comment by rsxdalv** [comment]
It seems that the filenames are not what they are expected to be. Is this
the tortoise model?

A quick fix would be to backup and remove the outputs.

I will try to make a proper solution after.

**Comment by Username69992872** [comment]
jep it happens when generating with tortoise. History tab seems to be broken after that , not loading + console errors.
btw there is no info what CVVP option on tortoise page is doing, google also doesnt say.
Is it normal that on tortoise it takes like 10 seconds after clicking generate, before even seeing any progress in the console?

**Comment by Username69992872** [comment]
that one took me 20 seconds to generate, while I only see the progress bar moving on second 15.
![grafik](https://github.com/rsxdalv/tts-generation-webui/assets/96194225/d570d593-1159-401f-9d7c-ce4f969215dd)
![grafik](https://github.com/rsxdalv/tts-generation-webui/assets/96194225/4e07f543-b6dd-4e91-a094-db4470e36fe7)
is that normal?

**Comment by rsxdalv** [comment]
It doesn't cache the model, and it reloads it every time. So when using a fast GPU that is the biggest slowdown.

Also here's the tortoise documentation about CVVP:
Controls the influence of the CVVP model in selecting the best output from the autoregressive model.
                            [0,1]. Values closer to 1 mean the CVVP model is more important, 0 disables the CVVP model.

**Comment by Username69992872** [comment]
Looks like the GPU is not used at all or just by low amount. Looks like 10-20%, or sometimes not at all :o
https://github.com/rsxdalv/tts-generation-webui/assets/96194225/9a16d393-5d72-419b-9fb9-dd583bd9d7ea

**Comment by rsxdalv** [comment]
I see. you can also check the Performance > GPU > Cuda, but there are several factors why it might not be a 100%. 
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/2815141b-47da-41cd-b02b-84c987ace98b)

**Comment by Username69992872** [comment]
oh you are right. On the Bark Tab Cuda goes up to 40% if there is progress shown in the console. On Tortoise there is no Cuda load at all for the first 15seconds, only the last 5 seconds when there is progres in the console. Wondering if something is stuck or there is cpu stuff going on.

**Comment by rsxdalv** [comment]
Any generation has the following steps (which might be cached):
* Preparing Model (CPU load)
* Loading Model in CPU (RAM usage increases)
* Loading Model in GPU (VRAM usage increases, CUDA spike)
* Prepare Generation (CPU, RAM, VRAM and finally CUDA)

For tortoise the steps 1-3 get repeated. That can be cached.

**Comment by rsxdalv** [comment]
> After setting CVVP Amount to 1, error occoured. Now after restarting start_windows.bat: ![cmd_OnvqvPIJST](https://user-images.githubusercontent.com/96194225/239257631-85436b51-d8c3-4e34-8039-dfd1e48f5d09.png) edit: had to delete those from output: ![grafik](https://user-images.githubusercontent.com/96194225/239258777-42ccbc42-a2c6-4aae-920a-e46238cd8cad.png)

Ok, this error has been fixed in https://github.com/rsxdalv/tts-generation-webui/commit/75001da01c083d8fbf506d532da9dfab7a5d4acf

**Comment by rsxdalv** [comment]
> oh you are right. On the Bark Tab Cuda goes up to 40% if there is progress shown in the console. On Tortoise there is no Cuda load at all for the first 15seconds, only the last 5 seconds when there is progres in the console. Wondering if something is stuck or there is cpu stuff going on.

Tortoise speedup will become a part of #18 

I will close this issue, if these issues require additional questions, feel free to reopen or create a new issue.
