### ISSUE TITLE
Issue with MusicGen Melody input

### ISSUE THREAD

**Issue by Maki9009** [rsxdalv/tts-generation-webui#153]
It doesnt take Music / Melody input, the CMD says none for that even though i have a song in. it still generates a sound that has nothing to do with the song i input... and its a horrible sound because i assume the melody model needs an input to work properly... there is no error.. it only says that theres none for melody input

**Comment by rsxdalv** [comment]
Thank you for finding this!
It's fixed in the latest update.

I tested it with the same seed and melody/no melody. And it does make some impact now, although the model doesn't follow it exactly.

Background on the issue: the model "name" changed from _melody_ to _facebook/musicgen-melody_ and so the code kept erasing the melody.

**Comment by Maki9009** [comment]
there seems to be another issue now, it does load in a melody.. but i cannot see the progress bar in the CMD... so i dont even know if its actually processing or it froze

**Comment by rsxdalv** [comment]
Are you using multibanddiffusion? There's no progress for that one. And there's also a small bit of preprocessing for the melody.

Progress gets shown only for the main model.

**Comment by Maki9009** [comment]
no im not using multibanddiffusion it set to false, it did generate an audio though... but yeah no progress bar. just tested it again

**Comment by rsxdalv** [comment]
Here's how it's shown for me:
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/98f8e56a-52e7-460f-b139-6fe06ce88f12)
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/365d0e61-473d-42cb-8f9d-cc899a16a590)
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/fffc939d-cb13-4de7-b9f1-1b94febf7b45)

**Comment by Maki9009** [comment]
yeah i no longer have that n / 1500, it was there before this latest pull i just did

**Comment by Maki9009** [comment]
![Capture](https://github.com/rsxdalv/tts-generation-webui/assets/62298209/7d31d9c1-196b-44c5-b9e6-fa8f3900a4a9)

**Comment by rsxdalv** [comment]
That's an unfortunate bug. I tested several times, ran a full update and it still works. Refreshed and reopened the window, also works. I haven't been able to reproduce that.

**Comment by Maki9009** [comment]
okay hmm would it be possible to implement a proper progress bar in gradio webui.. or something with a more accurate timing, since the progress bar on there is extremely off

**Comment by rsxdalv** [comment]
Nevermind, I found it, when doing melody for some reason the progress was disabled.
Yes there can be a proper progress bar as well, but it involves more work.

**Comment by rsxdalv** [comment]
Pushed as a fix

**Comment by Maki9009** [comment]
yeah its working thanks
