### ISSUE TITLE
How do i run it the second time? 

### ISSUE THREAD

**Issue by notduckiee** [rsxdalv/tts-generation-webui#156]
If i close all the program after finish using it, and the next time i want to use it, do i need to run the batch file again? or is there anyway to make it more convenient?

**Comment by rsxdalv** [comment]
Hi! Not really. The gradio will take about a minute to start.

**Comment by rsxdalv** [comment]
Yes, start_windows.bat

**Comment by rsxdalv** [comment]
If you want to have a shortcut, you can make a shortcut of the bat file and then put it on the
Desktop. That way it should work with start menu search

**Comment by notduckiee** [comment]
alright! thank you

**Comment by notduckiee** [comment]
oh and the text generation process seems to be long for me, do you know why it happen so? 

![image](https://github.com/rsxdalv/tts-generation-webui/assets/143173021/13257919-f6f1-4c1c-a97e-5667b28124ce)

**Comment by rsxdalv** [comment]
In your screenshot it's still downloading the model weights. It downloads them when you use or generate for the first time.

For all the models in this UI, the total would be 20 or so gigabytes.

**Comment by notduckiee** [comment]
Hey doesn this means im running out of storage? 

![image](https://github.com/rsxdalv/tts-generation-webui/assets/143173021/a2bc47b0-8acc-407a-9195-60c4638ac6db)

**Comment by rsxdalv** [comment]
No, it means that for the space efficient usage of cache, you could use developer mode or run the webui as an administrator. I'm not sure how impactful that is, I think I have developer mode myself.

**Comment by notduckiee** [comment]
hey i tried run it as administrator and receive runtimeerror
![image](https://github.com/rsxdalv/tts-generation-webui/assets/143173021/82e303ce-b000-43fd-bc32-02c4b7842e9e)

**Comment by rsxdalv** [comment]
> hey i tried run it as administrator and receive runtimeerror ![image](https://user-images.githubusercontent.com/143173021/264989034-82e303ce-b000-43fd-bc32-02c4b7842e9e.png)

That's https://github.com/rsxdalv/tts-generation-webui/issues/155

**Comment by notduckiee** [comment]
i don't see the solution on that page
