### ISSUE TITLE
Cuda is Out of Memory. How to turn on CPU Offload?

### ISSUE THREAD

**Issue by tomb-of-ash** [rsxdalv/tts-generation-webui#157]
Hi team,
Thanks for this great tool. I'm having the same issue with my 8GB card:
https://github.com/rsxdalv/tts-generation-webui/issues/56
Could I get some help with what to input into config.json to enable CPU offload? Got plenty of RAM and such (256gb) and 2x Xeon CPUs so would like to make use of it in case it runs out of memory

**Comment by tomb-of-ash** [comment]
Whoops, just noticed as setting in option.

**Comment by rsxdalv** [comment]
Hi, yes it's possible for Bark. For others - it's requires an improvement to the app. I usually just restart the UI, I use 8GB of VRAM myself.

**Comment by jamesdnexa** [comment]
How do we configure how much VRAM is allocated in Windows (if anywhere)?  Strange one, on 24gb 3090, it's telling me OOM allocating VRAM just trying to do a basic Tortoise TTS generation

**Comment by rsxdalv** [comment]
> How do we configure how much VRAM is allocated in Windows (if anywhere)? Strange one, on 24gb 3090, it's telling me OOM allocating VRAM just trying to do a basic Tortoise TTS generation

Yes that is strange. Did you launch any other models or any other AI apps? Tortoise should fit within 2, maybe 4gbs.
