### ISSUE TITLE
xdg-open seems wrong

### ISSUE THREAD

**Issue by JFronny** [rsxdalv/tts-generation-webui#159]
[`open_folder`](https://github.com/rsxdalv/tts-generation-webui/blob/61db624a90cc67a8907429a19b865f00821dfad2/src/history_tab/open_folder.py#L12) uses `xdg-open -- {file}` while the [manpage](https://man.archlinux.org/man/xdg-open.1) for `xdg-open` (provided by `xdg-utils` 1.1.3) declares its syntax as `xdg-open {file | URL}`.
Due to this, the open-directory-buttons for the RVC tab don't work (the command returns `xdg-open: unexpected option '--'` and a non-zero exit code), while manually running the same command but without the `--` does.
Maybe another implementation of the `xdg-open` does support this, but this seems like an issue to me.

**Comment by rsxdalv** [comment]
Thank you for reporting this! I will update it accordingly

**Comment by rsxdalv** [comment]
Updated

**Comment by JFronny** [comment]
Works now :+1:
