### ISSUE TITLE
MusicGen Not Installing on Colab

### ISSUE THREAD

**Issue by Maki9009** [rsxdalv/tts-generation-webui#160]
It wont install, even when i click the install button because it was missing... it installs and says it successful  and asks to restart the webui, i do that. And it still assumes it hasnt been installed.

**Comment by rsxdalv** [comment]
Hi, does it snow an error in the UI or the console?

What's your platform?

**Comment by rsxdalv** [comment]
For MusicGen on colab, it might be this line that needs to be run:
```python
# Fix torchvision for MusicGen 
# !pip install torchvision==0.15.0+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
```

They updated something and for some reason this audio-generation model became sensitive to the version of the image/visual package. Without digging in more, I just added a fix for those who need it.

**Comment by rsxdalv** [comment]
The above lines fixed it for me, I will close this issue for now.

In the _future_ hopefully there's a fast way to get the right torch versions in colab. Right now that's a slow step so I don't want to install everything every time.
