### ISSUE TITLE
Please add a button to unload models

### ISSUE THREAD

**Issue by Aamir3d** [rsxdalv/tts-generation-webui#162]
When moving between tabs (Bark, AudioGen etc.), each model starts occupying GPU memory and then it starts running out of GPU memory.
A good to have would be a button that clears/unloads a model on each page (or combined).

**Comment by rsxdalv** [comment]
Added for bark. I tested and managed to reclaim some of the GPU memory, but not all of it (for example, I saw 4.5gb -> 1.3 gb drop). But when using CPU offloading, there's almost no reclaimed memory, only about 300mbs (usage goes from 1gb -> 700mb).

**Comment by Aamir3d** [comment]
> Added for bark. I tested and managed to reclaim some of the GPU memory, but not all of it (for example, I saw 4.5gb -> 1.3 gb drop). But when using CPU offloading, there's almost no reclaimed memory, only about 300mbs (usage goes from 1gb -> 700mb).

Thank you!
What happens is if you shift to the audiogen section, it starts to use all available GPU memory (12+ VRAM) and there's no way to release memory unless the app is closed and restarted.
I'll test the update today for Bark and let you know how it goes.

**Comment by rsxdalv** [comment]
Yes audiogen is a beast, it's kind of at the limit of "consumer" hardware.
I think you can get some of it back if you select the smaller model. But
multi band diffusion eats up a lot as well. If it has not been done yet,
AudioGen should get CPU offloading.

**Comment by Aamir3d** [comment]
I just tested with the latest update.
After clicking Unload Models, the memory usage goes down by only 2 GB. Not sure why the remaining memory isn't cleared.
![image](https://github.com/rsxdalv/tts-generation-webui/assets/122131887/3e919a82-8ef3-4687-8758-adef3853bf28)
![image](https://github.com/rsxdalv/tts-generation-webui/assets/122131887/968a12ce-6cc1-437b-99c7-3bf27cbd4981)


**Question**: What does the "Clear Models" on the Bark Voice Clone do? Is it similar to Unloading?

**Bug** : After clicking Unload Models, the button says "Unloaded"  and doesn't reset
![image](https://github.com/rsxdalv/tts-generation-webui/assets/122131887/6fd30fba-afa5-4e4a-abe3-a05099dbfbcd)

**Comment by rsxdalv** [comment]
Most of the models now contain a button for unloading. It works about as well as it can, but if there are any models that fail to properly unload please inform me.
