### ISSUE TITLE
ModuleNotFoundError: No module named 'tortoise.api'

### ISSUE THREAD

**Issue by 1tporridge** [rsxdalv/tts-generation-webui#164]
root@afdb675d1c33:/tts-generation-webui-main# python server.py
Traceback (most recent call last):
  File "/tts-generation-webui-main/server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "/tts-generation-webui-main/src/tortoise/generation_tab_tortoise.py", line 7, in <module>
    from src.tortoise.gen_tortoise import (
  File "/tts-generation-webui-main/src/tortoise/gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
ModuleNotFoundError: No module named 'tortoise.api'

pip install tortoise.api
success
But still ModuleNotFoundError: No module named 'tortoise.api'

pip install ./tortoise_api-0.3.0-py3-none-any.whl
ERROR: Package 'tortoise-api' requires a different Python: 3.10.12 not in '>=3.11'

Doing my head in, unsure what to do. Anyone know a fix?

**Comment by rsxdalv** [comment]
Hi, that generally indicates an installation failure. However, it's unusual
that it failed midway. Could you share any other logs or errors with me
please? If you still have the window open, could you copy the output of
installation?

**Comment by 1tporridge** [comment]
Installing collected packages: tortoise-api
Successfully installed tortoise-api-0.2.8
root@afdb675d1c30:/tts-generation-webui-main# python server.py
Traceback (most recent call last):
  File "/tts-generation-webui-main/server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "/tts-generation-webui-main/src/tortoise/generation_tab_tortoise.py", line 7, in <module>
    from src.tortoise.gen_tortoise import (
  File "/tts-generation-webui-main/src/tortoise/gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
ModuleNotFoundError: No module named 'tortoise.api'
root@afdb675d1c30:/tts-generation-webui-main# pip list | grep api
fastapi                   0.103.1
tortoise-api              0.2.8
tortoise-api-model        0.2.8
root@afdb675d1c30:/tts-generation-webui-main# python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tortoise.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tortoise.api'
>>> import tortoise_api
>>> from  tortoise_api import TextToSpeech, MODELS_DIR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TextToSpeech' from 'tortoise_api' (/venv/lib/python3.10/site-packages/tortoise_api/__init__.py)
>>> exit()

**Comment by 1tporridge** [comment]
I tried using Python 11 but still the same error....

root@afdb675d1c30:/tts-generation-webui-main# python3.11 -m pip install ./tortoise_api-0.3.0-py3-none-any.whl
Processing ./tortoise_api-0.3.0-py3-none-any.whl
Requirement already satisfied: tortoise-api-model>=0.2.7 in /usr/local/lib/python3.11/dist-packages (from tortoise-api==0.3.0) (0.2.8)
Requirement already satisfied: asyncpg in /usr/local/lib/python3.11/dist-packages (from tortoise-api==0.3.0) (0.28.0)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.11/dist-packages (from tortoise-api==0.3.0) (0.23.2)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.11/dist-packages (from tortoise-api==0.3.0) (1.0.0)
Requirement already satisfied: starlette in /usr/local/lib/python3.11/dist-packages (from tortoise-api==0.3.0) (0.27.0)
Requirement already satisfied: tortoise-orm[asyncpg] in /usr/local/lib/python3.11/dist-packages (from tortoise-api-model>=0.2.7->tortoise-api==0.3.0) (0.20.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.11/dist-packages (from starlette->tortoise-api==0.3.0) (3.7.1)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn->tortoise-api==0.3.0) (0.14.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from uvicorn->tortoise-api==0.3.0) (8.1.7)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.4.0->starlette->tortoise-api==0.3.0) (3.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.4.0->starlette->tortoise-api==0.3.0) (1.3.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.11/dist-packages (from tortoise-orm[asyncpg]->tortoise-api-model>=0.2.7->tortoise-api==0.3.0) (2023.3.post1)
Requirement already satisfied: pypika-tortoise<0.2.0,>=0.1.6 in /usr/local/lib/python3.11/dist-packages (from tortoise-orm[asyncpg]->tortoise-api-model>=0.2.7->tortoise-api==0.3.0) (0.1.6)
Requirement already satisfied: iso8601<2.0.0,>=1.0.2 in /usr/local/lib/python3.11/dist-packages (from tortoise-orm[asyncpg]->tortoise-api-model>=0.2.7->tortoise-api==0.3.0) (1.1.0)
Requirement already satisfied: aiosqlite<0.18.0,>=0.16.0 in /usr/local/lib/python3.11/dist-packages (from tortoise-orm[asyncpg]->tortoise-api-model>=0.2.7->tortoise-api==0.3.0) (0.17.0)
Requirement already satisfied: typing_extensions>=3.7.2 in /usr/local/lib/python3.11/dist-packages (from aiosqlite<0.18.0,>=0.16.0->tortoise-orm[asyncpg]->tortoise-api-model>=0.2.7->tortoise-api==0.3.0) (4.7.1)
tortoise-api is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@afdb675d1c30:/tts-generation-webui-main# python3.11 -m pip list
tortoise                  0.1.1
tortoise-api              0.3.0
tortoise-api-model        0.2.8
tortoise-orm              0.20.0

root@afdb675d1c30:/tts-generation-webui-main# python3.11 server.py
Traceback (most recent call last):
  File "/data/zhouyitong/tts-generation-webui-main/server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "/data/zhouyitong/tts-generation-webui-main/src/tortoise/generation_tab_tortoise.py", line 7, in <module>
    from src.tortoise.gen_tortoise import (
  File "/data/zhouyitong/tts-generation-webui-main/src/tortoise/gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
ModuleNotFoundError: No module named 'tortoise.api'

**Comment by rsxdalv** [comment]
I highly recommend using conda for an easy setup unless you are specifically trying to set it up as "raw" as you can. I personally use conda to develop this.

If you want to have a semi-manual approach, you can take a look at the one-click installer and take note of the:
python and torch* versions
virtual environment
pip install commands

**Comment by rsxdalv** [comment]
Assuming the issue is resolved, if not, please reopen.
