### ISSUE TITLE
Changed port and getting error

### ISSUE THREAD

**Issue by Dartvauder** [rsxdalv/tts-generation-webui#168]
Hello. I have a problem. I am just add --listen to webui.py and changed port to 7862 in settings, and get this error:

Loading extensions:
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded extension: empty_extension
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.
2023-09-10 22:31:12 | WARNING | xformers | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2023-09-10 22:31:12 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.
This is just a warning: No module named 'triton'
Starting Gradio server...
Gradio interface options:
  inline:               False
  inbrowser:            True
  share:                False
  debug:                False
  enable_queue:         True
  max_threads:          40
  auth:                 None
  auth_message:         None
  prevent_thread_lock:  False
  show_error:           False
  server_name:          0.0.0.0
  server_port:          7862
  show_tips:            False
  height:               500
  width:                100%
  favicon_path:         None
  ssl_keyfile:          None
  ssl_certfile:         None
  ssl_keyfile_password: None
  ssl_verify:           True
  quiet:                True
  show_api:             True
  file_directories:     None
  _frontend:            True
Traceback (most recent call last):
  File "F:\OpenSource\OfflineAi\AudioGenerationWebUI\MusicSoundWebUI\tts-generation-webui\server.py", line 160, in <module>
    start_server()
  File "F:\OpenSource\OfflineAi\AudioGenerationWebUI\MusicSoundWebUI\tts-generation-webui\server.py", line 154, in start_server
    demo.queue(
  File "F:\OpenSource\OfflineAi\AudioGenerationWebUI\MusicSoundWebUI\installer_files\env\lib\site-packages\gradio\blocks.py", line 1777, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "F:\OpenSource\OfflineAi\AudioGenerationWebUI\MusicSoundWebUI\installer_files\env\lib\site-packages\gradio\networking.py", line 121, in start_server
    s.bind((LOCALHOST_NAME, server_port))
TypeError: 'str' object cannot be interpreted as an integer

Done!

What i am need to do for fix it? Im deleting -- listen and its not help.

**Comment by rsxdalv** [comment]
Hi, thanks for finding this! I will fix it. I think --listen should not be necessary in any case.

Here's my config.json:
```json
{
  "model": {
    "text_use_gpu": true,
    "text_use_small": true,
    "coarse_use_gpu": true,
    "coarse_use_small": true,
    "fine_use_gpu": true,
    "fine_use_small": false,
    "codec_use_gpu": true
  },
  "load_models_on_startup": false,
  "gradio_interface_options": {
    "inline": false,
    "inbrowser": true,
    "share": false,
    "debug": false,
    "enable_queue": true,
    "max_threads": 40,
    "auth": null,
    "auth_message": null,
    "prevent_thread_lock": false,
    "show_error": true,
    "server_name": "0.0.0.0",
    "server_port": 7865,
    "show_tips": false,
    "height": 500,
    "width": "100%",
    "favicon_path": null,
    "ssl_keyfile": null,
    "ssl_certfile": null,
    "ssl_keyfile_password": null,
    "ssl_verify": true,
    "quiet": false,
    "show_api": false,
    "file_directories": null,
    "_frontend": true
  }
}
```

If you change it here, it will be an integer and it should work until I fix it properly in the UI.

**Comment by rsxdalv** [comment]
The location is similar to:
```
\one-click-installers-tts-main\tts-generation-webui\config.json
```

**Comment by Dartvauder** [comment]
Thanky very much! All work good

**Comment by rsxdalv** [comment]
Will be fixed in the newest update.
