### ISSUE TITLE
[Feature Request]: Audio quality Enhancer. Just came out could be used for everything. - AudioSR

### ISSUE THREAD

**Issue by Maki9009** [rsxdalv/tts-generation-webui#170]
https://github.com/haoheliu/versatile_audio_super_resolution
https://audioldm.github.io/audiosr/
the demos are promising

**Comment by rsxdalv** [comment]
Thanks for showing it!
I would want it but it's licensed as:
Attribution-NonCommercial-ShareAlike 4.0 International



This license is almost like saying "look at the cool thing I made, but
don't use it in you creation". It's unfortunately not "open source".

If I include it into this project, the entire project becomes this license.

I think the only thing I could do is instruct you how to integrate it into
the project. Then, as long as you don't redistribute it, it's usable.

**Comment by rsxdalv** [comment]
With this one it's similar to coqui. They have made an informed choice (not just here, in multiple places), and it completely makes these projects unusable.

Any project that uses them (AudioLDM, Audio super resolution etc by haoheliu that has CC BY NC 4.0) has a risky license status.
