### ISSUE TITLE
Will you add Vall-e-x repo? Looks promising

### ISSUE THREAD

**Issue by maxbizz** [rsxdalv/tts-generation-webui#172]
Hi,
I have been following this repo for sometime after it was released a week ago. https://github.com/Plachtaa/VALL-E-X. I really liked the outputs. Are you considering adding it to your repo? Then this would be a great idea. Bark, Tortoise, RVC, Vall-e together

**Comment by rsxdalv** [comment]
Thank you, I want to add it. The license is compatible, it's based on a
similar architecture as the other models here and it's promising! I hope
that the dependencies will work out easily.

**Comment by rsxdalv** [comment]
Long very long awaited update - I'm working on it, although the repository is not formatted as a package. Thus first I have to change the codebase to work as a package which might be quite troublesome. Any alternative solution where I would just download the project and install it not as a package is likely to lead to bugs in development and problems for users.

Here's my fork https://github.com/rsxdalv/VALL-E-X

**Comment by rsxdalv** [comment]
Added as a demo. Vall-E-X really did impress me while working on it, I wish I had integrated it sooner. I will close this issue as it is included now. If further improvements or suggestions arise, please open a new issue.
