### ISSUE TITLE
So close to prefect, but no WebUI launches.

### ISSUE THREAD

**Issue by Benzene82** [rsxdalv/tts-generation-webui#177]
This would be a dream come true for the project I am working on. I've installed Stable Diffusion, Automatic1111, XL, ComfyUI. I'm not a coder and the one click install for windows does everything except opening a WebUI. Tried everything in INSTRUCTIONS.txt and I just get Done! press any key...   The only Red text during update_windows.bat is this:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairseq 0.12.4 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.4 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
Successfully installed antlr4-python3-runtime-4.9.3 hydra-core-1.3.2 omegaconf-2.3.0

Any help to resolve would be greatly appreciated. Thanks.

**Comment by rsxdalv** [comment]
Hi, that's a little odd. The pip issue is normal (it's because these models
like bark and audiocraft have slightly different dependencies).

Are you running anything else, like stable diffusion at the same time?

The default port is 7860 so it's trying to use that.

Are you using any flags?

**Comment by rsxdalv** [comment]
And most importantly: could you try to copy paste the full log that you are
seeing?

**Comment by rsxdalv** [comment]
This might have been the same issues as others.

The repo has been updated. The change is that now it will install beartype==0.15.0, updating should fix it.

**Comment by Benzene82** [comment]
The update fixed it. I wasn't running Stable Diffusion at the time. If you
still want the full log, let me know.

Thank you so much for the quick response and the update!

**Comment by Benzene82** [comment]
I was hoping to get Tortoise TTS working. I was sifting through GitHub
looking for a source, or checkpoint. I see TTS doesn't really work like
that. I generated a few sentences, as you suggested in other issue posts,
those models download but the TortoiseTTS model folder only has the
.gitkeep file. I watched all the videos in the <code> but those relate to
RVC. Thank you for your time.
Here is the ERROR log...

Running on local URL:  http://0.0.0.0:7860
Traceback (most recent call last):
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\gradio\routes.py",
line 437, in run_predict
    output = await app.get_blocks().process_api(
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\gradio\blocks.py",
line 1352, in process_api
    result = await self.call_function(
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\gradio\blocks.py",
line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\anyio\to_thread.py",
line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py",
line 877, in run_sync_in_worker_thread
    return await future
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py",
line 807, in run
    result = context.run(func, *args)
  File "V:\ZTorTTSWebUI\tts-generation-webui\src\tortoise\gen_tortoise.py",
line 49, in switch_model
    get_tts(
  File "V:\ZTorTTSWebUI\tts-generation-webui\src\tortoise\gen_tortoise.py",
line 84, in get_tts
    MODEL = TextToSpeech(
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\tortoise\api.py",
line 233, in __init__
    self.tokenizer = VoiceBpeTokenizer(
  File
"V:\ZTorTTSWebUI\installer_files\env\lib\site-packages\tortoise\utils\tokenizer.py",
line 174, in __init__
    self.tokenizer = Tokenizer.from_file(
Exception: stream did not contain valid UTF-8
