### ISSUE TITLE
Bark API

### ISSUE THREAD

**Issue by mt123456789** [rsxdalv/tts-generation-webui#183]
Hi there,

I'm trying to use the Bark TTS model with its API, but I'm running into some issues. I've followed the documentation, but I'm still facing problems. Here are the issues I'm encountering:

. **API Usage**: I'm not entirely sure how to use Bark with its API. I've looked at the documentation, but I'm having trouble understanding the steps involved in generating speech using the API.

. **Speaker**: I'd like to clone a specific speaker's voice, but I'm not sure how to specify the speaker ID or use a pre-existing speaker file. Could you provide an example of how to do this?

. **Saving Output**: After generating speech, I want to save the resulting audio as an MP3 file. Could you provide an example of how to do this?

**Comment by rsxdalv** [comment]
Please follow the instructions on the main bark repo. When you make your own script here, you can assume that bark is installed and try this:
`
from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)

# save audio to disk
write_wav("bark_generation.wav", SAMPLE_RATE, audio_array)
  
# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)
`

**Comment by rsxdalv** [comment]
Closing unless there's a further discussion needed.
