### ISSUE TITLE
[Question] How do I add a custom tokenizer to Bark voice training?

### ISSUE THREAD

**Issue by lilskippyy** [rsxdalv/tts-generation-webui#188]
I would like to add a custom pth tokenizer that I download for a different language not available on the default options. 

Is it possible to do it? If so, how can I do it?

**Comment by rsxdalv** [comment]
Hi, did you download it from HuggingFace? If you format the input correctly (same as the others), type it into the drop-down and hit enter it will automatically apply.

Also is the tokenizer in the official list? Then I can update from the list, that's what I actually have done before.

**Comment by lilskippyy** [comment]
I donwloaded it from here:
https://huggingface.co/MadVoyager/bark-voice-cloning-portuguese-HuBERT-quantizer

how could I format it? I try putting in \tts-generation-webui\data\models\hubert, but it won't show on the list

Thanks for answering !

**Comment by rsxdalv** [comment]
Should be
```
portuguese-HuBERT-quantizer_24_epoch.pth @ MadVoyager/bark-voice-cloning-portuguese-HuBERT-quantizer
```

I added it to the repo

**Comment by lilskippyy** [comment]
thank you!
