### ISSUE TITLE
can't find the voice clone tab

### ISSUE THREAD

**Issue by Username69992872** [rsxdalv/tts-generation-webui#19]
where is the voice clone tab? I cab see it on the git page, but its not there on my webui?

**Comment by rsxdalv** [comment]
I'll check it tomorrow. Could you please verify the commit hash/version?

**Comment by Vdrio** [comment]
tab_voice_clone_demo gives module not found error and I was unable to start the webui.

The fix was to comment out line 12 and line 126 in server.py. This starts it without the voice cloning tab. Hope this helps in figuring out the issue.

**Comment by Vdrio** [comment]
I was using the one click installer v3.1 on windows btw

**Comment by rsxdalv** [comment]
Could you show the error, please? I would like to make a fix to the installer to include the missing modules

**Comment by Vdrio** [comment]
Sure thing, this is the error I got before commenting out line 12 and 126 of server.py. This is a screenshot of what I see after running start_windows.bat:
![Screenshot 2023-05-31 031750](https://github.com/rsxdalv/tts-generation-webui/assets/40824150/7e845226-cc62-4175-9604-589879fdb987)

**Comment by rsxdalv** [comment]
@Vdrio fixed with https://github.com/rsxdalv/one-click-installers-tts/releases/tag/v4.0
You can just git pull or copy paste over the new release files (changed only webui.py) and run "update" command

**Comment by rsxdalv** [comment]
When installing with v4.0 installer (linked on README.md page) the voice cloning will be installed. If there are further issues or questions about updates, please reopen the issue.
