### ISSUE TITLE
does this work on amd gpus

### ISSUE THREAD

**Issue by Pickymarker** [rsxdalv/tts-generation-webui#194]
does this work on amd gpus

**Comment by rsxdalv** [comment]
The installer does not but if you manage to install it manually, some
models can work. For example, bark is known to work with some setup. But
other models, like audiocraft, do not support anything other than CUDA.
However, *eventually* they all might support AMD.

You can always install the CPU version and start from there. Modern CPUs
run slow but not horribly slow.

**Comment by rsxdalv** [comment]
As this is the current state, I will close the issue for now.

Also something to add - for example, _Bark_ has some AMD community that managed to run it. It used to require manual steps, but they did it, so if you search you might find it. Perhaps bark-infinity by Jonathan has a good insight.
