### ISSUE TITLE
Problems when install on macOS

### ISSUE THREAD

**Issue by paulocoutinhox** [rsxdalv/tts-generation-webui#196]
Hi,

I have this error:

```
Building wheels for collected packages: torchcrepe, rvc-beta, pyworld
  Building wheel for torchcrepe (setup.py) ... done
  Created wheel for torchcrepe: filename=torchcrepe-0.0.20-py3-none-any.whl size=72326240 sha256=f1883703d9f2ae72ce72b648f4a2eff7a361b136d35976dbc9c185e186846c34
  Stored in directory: /private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-ephem-wheel-cache-9zofukgn/wheels/4a/7c/9f/170aad22b22218ca80febc6cf9f321b105adfed5c6930233fe
  Building wheel for rvc-beta (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for rvc-beta (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "/Users/paulo/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/paulo/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/paulo/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel
          return WheelBuilder.make_in(
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 87, in make_in
          wb.build(target_dir=directory)
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 123, in build
          self._copy_module(zip_file)
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 234, in _copy_module
          to_add = self.find_files_to_add()
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 200, in find_files_to_add
          if self.is_excluded(
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 143, in is_excluded
          if exclude_path.as_posix() in self.find_excluded_files(fmt=self.format):
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 111, in find_excluded_files
          vcs_ignored_files = set(vcs.get_ignored_files()) if vcs else set()
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/vcs/git.py", line 340, in get_ignored_files
          output = self.run(*args)
        File "/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-build-env-ht4n8qb8/overlay/lib/python3.10/site-packages/poetry/core/vcs/git.py", line 373, in run
          subprocess.check_output(
        File "/Users/paulo/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/paulo/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['git', '--git-dir', '/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-install-yby4jxs1/rvc-beta_012b38e2953241258889a6c232b364c6/.git', '--work-tree', '/private/var/folders/0j/1vzxlz_d135_p0gs5jjc428c0000gn/T/pip-install-yby4jxs1/rvc-beta_012b38e2953241258889a6c232b364c6', 'ls-files', '--others', '-i', '--exclude-standard']' returned non-zero exit status 128.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rvc-beta
  Building wheel for pyworld (pyproject.toml) ... done
  Created wheel for pyworld: filename=pyworld-0.3.4-cp310-cp310-macosx_11_0_arm64.whl size=175721 sha256=bd570dbf3ffd57f022bfb92349e81633d42d828e319da9b2242a2cdcddbe8654
  Stored in directory: /Users/paulo/Library/Caches/pip/wheels/66/09/8a/a1d79b73d59756f66e9bfe55a199840efc7473adb76ddacdfd
Successfully built torchcrepe pyworld
Failed to build rvc-beta
ERROR: Could not build wheels for rvc-beta, which is required to install pyproject.toml-based projects
```

Also, how can i completely remove this?

Thanks.

**Comment by rsxdalv** [comment]
Hi, thanks for the report. It seems that git just failed in between. May I ask if git is working fine on your machine?
Also to delete, one half is the one-click-installer directory, but the other part is in the cache folders.
You have HuggingFace cache and torch cache. These caches are shared between projects so if you delete everything you might need to download something (though it happens automatically) for another project again.

**Comment by paulocoutinhox** [comment]
Hi,

Yes, git is working nice, i use it all days.

Yes, i want delete all these caches. Where they are?

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

It is not installing, either opening the web ui.

**Comment by jaylex32** [comment]
Can we fix this issue? I’m having the same problem running the start.sh in a macOS M1 chip in Ventura.

**Comment by rsxdalv** [comment]
Might have to give up automatic installation for RVC on Mac. Although it
used to work, it sounds like now it's potentially breaking.

**Comment by rsxdalv** [comment]
I researched more and this seems like a tough one: https://github.com/pytorch/audio/issues/62

If this is the matching issue, it would mean that conda isn't choosing the right "platform", something that becomes very complicated to handle very quickly.

> Can we fix this issue? I’m having the same problem running the start.sh in a macOS M1 chip in Ventura.

Also, just to clarify - _this_ is a different issue you are talking about. The issue for this user was probably the XCode's crappy git that doesn't work like it should, as seen by the git command returning an error in the original log.

**Comment by rsxdalv** [comment]
@testter21

I can't guarantee it, but this might work (run within conda with `cmd_macos.sh`):
```
conda install torchaudio=2.0.0
```

I am seeing that the version of torchaudio no longer matches the pytorch. I will investigate further at some point, but this could fix the installation.

**Comment by testter21** [comment]
tester@testers-MBP one-click-installers-tts % chmod +x ./cmd_macos.sh  
tester@testers-MBP one-click-installers-tts % ./cmd_macos.sh

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
(/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env) bash-3.2$ conda install torchaudio=2.0.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio=2.0.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env) bash-3.2$

**Comment by rsxdalv** [comment]
My bad, here's the command with the relevant _conda channels_:
```
conda install -y -k torchaudio=2.0.0 -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia
```

**Comment by testter21** [comment]
Ok, so webui starts. Current log is this:

tester@testers-MBP ~ % cd /Users/tester/Downloads/xtts/one-click-installers-tts/
tester@testers-MBP one-click-installers-tts % chmod +x ./start_macos.sh
tester@testers-MBP one-click-installers-tts % ./start_macos.sh
Loading extensions:
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: empty_extension
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.
2023-12-12 21:12:05 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Failed to load musicgen demo
No module named 'audiocraft'
Failed to load rvc demo
No module named 'rvc_beta'
Failed to load demucs demo
No module named 'demucs'
Starting Gradio server...
Gradio interface options:
  inline:               False
  inbrowser:            True
  share:                False
  debug:                False
  enable_queue:         True
  max_threads:          40
  auth:                 None
  auth_message:         None
  prevent_thread_lock:  False
  show_error:           False
  server_name:          0.0.0.0
  server_port:          None
  show_tips:            False
  height:               500
  width:                100%
  favicon_path:         None
  ssl_keyfile:          None
  ssl_certfile:         None
  ssl_keyfile_password: None
  ssl_verify:           True
  quiet:                True
  show_api:             True
  file_directories:     None
  _frontend:            True
Running on local URL:  http://0.0.0.0:7860

Nothing is missing here in relation to multilingual voice-cloning/tts tabs?

Models download automatically, or have to be searched and downloaded manually? I'm specifically interested to have them gathered in some hassle-free path, so that I can for example backup whole project simply by compressing it and keeping copy somewhere (so that at least the project runs on the same machine in the future).

**Comment by rsxdalv** [comment]
> Ok, so webui starts. Current log is this:
> 
> tester@testers-MBP ~ % cd /Users/tester/Downloads/xtts/one-click-installers-tts/ tester@testers-MBP one-click-installers-tts % chmod +x ./start_macos.sh tester@testers-MBP one-click-installers-tts % ./start_macos.sh Loading extensions: Loaded extension: callback_save_generation_ffmpeg Loaded extension: empty_extension Loaded extension: callback_save_generation_musicgen_ffmpeg Loaded 2 callback_save_generation extensions. Loaded 1 callback_save_generation_musicgen extensions. 2023-12-12 21:12:05 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX Failed to load musicgen demo No module named 'audiocraft' Failed to load rvc demo No module named 'rvc_beta' Failed to load demucs demo No module named 'demucs' Starting Gradio server... Gradio interface options: inline: False inbrowser: True share: False debug: False enable_queue: True max_threads: 40 auth: None auth_message: None prevent_thread_lock: False show_error: False server_name: 0.0.0.0 server_port: None show_tips: False height: 500 width: 100% favicon_path: None ssl_keyfile: None ssl_certfile: None ssl_keyfile_password: None ssl_verify: True quiet: True show_api: True file_directories: None _frontend: True Running on local URL: http://0.0.0.0:7860
> 
> Nothing is missing here in relation to multilingual voice-cloning/tts tabs?
> 
> Models download automatically, or have to be searched and downloaded manually? I'm specifically interested to have them gathered in some hassle-free path, so that I can for example backup whole project simply by compressing it and keeping copy somewhere (so that at least the project runs on the same machine in the future).

The modern models (2023+) generally download automatically. There are things that require extra installation on Macs because of limited or no official support (i.e., Facebook didn't build support for Mac in audiocraft). Bark has multiple languages, Tortoise _can_ do many languages but it requires finding the models and setting them up, the default is English.

**Comment by testter21** [comment]
Okay, a quick question. I started webui, went to bark voice clone tab, and selected model for polish language. It looks that it's downloading, or at least the webui shows progress time and queue mark. I don't see anything changed on the terminal window however (should I? In some other apps, downloads were indicated on terminal).

And where is the download folder? I mean - is it within the tts webui folder, or somewhere outside?

**Comment by testter21** [comment]
Okay, so probably the webui is not downloading anything.
The counter goes into infinity, but on the hugginggface via github
https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer?tab=readme-ov-file
https://huggingface.co/Hobis/bark-voice-cloning-polish-HuBERT-quantizer/tree/main
PL model is just 250MB in size if this is what is supposed to be.
Also, I see no subfolder named hubert is created in /data/models/
So I'm putting it there manually and we see what happens.

**Comment by testter21** [comment]
If I put the model to destination fole and restart, nothing more happens. Queue is counting time ad infinity when selecting polish model.

In the meantime. If I just start webui and in the "Generation (Bark)" tab switch to "or Use a voice:", terminal outputs these errors. I don't know if this is normal at this point.

Running on local URL:  http://0.0.0.0:7860
2023-12-13 18:46:40 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='ekdi7gy1mt_9' coro=<Queue.process_events() done, defined at /Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['or Use a voice...ion_hash': 'ekdi7gy1mt'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['or Use a voice...ion_hash': 'ekdi7gy1mt'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

**Comment by testter21** [comment]
From what I see on colab version, when selecting polish model on second tab, I get error (although 'queue' mark changes to 'processing' mark), plus on first tab, webui is loaded fully.

**Comment by rsxdalv** [comment]
> If I put the model to destination fole and restart, nothing more happens. Queue is counting time ad infinity when selecting polish model.
> 
> In the meantime. If I just start webui and in the "Generation (Bark)" tab switch to "or Use a voice:", terminal outputs these errors. I don't know if this is normal at this point.
> 
> Running on local URL: http://0.0.0.0:7860 2023-12-13 18:46:40 | ERROR | asyncio | Task exception was never retrieved future: <Task finished name='ekdi7gy1mt_9' coro=<Queue.process_events() done, defined at /Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody event_id Field required [type=missing, input_value={'data': ['or Use a voice...ion_hash': 'ekdi7gy1mt'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.5/v/missing> Traceback (most recent call last): File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 346, in process_events client_awake = await self.gather_event_data(event) File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 219, in gather_event_data data, client_awake = await self.get_message(event, timeout=receive_timeout) File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 448, in get_message return PredictBody(**data), True File "/Users/tester/Downloads/xtts/one-click-installers-tts/installer_files/env/lib/python3.10/site-packages/pydantic/main.py", line 164, in **init** **pydantic_self**.**pydantic_validator**.validate_python(data, self_instance=**pydantic_self**) pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody event_id Field required [type=missing, input_value={'data': ['or Use a voice...ion_hash': 'ekdi7gy1mt'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.5/v/missing

oh no that's a bad one - that's an error in gradio. It might be a gradio bug, or something that requires a restart or a reinstall or there's a bad gradio _package_ (gradio _would_ work but there are two different packages)

**Comment by testter21** [comment]
It's the same after restarts.

I followed only your instructions and used scripts from your github. Nothing external added. So as of right now, this will be probably the end result when someone attempts to use this project "as is" on mac.

Any ideas on how this could be continued?

**Comment by rsxdalv** [comment]
I can research this and maybe get a workable solution. As for the packages - I know that you used the correct script and thanks to you I also have the full log for debugging. This is more of a "that shouldn't even break" situation which is why I mentioned all the possible sources of failure.

**Comment by testter21** [comment]
Okay, thanks, so I'm waiting for further info.
In any case, I can help with testing.

**Comment by rsxdalv** [comment]
After a long research, I found that it could be related to this:
https://github.com/oobabooga/text-generation-webui/issues/3042

They suggest two potential solutions there (which partially match what I am seeing):
* upgrade gradio `pip install 'gradio>=3.36.1'`
* OR downgrade fastapi `pip install 'fastapi==0.95.2'`
These commands need to be run within the conda environment (i.e, by cmd_macos.sh)

Myself I have confirmed that I have the following versions:
```
(C:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env) C:\Users\admin\Desktop\one-click-installers-tts-main>pip show fastapi
Name: fastapi
Version: 0.100.0
Summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
Home-page:
Author:
Author-email: Sebastián Ramírez <tiangolo@gmail.com>
License:
Location: c:\users\admin\desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages
Requires: pydantic, starlette, typing-extensions
Required-by: gradio

(C:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env) C:\Users\admin\Desktop\one-click-installers-tts-main>pip show gradio
Name: gradio
Version: 3.35.2
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License:
Location: c:\users\admin\desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages
Requires: aiofiles, aiohttp, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, jinja2, markdown-it-py, markupsafe, matplotlib, mdit-py-plugins, numpy, orjson, pandas, pillow, pydantic, pydub, pygments, python-multipart, pyyaml, requests, semantic-version, uvicorn, websockets
Required-by: audiocraft, rvc-beta
```

_If this has been the core issue, how could it happen?_ fastapi project might have made an update that did not match gradio's expectations.

**Comment by testter21** [comment]
Ok, I will give a try in a few days and let you know.
