### ISSUE TITLE
MusicGen Error

### ISSUE THREAD

**Issue by GalenMarek14** [rsxdalv/tts-generation-webui#199]
I installed this using the one-click installer. Gradio opens without a problem but I can't use MusicGen. 4-5 seconds after I press the generate button it gives this error:
(Log of the first opening):

> Env file not found. Creating default env.
> Config file not found. Creating default config.
> Loading extensions:
> Loaded extension: callback_save_generation_ffmpeg
> Loaded extension: callback_save_generation_musicgen_ffmpeg
> Loaded extension: empty_extension
> Loaded 2 callback_save_generation extensions.
> Loaded 1 callback_save_generation_musicgen extensions.
> 2023-10-22 01:01:43 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
> 2023-10-22 01:01:43 | WARNING | xformers | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
>     PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.0.0+cpu)
>     Python  3.10.11 (you have 3.10.13)
>   Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
>   Memory-efficient attention, SwiGLU, sparse and more won't be available.
>   Set XFORMERS_MORE_DETAILS=1 for more details
> 2023-10-22 01:01:44 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.
> This is just a warning: No module named 'triton'
> Failed to load rvc demo
> No module named 'rvc_beta'
> Starting Gradio server...
> Gradio interface options:
>   inline:               False
>   inbrowser:            True
>   share:                False
>   debug:                False
>   enable_queue:         True
>   max_threads:          40
>   auth:                 None
>   auth_message:         None
>   prevent_thread_lock:  False
>   show_error:           False
>   server_name:          0.0.0.0
>   server_port:          None
>   show_tips:            False
>   height:               500
>   width:                100%
>   favicon_path:         None
>   ssl_keyfile:          None
>   ssl_certfile:         None
>   ssl_keyfile_password: None
>   ssl_verify:           True
>   quiet:                True
>   show_api:             True
>   file_directories:     None
>   _frontend:            True
> Running on local URL:  http://0.0.0.0:7860
> Loading model facebook/musicgen-small
> Traceback (most recent call last):
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2004, in _from_pretrained
>     tokenizer = cls(*init_inputs, **init_kwargs)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\transformers\models\t5\tokenization_t5.py", line 190, in __init__
>     self.sp_model.Load(vocab_file)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
>     return self.LoadFromFile(model_file)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
>     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
> OSError: Not found: "C:\Users\Özkan PC/.cache\huggingface\hub\models--t5-base\snapshots\fe6d9bf207cd3337512ca838a8b453f87a9178ef\spiece.model": No such file or directory Error #2
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
>     output = await app.get_blocks().process_api(
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
>     result = await self.call_function(
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1077, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\tts-generation-webui\src\musicgen\musicgen_tab.py", line 146, in generate
>     MODEL = load_model(model)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\tts-generation-webui\src\musicgen\musicgen_tab.py", line 125, in load_model
>     return MusicGen.get_pretrained(version)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\audiocraft\models\musicgen.py", line 117, in get_pretrained
>     lm = load_lm_model(name, device=device)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\audiocraft\models\loaders.py", line 111, in load_lm_model
>     model = builders.get_lm_model(cfg)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\audiocraft\models\builders.py", line 97, in get_lm_model
>     condition_provider = get_conditioner_provider(kwargs["dim"], cfg).to(cfg.device)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\audiocraft\models\builders.py", line 137, in get_conditioner_provider
>     conditioners[str(cond)] = T5Conditioner(output_dim=output_dim, device=device, **model_args)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\audiocraft\modules\conditioners.py", line 415, in __init__
>     self.t5_tokenizer = T5Tokenizer.from_pretrained(name)
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1841, in from_pretrained
>     return cls._from_pretrained(
>   File "D:\Audiocraft\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2006, in _from_pretrained
>     raise OSError(
> OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.

**Comment by rsxdalv** [comment]
The path is a bit unique, is it really `C:\Users\Özkan PC/.cache\huggingface`. I can't imagine the reason for one slash being the other way around. Also, is there enough space on C disk for the models? You might want to use a different location for the model weights cache. (but changing it without manually copying would mean they download again.)

**Comment by GalenMarek14** [comment]
Is there a chance that space or non-English characters in the folder name causing this? It didn't cause any problems in the past for other programs though...

C has 87 GB of space, is enough I think? The installer is in D, is it normal for it to store caches in C? I can change and try again if you want, though I don't know how to do it.

Downloading again is no problem really if it can solve this. I already did several times.

By the way, are these errors(?) a problem?

> 2023-10-22 01:01:43 | WARNING | xformers | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
> PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.0.0+cpu)
> Python 3.10.11 (you have 3.10.13)
> Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
> Memory-efficient attention, SwiGLU, sparse and more won't be available.
> Set XFORMERS_MORE_DETAILS=1 for more details
> 2023-10-22 01:01:44 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.

**Comment by rsxdalv** [comment]
Yes, by default _everything_ on Windows gets stored on C as long as it's a cache, temporary files. This cache is cross-project so there are downsides - space and file download - to not having it on a "global" level. As suggested in a different thread, a better solution would be a nice "cache manager". Just FYI - if you install another bark, tortoise TTS project, several gigabytes of model weights will be shared and will take up less space!

87 is more than enough space.

One error suggests that you have CPU torch installed, is this intentional, or do you want to be using CUDA?

As far as the path - I don't know with absolute certainty, it might but usually shouldn't be a problem in 2023.

**Comment by GalenMarek14** [comment]
I will try my luck with a cache manager then. I checked the weird address and the file actually exists in that folder. Audiocraft just can't access it for some reason (I also tried launching the bat file as administrator). I will try to change the cache folder and update it here.

> OSError: Not found: "C:\Users\Özkan PC/.cache\huggingface\hub\models--t5-base\snapshots\fe6d9bf207cd3337512ca838a8b453f87a9178ef\spiece.model": No such file or directory Error https://github.com/rsxdalv/tts-generation-webui/pull/2

![image](https://github.com/rsxdalv/tts-generation-webui/assets/148660654/6e08b795-8dc6-4542-8c81-c711a9557965)


Torch version wasn't intentional. I used the one-click installer so it installed everything automatically in its folder in D. I tried changing global Python and torch versions manually but it stayed the same. My global Python is 3.10.11, here it's 3.10.13. 

I tried uninstalling global PyTorch and installing the required CUDA version manually using this code:

> pip install torch==2.0.0+cu118 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Manual PyTorch installation log:

> Successfully installed torch-2.0.0+cu118
> WARNING: Ignoring invalid distribution -pencv-python (c:\users\özkan pc\appdata\local\programs\python\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -pencv-python (c:\users\özkan pc\appdata\local\programs\python\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -pencv-python (c:\users\özkan pc\appdata\local\programs\python\python310\lib\site-packages)
> 
> [notice] A new release of pip is available: 23.0.1 -> 23.3
> [notice] To update, run: python.exe -m pip install --upgrade pip
> 
> C:\Users\Özkan PC>pip show torch
> WARNING: Ignoring invalid distribution -pencv-python (c:\users\özkan pc\appdata\local\programs\python\python310\lib\site-packages)
> Name: torch
> Version: 2.0.0+cu118
> Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
> Home-page: https://pytorch.org/
> Author: PyTorch Team
> Author-email: packages@pytorch.org
> License: BSD-3
> Location: c:\users\özkan pc\appdata\local\programs\python\python310\lib\site-packages
> Requires: filelock, jinja2, networkx, sympy, typing-extensions
> Required-by: accelerate, audiocraft, audiolm-pytorch, demucs, dora-search, ema-pytorch, encodec, fairseq, flashy, julius, lion-pytorch, local-attention, openunmix, rotary-embedding-torch, suno-bark, torchaudio, torchmetrics, torchvision, vector-quantize-pytorch, vocos, xformers

But it still stays the same in the WebUI console. I don't know how to change venv versions inside that folder but I can try it if you need me to do?

I will try changing the cache folder for now. Thanks for the help!

**Comment by rsxdalv** [comment]
The project uses it's own python, pip versions and runs in its own virtual (conda) environment. You can access the consule with the cmd_windows. There you can _try_ to install whichever pytorch you want etc. It's a bit strange that it installed CPU, might mean that some project is causing a problem or a breakage in a new way (some patches already prevent this from happening).

**Comment by GalenMarek14** [comment]
I feel like an idiot now... Yeah, the problem seems to be the name of the cache folder. I changed it inside Gradio settings for Hugging Face and it works perfectly now. Also tried to install the correct Python and PyTorch versions with cmd, but I think it broke after I uninstalled Python to install the correct version. update_windows.bat didn't solve it either so I need to redownload it again.

For some reason, PyTorch error resolved by itself after reinstalling the entire thing. It works perfectly now.

Thank you so much.

**Comment by rsxdalv** [comment]
> I feel like an idiot now... Yeah, the problem seems to be the name of the cache folder. I changed it inside Gradio settings for Hugging Face and it works perfectly now. Also tried to install the correct Python and PyTorch versions with cmd, but I think it broke after I uninstalled Python to install the correct version. update_windows.bat didn't solve it either so I need to redownload it again.
> 
> For some reason, PyTorch error resolved by itself after reinstalling the entire thing. It works perfectly now.
> 
> Thank you so much.

These things tend to break in countless strange ways.
