### ISSUE TITLE
History tab broken after using for first time

### ISSUE THREAD

**Issue by Vdrio** [rsxdalv/tts-generation-webui#20]
Using the v3.1 one click installer, I had to comment out lines 12 and 126 of tts-generation-webui/server.py to get the start_windows.bat to work. Ran a few tests and got great results with both Bark and Tortoise. 
After closing and restarting the webui, i got the error: ValueError: not enough values to unpack (expected 2, got 1). A screenshot is below of what the Terminal looks after running start_windows.bat

A temporary fix is commenting out line 129 of tts-generation-webui/server.py but this removes the History tab.

![Screenshot 2023-05-31 033307](https://github.com/rsxdalv/tts-generation-webui/assets/40824150/65cc5578-5c65-493b-9b05-3e6f6e5e374e)

**Comment by rsxdalv** [comment]
Pushed a patch
https://github.com/rsxdalv/tts-generation-webui/commit/75001da01c083d8fbf506d532da9dfab7a5d4acf

**Comment by ZENwww** [comment]
![Screenshot_8](https://github.com/rsxdalv/tts-generation-webui/assets/57990038/c3d6ddf0-2bc6-4426-9da9-5ae1cb716629)

Still doesn't work.

**Comment by Vdrio** [comment]
> ![Screenshot_8](https://user-images.githubusercontent.com/57990038/242740875-c3d6ddf0-2bc6-4426-9da9-5ae1cb716629.png)
> 
> Still doesn't work.

seems like you still need to comment out line 12 and 126 of tts-generation-webui/server.py ... The patch posted was for fixing the history tab, not the voice cloning tab.

**Comment by Vdrio** [comment]
I confirmed the latest patch fixes the history tab, thank you very much.  lines 12 and 126 of tts-generation-webui/server.py need to be commented out still as of now for the 3.1 installer to work

**Comment by rsxdalv** [comment]
Thank you for verifying and your patience! For the voice clone, I posted a
4.0 installer in the other issue. To describe the issue/fix - the installer
cloned the repository in the wrong place. Instead of models/ it clones it
into the root installation directory. The new installer clones it into
models/
