### ISSUE TITLE
[BUG] increasing seed when shouldn't

### ISSUE THREAD

**Issue by 520Pig520** [rsxdalv/tts-generation-webui#201]
for each line, it increase the seed when seed is defined, and it make things unstable in "Split prompt by lines" mode.
for each line it should pin the seed, or at least an option to pin or not seed is welcome.

**Comment by rsxdalv** [comment]
Thanks, I found the place of the bug.

Do you mind making this change and seeing if it works better for you?

https://github.com/rsxdalv/tts-generation-webui/blob/main/src/bark/generation_tab_bark.py#L406

change from
```python
                    waveform_temp=waveform_temp,
                    history_prompt=history_prompt,
                    history_prompt_semantic=history_prompt_semantic,
                    seed=seed, # ORIGINAL
                    index=i,
                )
```
to
```python
                    waveform_temp=waveform_temp,
                    history_prompt=history_prompt,
                    history_prompt_semantic=history_prompt_semantic,
                    seed=_original_seed, # Fix
                    index=i,
                )
```

I'm in the middle of making the React UI so it's a bit hard to finalize this fix now.

**Comment by rsxdalv** [comment]
The fix has been shipped already, and this problem should be gone. I will close the issue, please feel free to reopen or comment if there's lack of clarity or possible bug remaining.
