### ISSUE TITLE
Installation guidance and help for a newbee.

### ISSUE THREAD

**Issue by Miss0x** [rsxdalv/tts-generation-webui#206]
Is there any possiblity to see a guidance to introduce how to deploy the whole service on any other server in the future? 
I hope this would be great helpfut for those new students.
Thank you team.

**Comment by rsxdalv** [comment]
Docker is a way to deploy to a server. However, securing your deployment is
something that should not be forgotten. Reverse proxies, limited user
permissions and file access are recommended.

**Comment by Miss0x** [comment]
Thank you rsxdalv for your super fast reply. 
Actually I met a problem when I deploy this project on a cloud platform. I copied the code in your provided google colab notebook. Then everything worked just fine in my rented server, until the last step. 

This is the result of the last run command !python server.py --share. I can't call out the public link.
`Running on local URL:  http://0.0.0.0:7860/

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app/. 

Also please ensure that your antivirus or firewall is not blocking the binary file located at: /root/miniconda3/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2`

Is there any modification I should do in the load_config.py？

Thank you.

**Comment by rsxdalv** [comment]
Have you used other gradio projects like this before? I think there might be a small step missing

**Comment by Miss0x** [comment]
Finally I solve this problem, please allow me to say something. 

Due to some unknow connection failed reason, I dont have file: frpc_linux_amd64_v0.2 in the folder: /root/miniconda3/lib/python3.10/site-packages/gradio/.

Then I have to mannully download this from 
https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64, 

and give it permission by command `chmod +x frpc_linux_amd64_v0.2`

Restart the terminal then `!python server.py --share`

It's now working!

**Comment by rsxdalv** [comment]
Thank you for documenting this, hopefully people can find it if it happens again!
