### ISSUE TITLE
Where can I get the example voices from the samples show in the readme?

### ISSUE THREAD

**Issue by nospam2k** [rsxdalv/tts-generation-webui#216]
The title says it all. Thanks!

**Comment by rsxdalv** [comment]
There are more voices in the bark speaker directory. For those particular
ones, as far as I remember there was no voice used to generate them.

**Comment by nospam2k** [comment]
I don't understand. There must have been a voice to generate them?? Why would they be included as examples?

**Comment by rsxdalv** [comment]
There's an option to use no voice, to have it be fully creative. It's like
text to image rather than image to image.
