### ISSUE TITLE
one-click-installer: syntax error for cmd_macos.sh

### ISSUE THREAD

**Issue by audiocommander** [rsxdalv/tts-generation-webui#218]
Hello! Looks like an awesome project. 

I tried to follow the readme in ```one-click-installers-tts-6.0``` and because I just created a fresh conda env with AARM64 PyTorch, I thought it'd be nice to use the cmd_macos.sh installer.

However, this fails with a syntax error on zsh (default mac os shell, I'm on a MacBook Air M2):

```bash
% sh cmd_macos.sh 
cmd_macos.sh: line 12: syntax error near unexpected token `('
cmd_macos.sh: line 12: `bash --init-file <(echo "source \"$CONDA_ROOT_PREFIX/etc/profile.d/conda.sh\" && conda activate \"$INSTALL_ENV_DIR\"")'
```

**Comment by rsxdalv** [comment]
Although I can't say for sure, I'd like to point out that it's meant to set
up the entire conda stack for you, so there might be some strangeness if
it's trying to create from within conda (I'm not familiar with nested
condas).

Once I get back I can investigate if there's a zsh syntax error.

**Comment by audiocommander** [comment]
thanks! no worries and no stress. This isn't meant as a desperate call for help but rather an info that the installers don't seem to work straight of the box (if I didn't mess it up). I'm not a trained computer scientist but I do have quite some experience in coding and feel like I do have a stable background in setting up my conda envs. Maybe I can help, this project looks pretty cool.

**Comment by rsxdalv** [comment]
Thank you! If you are interested, you can take a look at the setup files.
They install python and pytorch as well as ffmpeg. Next, there is the
projects python install script which attempts to install as many
requirements files as possible.

Furthermore, for high compatibility, running a Linux container with pytorch
CPU would probably give you the most access to all the different models,
though it is painfully slow.

**Comment by audiocommander** [comment]
Great!
Well, I believe I could install pretty much everything in order to run server.py successfully and I'm looking at a gradio site in my browser. Cool!

I will see if I find out more in the next days (haven't tested, I can only guess not everything will work out of the box). 

Right now I can already say that the main problem with the install and update scripts is, that they uninstall working Metal-enabled PyTorch versions (2.2.0) and install oder CPU-only versions (2.0.0). I'm not sure about if xformers will even work on mac, but I could install something that was alright enough for audiocraft.

I think the only way to install PyTorch with Metal support is by using this (Apple recommended) command. At least some quick tests on my MacBook Air M2 run nicely and show that metal can be enabled with pytorch:

```bash
conda install pytorch torchvision torchaudio -c pytorch-nightly
```

Just had one major hiccup with gradio, but downgrading to 3.48.0 worked:
```bash
conda install gradio==3.48.0
```
(avoiding pip when conda install is available seems like a good strategy for me)

...will report more when I managed to play around a bit. I'm assuming that there are more things not yet working. But as I have already running bark in another env, I guess that most of it should theoretically work. Not blazingly fast but definitely not painfully slow. Enough to have some nerd fun with it...

**Comment by rsxdalv** [comment]
So as far as the installing torch 2.0.0 goes - it's hard to prevent it from happening. Most of the projects used here "just do it" so I need a workaround to prevent it from happening. And if I'm not mistaken, some models might not work with newer torch versions, I think it was tortoise.
A solution could be to just install the new torch at the very end. Though, already the installation time is 50% reinstalling packages just to make all of the projects "happy".

**Comment by rsxdalv** [comment]
Also, the project has now been upgraded to 3.48.0 hopefully reducing the issues for users.

**Comment by rsxdalv** [comment]
The project now reinstalls the newest version of PyTorch for non-cuda installs at the end of each update. Hopefully that resolves the issue.
