### ISSUE TITLE
Incompatibility between audiocraft and fairseq

### ISSUE THREAD

**Issue by TacitTactics** [rsxdalv/tts-generation-webui#223]
Is there a fix for installing manually? I am running in the problem of audiocraft requiring hydra-core==1.1 but fairseq only works with hydra-core==1.0.7.  Please help me with a fix. One-click installer always breaks. Below if what I am running:
Linux Mint 21.1
Nvidia 2080 TI
Driver is the recommended one 535 installed from Mint repo using APT package manager
Cuda toolkit is the 12-3 for the 535 driver
I am running in venv environment.
I installed the xformers==0.0.19 and ffmpeg manually before running the other requirements files. 
I even ran the update_linux.sh but it just calls the exisiting requirements files that have the conflicting versions. 

I love the work being done, but I cannot use it as shown on videos from 4 months ago on youtube.
The TTS project (https://github.com/coqui-ai/TTS) runs just fine on my rig, but this is CLI. I really want the webui to teach my students. Thank you

**Comment by rsxdalv** [comment]
What's the issue you are seeing? I know they report installation error but
anything else?

**Comment by TacitTactics** [comment]
No that was it for the manual installation. The webui loads with manual installation. The oneclick installer did not launch the browser. I just reformatted my box,  because I was having others issue. Now the oneclick installer launches the browser window.

**Comment by rsxdalv** [comment]
As I understand things are working now, right? I will close this issue, please feel free to reopen if that's not the case.
