### ISSUE TITLE
Stop button

### ISSUE THREAD

**Issue by BornSaint** [rsxdalv/tts-generation-webui#224]
Please, put a stop button to cancel the generation, because sometimes we misclick and have to wait too long to finish

**Comment by rsxdalv** [comment]
I'll check what I can do. The problem I had before was that I don't think I
saw a real way for gradio to implement that. Even now, it might be a hard
thing to make because the generation code is deep within. For long
generations it's a lot more doable.

**Comment by rsxdalv** [comment]
I have added a way to interrupt batches for MusicGen in the new React UI. I plan to expand this functionality to other generation types, although bark is a bit difficult because the code became way too convoluted.

**Comment by rsxdalv** [comment]
React UI uses interrupt as much as it can and generally it's a design goal to be able to stop any long generations. However, this project probably won't allow mid-generation interruptions for the time being as those require some custom code for each and every model.
