### ISSUE TITLE
Integration: Coqui AI

### ISSUE THREAD

**Issue by slavakurilyak** [rsxdalv/tts-generation-webui#226]
It would be great to see an integration with [TTS](https://github.com/coqui-ai/TTS) by @coqui-ai, similar to [bark](https://github.com/suno-ai/bark) by @suno-ai

For inspiration, check out [XTTS](https://huggingface.co/spaces/coqui/xtts) space on HuggingFace

**Comment by rsxdalv** [comment]
They have chosen this license: https://coqui.ai/cpml which makes it unreasonable to use xtts in open source projects. I have not investigated the latest version of XTTS but the older version was an improvement of Tortoise.

**Comment by rsxdalv** [comment]
Closing this issue. If they change the license for XTTS or modify CPML.
