### ISSUE TITLE
Question: Can I delete the installer_files folder?

### ISSUE THREAD

**Issue by bobcate** [rsxdalv/tts-generation-webui#227]
The title.
The one-click installer worked nicely and now I can generate speech.
Do I still need the installer files for updates or anything? Because it's taking up 20 gigs of space.

**Comment by bobcate** [comment]
Thank you for the clarification about the folder.

While I have no idea about Conda, I think that 8 gigs is the env folder.
I'll put what I found here for future reference:

It says [here](https://www.geeksforgeeks.org/how-to-delete-an-environment-in-conda/) that Conda creates environments for projects and when a project is complete, it's environment can be deleted.
[This source](https://www.freecodecamp.org/news/how-to-delete-an-environment-in-conda/) briefly explains how to delete an environment.

CMD couldn't find "conda" in my system to be able to use it's commands, so I found a conda.exe in the installer_files directory and tried using that. But `conda env list` only returns the base env which I believe cannot be deleted with a command.

Since you've warned that I'd have to redownload stuff in the future, I decided not to touch it unless I need that space back.

**Comment by rsxdalv** [comment]
Here's one of the commands: https://docs.conda.io/projects/conda/en/latest/commands/clean.html

**Comment by bobcate** [comment]
I opening cmd in /installer_files/conda/ , and calling `_conda clean -a` and it returns five lines of `There are no xxx to remove.`

**Comment by rsxdalv** [comment]
Got it, I'll try to recreate the exact command I used before.

**Comment by bobcate** [comment]
I don't have a conda installed on a system level. So, I'm cd'ing to the conda directory inside the installer folder and using the `_conda.exe` _(with an underscore character in front)_.
Maybe that's it?

**Comment by rsxdalv** [comment]
Use cmd_windows.bat then just conda without the underscore.

**Comment by bobcate** [comment]
That did it, cleaned about 3-4gigs. Thank you!

**Comment by rsxdalv** [comment]
Awesome, let's see if I can add it to the UI
