### ISSUE TITLE
One click Installer Not working on windows

### ISSUE THREAD

**Issue by aloksaurabh** [rsxdalv/tts-generation-webui#233]
Tried installing using one click installer on windows 10 fully patched and updated till date. I also have build tools installed. 
Below is the error after installation
Same error before and after update bat.
```Traceback (most recent call last):
  File "C:\Users\Alok\Documents\tts\tts-generation-webui\server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "C:\Users\Alok\Documents\tts\tts-generation-webui\src\tortoise\generation_tab_tortoise.py", line 7, in <module>
    from src.tortoise.gen_tortoise import (
  File "C:\Users\Alok\Documents\tts\tts-generation-webui\src\tortoise\gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
  File "C:\Users\Alok\Documents\tts\installer_files\env\lib\site-packages\tortoise\api.py", line 17, in <module>
    from tortoise.models.clvp import CLVP
  File "C:\Users\Alok\Documents\tts\installer_files\env\lib\site-packages\tortoise\models\clvp.py", line 7, in <module>
    from tortoise.models.transformer import Transformer
  File "C:\Users\Alok\Documents\tts\installer_files\env\lib\site-packages\tortoise\models\transformer.py", line 6, in <module>
    from rotary_embedding_torch import RotaryEmbedding, broadcat
ImportError: cannot import name 'broadcat' from 'rotary_embedding_torch' (C:\Users\Alok\Documents\tts\installer_files\env\lib\site-packages\rotary_embedding_torch\__init__.py)```

**Comment by rsxdalv** [comment]
Hi, thanks for the report. Is it possible to get the full installation log?

It might not be necessary, but it always helps so I ask just in case.

**Comment by rsxdalv** [comment]
Ok, I made an issue with the package so that it could be resolved properly. https://github.com/lucidrains/rotary-embedding-torch/issues/17

For now this requires manually downgrading that package to version 0.4.0

**Comment by aloksaurabh** [comment]
The installer does not save logs and windows cmd does not remember output after certain point. Best that one can do is .\start_windows.bat > logs.txt
[logs.txt](https://github.com/rsxdalv/tts-generation-webui/files/13692610/logs.txt)

But that does not put errors and warnings in logs file. I have attached that separately in another file. 
[logs_onscreen.txt](https://github.com/rsxdalv/tts-generation-webui/files/13692611/logs_onscreen.txt)

**Comment by rsxdalv** [comment]
Ok, this is issue has been resolved in tortoise project and will hopefully quickly enough trickle down to here.
To fix your installation you need to run:
`cmd_windows.bat`
then
`pip install rotary_embedding_torch==0.4.0`

**Comment by aloksaurabh** [comment]
Works.. 
Please close as needed.

**Comment by rsxdalv** [comment]
Thanks! I will close once this won't happen to new installers, hopefully that is very soon.

**Comment by rsxdalv** [comment]
Thanks to lucidrains installation will succeed for everyone now.
https://github.com/lucidrains/rotary-embedding-torch/issues/17
