### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by Sinicyn78** [rsxdalv/tts-generation-webui#236]
When cloning into Bark, is the generation only in English or is there a way in other languages?

**Comment by rsxdalv** [comment]
If you change the tokenizer you can do other languages.

**Comment by Sinicyn78** [comment]
How to change the tokenizer? In web UI or somewhere in the config?

**Comment by rsxdalv** [comment]
Web UI

**Comment by KPY7030P** [comment]
Hi! I found another tokenizer. how can I connect it to the Web UI interface?

**Comment by rsxdalv** [comment]
> Hi! I found another tokenizer. how can I connect it to the Web UI interface?

Sorry for the late reply, here's a screenshot to highlight it:

![image](https://github.com/user-attachments/assets/5fe6b809-1eb4-46ce-9104-4112a0685572)
