### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Code-Knight-Rise** [rsxdalv/tts-generation-webui#24]
I used the latest installation package “one-click-installers-tts-4.0” for installation, but encountered an error during the final installation.
![image](https://github.com/rsxdalv/tts-generation-webui/assets/86176946/3d8edd04-55d9-4540-b1b0-0b1589c75c07)
Is this error related to an exception during installation? How can I solve this problem?
![image](https://github.com/rsxdalv/tts-generation-webui/assets/86176946/84565c3a-a8e0-4c9f-b355-0777bbb2501e)

**Comment by rsxdalv** [comment]
Hmm, this could be the result of some change in another project, let's see how to fix it. I will attempt to do a clean install, meanwhile, could you please post the whole log if you try to run install command again? 
If you right click on the window, you can do Edit > Select All, Copy and Paste here
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/a41a7448-ce92-42a9-9c1a-c43b0c1224ab)

**Comment by rsxdalv** [comment]
For reference, here's a clean install that worked for me:
[install-log.txt](https://github.com/rsxdalv/tts-generation-webui/files/11650295/install-log.txt)

**Comment by rsxdalv** [comment]
Several installation improvements have happened, including for fairseq, to ensure that the installation is smoother. Closing the issue for now, if there are more problems, please reopen it.
