### ISSUE TITLE
Use existing .pth & .index files as a voice to enter text prompt

### ISSUE THREAD

**Issue by JasonSemaan1** [rsxdalv/tts-generation-webui#245]
Hello - I have gotten the TTS Generation WebUI running successfully. I have a number of RVC trained voice model .pth and .index files and was wondering if its possible to use these existing files as a voice to feed text prompts to?
Noticed that the default 'Alice' voice is a .npz file

**Comment by rsxdalv** [comment]
Yes and no. RVC Models can be used for RVC, Bark voices can be used for bark. You can, however, generate with bark and then convert (or make more similar) with RVC. Additionally, you can try to make a bark voice from RVC ouput audio.

Bark voices usually are .npz but in reality that just means - zipped python arrays, and npz files are used for many other things too.

**Comment by dangerweenie** [comment]
thanks for this - do you know where to save the .pth and .index files?

**Comment by rsxdalv** [comment]
Sorry for the late reply. If you mean the RVC models, you can save them 
\tts-generation-webui\data\models\rvc\checkpoints\<subfolder>

for example
\tts-generation-webui\data\models\rvc\checkpoints\my_voice\voice.pth
