### ISSUE TITLE
How can we change the React UI default port?

### ISSUE THREAD

**Issue by ozymoz** [rsxdalv/tts-generation-webui#250]
Creating .env file and port=3003 did not work. Any other ideas ?

**Comment by rsxdalv** [comment]
next start -p 8080

**Comment by rsxdalv** [comment]
You can also use PORT=8080 but it has to at the server level, not .env file, i.e., 
`PORT=8080 npm start`
or
`SET PORT=8080 && npm start`

**Comment by ozymoz** [comment]
I was able to change all ports with the following changes.

react-ui/src/pages/api/gradio/[name].tsx
```
const defaultBackend = "http://127.0.0.1:4200/";
``` 

react-ui/package.json
```
"start": "next start -p 4201",
``` 

tts-generation-webuiconfig.json
```
"server_port": 4200,
```
