### ISSUE TITLE
Bark voice clone multiple audio inputs?

### ISSUE THREAD

**Issue by MysticDaedra** [rsxdalv/tts-generation-webui#254]
It seems this isn't possible? What would be an ideal audio file length for Bark voice cloning if it can only accept a single input? I guess this might be a reason to use Tortoise instead. Usually the larger the dataset, the more accurate the reproduction.

**Comment by rsxdalv** [comment]
Bark voice clone is a lot more like stable diffusion with hit and miss.
There are some guides and explanations, but generally 6-10 seconds should
be good.

Tortoise can do a lot better voice reproduction if that's your specific
goal.

**Comment by jacooooooooool** [comment]
The turtle can reproduce the voice much better - I agree 100%, it's a pity that the language possibilities are so limited, I'm looking for a Polish model :) or a description of the possibility of training your own language model at home - a simple model

**Comment by rsxdalv** [comment]
> The turtle can reproduce the voice much better - I agree 100%, it's a pity that the language possibilities are so limited, I'm looking for a Polish model :) or a description of the possibility of training your own language model at home - a simple model

XTTS is very similar to tortoise but has polish support built in. There's a plugin that I will continue improving for running XTTS.
