### ISSUE TITLE
Keeping models in vram all the time

### ISSUE THREAD

**Issue by ozymoz** [rsxdalv/tts-generation-webui#260]
Can we keep the following 4 models in vram all the time? 4090 can do this.

RVC Voice 2 Models
MusicGen Large
AudioGen Medium

**Comment by rsxdalv** [comment]
It sounds like you'd benefit from running 2 web UIs at the same time. Are
you using Gradio or the new UI?

Basically, you might have to change the PORT setting to run the second
webui. Other than that, there are no absolute limits preventing running a
100 webui instances at the same time.
You can also open multiple tabs but that won't allow multiple models in
VRAM.
RVC + audiogen or RVC + musicgen can be loaded at the same time.

**Comment by ozymoz** [comment]
I will try and test it on different ports with React UI. Thanks.

**Comment by rsxdalv** [comment]
I'll check it out more tomorrow, I'm also interested if it's easy to do
this right now.

**Comment by rsxdalv** [comment]
Ok, with a fresh install, the second instance of webui automatically picked 7861 port for me. However, for react UI to use the correct backend it needs to have a different endpoint. Currently the end point is hardcoded, so it becomes a bit difficult to have 2 parallel react UI's.

**Comment by ozymoz** [comment]
Wouldn't the following change solve the problem?

react-ui/src/pages/api/gradio/[name].tsx
```
const defaultBackend = "http://127.0.0.1:4200/";
```

**Comment by rsxdalv** [comment]
I changed it to
```
const defaultBackend = process.env.GRADIO_BACKEND || "http://127.0.0.1:7860/";
```

This should make it easier to have 2 parallel UIs running.

**Comment by ozymoz** [comment]
What is the working difference between the two?

``` 
const defaultBackend = "http://127.0.0.1:4200/";
const defaultBackend = process.env.GRADIO_BACKEND || "http://127.0.0.1:7860/";
```

**Comment by rsxdalv** [comment]
if you supply the ENV you don't need to hardcode it, so you can do something _like_ this:

```
GRADIO_BACKEND=http://127.0.0.1:4200/ next start -p 8080
GRADIO_BACKEND=http://127.0.0.1:4201/ next start -p 8081
```

**Comment by ozymoz** [comment]
> if you supply the ENV you don't need to hardcode it, so you can do something _like_ this:
> 
> ```
> GRADIO_BACKEND=http://127.0.0.1:4200/ next start -p 8080
> GRADIO_BACKEND=http://127.0.0.1:4201/ next start -p 8081
> ```

Thank you for your support.
