### ISSUE TITLE
When trying a fresh install, I get these errors

### ISSUE THREAD

**Issue by mqsnn** [rsxdalv/tts-generation-webui#262]
Installing collected packages: sentencepiece, bitarray, antlr4-python3-runtime, tabulate, sox, psutil, portalocker, omegaconf, lxml, cython, colorama, sacrebleu, hydra-core, vector-quantize-pytorch, local-attention, lion-pytorch, ema-pytorch, accelerate, fairseq, audiolm-pytorch, bark_hubert_quantizer
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiocraft 1.3.0a0 requires av, which is not installed.
audiocraft 1.3.0a0 requires demucs, which is not installed.
audiocraft 1.3.0a0 requires flashy>=0.0.1, which is not installed.
audiocraft 1.3.0a0 requires hydra-colorlog, which is not installed.
audiocraft 1.3.0a0 requires julius, which is not installed.
audiocraft 1.3.0a0 requires num2words, which is not installed.
audiocraft 1.3.0a0 requires protobuf, which is not installed.
audiocraft 1.3.0a0 requires spacy>=3.6.1, which is not installed.
audiocraft 1.3.0a0 requires torchmetrics, which is not installed.
audiocraft 1.3.0a0 requires xformers, which is not installed.
audiocraft 1.3.0a0 requires hydra-core>=1.1, but you have hydra-core 1.0.7 which is incompatible.
audiocraft 1.3.0a0 requires torch==2.1.0, but you have torch 2.0.0 which is incompatible.

I've tried manually installing the pkgs listed but when running update_macos, it doesn't seem to register them.

**Comment by rsxdalv** [comment]
Facebook/Meta/Audiocraft developers haven't made it work on Macs. Now unlike before, this script still installs Audiocraft but without the dependencies.
From what people are saying, it seems still to be problematic or maybe even impossible to run it on Mac.

**Comment by rsxdalv** [comment]
I hoped that they would make it work, but it still has not happened, so I think I will add some Disclaimers to the UI.

**Comment by rsxdalv** [comment]
> 
> I've tried manually installing the pkgs listed but when running update_macos, it doesn't seem to register them.

This might be due to the conda environment. The way to install something manually is to do cmd_macos.sh and then `pip install` for example.

I am adding a note about the install not giving all models on all platforms.
