### ISSUE TITLE
Check if miniconda is already installed.

### ISSUE THREAD

**Issue by razvanab** [rsxdalv/tts-generation-webui#263]
I noticed that the installer is installing Miniconda. Is it possible to check if Miniconda is already installed and use the installed version instead?

**Comment by rsxdalv** [comment]
In the future I want to separate conda from the app installer, then it might be more natural to do that.

But on the other hand, considering how many things I've seen break for no reason, I'm worried that even a different version of conda could lead to broken packages, as impossible as it sounds.

I thought miniconda is a relatively small install, so I'm interested in the benefit of using the conda that is already installed? Does it use the same cache for different projects?

**Comment by razvanab** [comment]
I understand your reasoning now.
Yes, I think it is using the same cache, as far as I can tell.

**Comment by rsxdalv** [comment]
Also, I think if you activated your own conda and then run `python webui.py` it _might work_

**Comment by razvanab** [comment]
I'll try that.
Thank you.

**Comment by rsxdalv** [comment]
Did it work?

**Comment by rsxdalv** [comment]
I have updated the installer to a micromamba. However I also updated the manual installation instructions to be up to date and relevant. I think now there is more flexibility than before with the installers.

For direct reference, if you wanted to bring your own micromamba environment, you would activate your own conda, then do 
```bash
# activate env
...
# install torch, pip requirements, npm modules
node install_scripts/init_app.js
# start server
python server.py
```
