### ISSUE TITLE
Can rmvpe be added to pitch collection method in RVC?

### ISSUE THREAD

**Issue by ozymoz** [rsxdalv/tts-generation-webui#265]
rmvpe_gpu is more faithful to the voice model and faster. Do you plan to add rmvpe?

**Comment by rsxdalv** [comment]
I can see that they made a lot of updates, but the project is still not installable. I need to update my fork that lets RVC be installed as a python package. I don't know if there's any shortcut.
Here's that fork and package - 
https://github.com/rsxdalv/Retrieval-based-Voice-Conversion-WebUI/tree/package

**Comment by ozymoz** [comment]
Maybe the library below will help.

https://github.com/search?q=repo%3AIAHispano%2FApplio+rmvpe&type=code

**Comment by rsxdalv** [comment]
I reached halfway with the RVC upgrade but I haven't checked if RVC implements it.
If they don't I might have to make the PR for them.
I won't be able to do development for at least several more days.

**Comment by rsxdalv** [comment]
Added in latest update alongside FCPE
