### ISSUE TITLE
Support for seamless-expressive

### ISSUE THREAD

**Issue by curui** [rsxdalv/tts-generation-webui#282]
![QQ截图20240310024054](https://github.com/rsxdalv/tts-generation-webui/assets/83493228/076ca128-2f13-41e0-8033-74064c7cdb88)
Translate other languages via audio files like this！

**Comment by rsxdalv** [comment]
Hi, please try the newest update, I added a basic implementation for testing. Not all of the languages in the list are supported, and I don't have the S2TT, T2TT and ASR yet, I just added the S2ST functionality.

https://github.com/rsxdalv/tts-generation-webui/pull/284

**Comment by ld202167** [comment]
> 您好，请尝试最新的更新，我添加了一个基本的测试实现。并非列表中的所有语言都受支持，而且我还没有 S2TT、T2TT 和 ASR，我只是添加了 S2ST 功能。
> 
> [第284章](https://github.com/rsxdalv/tts-generation-webui/pull/284) ![127 0 0 1_7860_ (1)](https://private-user-images.githubusercontent.com/6757283/311529795-ce985bcc-f3c4-4794-b0c8-8acef3102d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDk4MzUsIm5iZiI6MTcxMDQ0OTUzNSwicGF0aCI6Ii82NzU3MjgzLzMxMTUyOTc5NS1jZTk4NWJjYy1mM2M0LTQ3OTQtYjBjOC04YWNlZjMxMDJkMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMjA1MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQzZTQzMmUwNzUxYzJhOTRmNWJlNzZhNTgwYjlmYzJiODFhM2RmMmI3ZTY0ZTE5YmVkZjQ3YWU4ZDlmMDE0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X0bCQKjcjgDorHTZ1IC31Uc31bo5jqxUD1DzD8XU5Gs)

thank u!You can refer to this https://replicate.com/adirik/seamless-expressive. They can recognize speech and translate the same timbre, just like heygen. They seem to use seamless.   For example: Upload the audio of an American who can translate and speak Chinese with the same accent/tone

**Comment by rsxdalv** [comment]
Interesting, the results on replicate seem better than what I saw myself so far. Thank you! This gives more research to do.
