### ISSUE TITLE
Port Connection Issues After Update

### ISSUE THREAD

**Issue by VegaStarlake** [rsxdalv/tts-generation-webui#285]
Since updating, I get a WinError 10061. I haven't changed any Windows configurations that would block or use the default port. After giving several errors, the webui starts on port 3000, but then generation fails because the program tries to use the default port and nothing is connected. Setting new inbound rules on firewall did not help.

**Comment by rsxdalv** [comment]
Hi, let me first release the update. I fixed an error in building the React UI, that should not but might be the reason by some chance. That should reduce the number of errors you are seeing.

**Comment by rsxdalv** [comment]
Also, please give me the logs if you can, I am not sure I will be able to guess which part is failing without more information.

**Comment by rsxdalv** [comment]
Closing this issue as more information is needed. I know that sometimes there are windows connection errors without a cause; however here it sounds like the gradio server is failing or React is unable to connect to it.
