### ISSUE TITLE
(Adding seamless-expressive) Regarding the problem of SeamlessM4T translating and cloning timbre/spoken language, here are cases

### ISSUE THREAD

**Issue by curui** [rsxdalv/tts-generation-webui#289]
Regarding using only one audio sample, you can speak multiple languages using the tone of the audio sample. In fact, what you use is: seamless
You can refer to this: https://replicate.com/adirik/seamless-expressive
He seems to have also quoted seamless: https://github.com/replicate/cog-seamlessexpressive
demo:https://www.youtube.com/watch?v=lgL_rCF02Ng
   You can refer to the recently popular ones: https://github.com/RVC-Boss/GPT-SoVITS

**Comment by ld202167** [comment]
I don’t know if your project can translate text and clone multi-language sounds based on samples at the same time, but SeamlessM4T seems to be possible. At the same time, I saw this case, but Seamless did not do this in huggingface space. It’s just Translating audio does not clone audio !original [english:

**Comment by rsxdalv** [comment]
Is GPT-SoVITS a new replacement for RVC?

**Comment by ld202167** [comment]
> https://replicate.com/adirik/seamless-expressive

You can upload an audio test, as if translated directly and clone the sound at the same time   https://replicate.com/adirik/seamless-expressive

**Comment by ld202167** [comment]
He uses seamless   ：https://huggingface.co/facebook/seamless-expressive   
<img width="695" alt="屏幕截图 2024-03-15 060657" src="https://github.com/rsxdalv/tts-generation-webui/assets/83493228/1ee23c48-27c2-4b32-a76d-451d86532ad4">  I don't know why you do this

**Comment by ld202167** [comment]
> Is GPT-SoVITS a new replacement for RVC?
GPT-SoVITS   can also Too complicated to use 。
You only need to upload a piece of audio, and you can use SeamlessExpressive. However, the SeamlessExpressive model needs to be reviewed before it can be obtained. I don’t know what the difference is between it and SeamlessM4T.

**Comment by rsxdalv** [comment]
> He uses seamless ：https://huggingface.co/facebook/seamless-expressive <img alt="屏幕截图 2024-03-15 060657" width="695" src="https://private-user-images.githubusercontent.com/83493228/313008434-1ee23c48-27c2-4b32-a76d-451d86532ad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTg2MTMsIm5iZiI6MTcxMDQ5ODMxMywicGF0aCI6Ii84MzQ5MzIyOC8zMTMwMDg0MzQtMWVlMjNjNDgtMjdjMi00YjMyLWE3NmQtNDUxZDg2NTMyYWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEwMjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNDg4ZDU1YTIyOWU2NTliOGE4MDY0Y2EwZTBkY2E1ZTRmZTk4MjA4ZTQxYWFjYjg5MjJiYTRjYTRkODAxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6BU8TZNPQw4iltBE1jrznVajSIB2ATBMoJm43-vI_cE"> I don't know why you do this

Ah now I remember this seamless-expressive, I got it confused with seamlessM4T. To be honest, I doubt that many people will be willing to fill out the form. 
GPOT-SoVITS and SeamlessM4T can be done though.

**Comment by rsxdalv** [comment]
So here's the post-mortem - since seamless-expressive has a restrictive, unique license (many people don't use a project with a custom license), and the development has been very slow (again, happens a lot with non-open-source style licenses), I will probably not include seamless-expressive, neither as a plugin, also because:
```
2. Restrictions. You will not, and will not permit, assist or cause any third party to:
        a. use the Seamless Materials or any outputs or results of the Seamless Materials in connection with any commercial uses or for any uses other than Noncommercial Research Uses;
```
This is _ridiculous_, by that standard I could break their license just by writing an article on how to install seamless-expressive.
