### ISSUE TITLE
Dead "NEW React UI" link

### ISSUE THREAD

**Issue by darkvertex** [rsxdalv/tts-generation-webui#290]
The line:
https://github.com/rsxdalv/tts-generation-webui/blob/c1013de6a03cdf0898c577ce0b579be5ad18bf40/server.py#L62
...adds a "NEW React UI" markdown link in the header that goes to localhost:3000 but there seems to be nothing set up to actually run anything on this port.

Is the docker-compose.yml missing something?

**Comment by rsxdalv** [comment]
The server.py should launch the Node.js process on 3000. I think it's the
port that's not exposed. Maybe there's something more missing.

**Comment by darkvertex** [comment]
Hmm, when launching the Docker image (`ghcr.io/rsxdalv/tts-generation-webui:main`) at the time of writing, I see:
`/bin/sh: 1: npm: not found`

I guess that's it; npm is missing.

Also missing is a line to expose port 3000 in the docker-compose.yml:
https://github.com/rsxdalv/tts-generation-webui/blob/c1013de6a03cdf0898c577ce0b579be5ad18bf40/docker-compose.yml#L6

**Comment by rsxdalv** [comment]
I pushed the update. Please test the new image and let me know how it goes. https://github.com/rsxdalv/tts-generation-webui/actions/runs/8393137834/job/22987441352

**Comment by rsxdalv** [comment]
That's amazing, thank you, I have included it in the latest commit. Thankfully gradio's markdown accepts HTML.
