### ISSUE TITLE
RVC not working anymore after upgrade

### ISSUE THREAD

**Issue by ashleykleynhans** [rsxdalv/tts-generation-webui#299]
There seems to be something wrong with the requirements for RVC after the recent RVC upgrade.

This is the error:

<img width="928" alt="Monosnap TTS Generation WebUI 2024-04-05 08-35-17" src="https://github.com/rsxdalv/tts-generation-webui/assets/886709/3b1932e8-2ba3-4926-8fbe-9a7eaf20ce88">

Even though the requirements are already installed.

**Comment by ashleykleynhans** [comment]
Seems to be a result of the most recent changes

<img width="862" alt="Screenshot 2024-04-05 at 11 17 15" src="https://github.com/rsxdalv/tts-generation-webui/assets/886709/65518c75-9b5d-41c1-9a35-03cbfec03f48">

Works fine when these removed packages are installed.

**Comment by rsxdalv** [comment]
Thanks, I planned to do a hotfix release, but didn't manage to release it
in time.

**Comment by rsxdalv** [comment]
https://github.com/rsxdalv/tts-generation-webui/pull/300 this should fix it for everyone. I will close the issue since in my tests it works now, but feel free to reopen if it comes up.

**Comment by ashleykleynhans** [comment]
Thanks, its working again 🙏
