### ISSUE TITLE
I wanted to run this on a docker and cpu, is that possible?

### ISSUE THREAD

**Issue by debjit** [rsxdalv/tts-generation-webui#308]
I do not mind the long waiting time; I wanted to run into my R5 2600 and 16 GB of RAM on Ubuntu 22 using Docker. Is that possible?

**Comment by rsxdalv** [comment]
There is a docker image, it should be runnable on CPU as well. Although some of the models have abysmal generation times for CPU.

**Comment by debjit** [comment]
Thank you for your quick reply; there is not much docker in the tutorials. I prefer docker over  install because I test a lot of packages, and docker helps me separate everything.

**Comment by rsxdalv** [comment]
https://github.com/rsxdalv/tts-generation-webui?tab=readme-ov-file#docker-setup

tts-generation-webui can also be ran inside of a Docker container. To get started, first build the Docker image while in the root directory:

docker build -t rsxdalv/tts-generation-webui .
Once the image has built it can be started with Docker Compose:

docker compose up -d
The container will take some time to generate the first output while models are downloaded in the background. The status of this download can be verified by checking the container logs:

docker logs tts-generation-webui

**Comment by debjit** [comment]
Thank you.
The readme is huge. and I think changelog should be at the end of it. I searched the Docker keyword, and it gave me changelogs pulling an image section, so I tried that.

**Comment by rsxdalv** [comment]
I agree, it's time to restructure the readme file.
