### ISSUE TITLE
voice Cloning RU

### ISSUE THREAD

**Issue by KPY7030P** [rsxdalv/tts-generation-webui#317]
Hi! there are models based on HuBert, but for the Russian language, I'm not sure that this is what is needed, but if so, then it would be good to add them.
https://cloud.ru/ru/datahub/rugpt3family/rubert-base
https://habr.com/ru/companies/sberbank/articles/567776/

**Comment by rsxdalv** [comment]
It seems to have a different format, there also needs to be a model that translates the tokens for use by Bark, perhaps gitmylo who made the HuBert based voice cloning used in this project can weigh in on it: https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer/issues
