### ISSUE TITLE
Add Stable Audio, please!

### ISSUE THREAD

**Issue by mykeehu** [rsxdalv/tts-generation-webui#319]
Please add Stable Audio to the options, if you please! Thank you very much in advance!

https://github.com/Stability-AI/stable-audio-tools

And model here: 
https://huggingface.co/stabilityai/stable-audio-open-1.0

**Comment by rsxdalv** [comment]
Hi, thanks for requesting this! I have been procrastinating with it actually. One question - such a model would require a huggingface account and a login to be used, since this https://huggingface.co/stabilityai/stable-audio-open-1.0 cannot be automatically downloaded. Would you be ok with that?

**Comment by mykeehu** [comment]
I don't have a problem downloading the model this way, maybe you could ask for the login to download it? So those who have it can use it, those who don't can't. I don't know why it's tied to a license, but I've seen a video of it making quite good sound effects, so after the login the model would be downloaded.

**Comment by chlowden** [comment]
I'd be interested in trying this out too, please.

**Comment by ke1ne** [comment]
> Hi, thanks for requesting this! I have been procrastinating with it actually. One question - such a model would require a huggingface account and a login to be used, since this https://huggingface.co/stabilityai/stable-audio-open-1.0 cannot be automatically downloaded. Would you be ok with that?
> 
> Please respond as this is a matter that could really determine whether or not people use it.

For instance, I'm ok with it. Thanks!

**Comment by chlowden** [comment]
I've already downloaded the checkpoint. I presume that those who are enjoying your interface are the sort of people who already have a huggingface account.

**Comment by rsxdalv** [comment]
Stable audio has been added but is causing some problems so it might be added-removed a few times until it's 'stable'.

**Comment by rsxdalv** [comment]
Also, I just want to clarify - with extensive research - stable audio is not a 'stable diffusion 1.5' moment because it has a restrictive, potentially dangerous license (which might be legally unenforceable or impossible to defend in court; it's the very same infamous SD3 license) and I saw comments about Facebook's (notably similarly non-commercially licensed) AudioGen/MusicGen performing similarly.

My biggest issue so far is that running the 'official' inference code results in ~14gb RAM usage, where due to memory management my 24 gb RAM & 24 gb VRAM system would often just fail.

That being said, I really appreciate receiving information about what people want to try and see.

**Comment by chlowden** [comment]
I concur on the VRAM issue. I often saturate my RTX 3090 with 24GB of RAM using MusicGen. I have not been able to test MultiBandDiffusion due to VRAM saturation. I have seen that python will not release the VRAM it takes up so it blocks the GPU. I have to restart the machine to liberate the VRAM.
If Stable Audio is even worse than MusicGen, it does make it probematic to test for me.

**Comment by rsxdalv** [comment]
Restarting the webui should be enough. Additionally, after I fix the bugs arising from adding this new model, I can spend more time on 'unload model' buttons throughout the UI; however, there will always be some leftovers that aren't unloaded.
As for Stable Audio - generating a 47 second or a 1 second clip seems to use the same amount of VRAM unless they somehow can fix it all will do it themselves. Honestly there's multiple improvements on the model itself that are waiting to be done by _somebody_, perhaps they are hoping the community will do it.

**Comment by chlowden** [comment]
And as we are talking of other models  ... maybe people are interested in ... Toucan TTS with 7000 languages
https://github.com/DigitalPhonetics/IMS-Toucan

**Comment by rsxdalv** [comment]
> And as we are talking of other models ... maybe people are interested in ... Toucan TTS with 7000 languages https://github.com/DigitalPhonetics/IMS-Toucan

For this project it seems decent but could be hard to handle if it means everyone has to install espeak.

**Comment by rsxdalv** [comment]
Ok nevermind stable audio is amazing sometimes. If you have the GPU for it, it generates quickly (anything below the 'default size', which I think is 47 seconds is not going to generate faster, but if you want a full sample it's so quick) and it often generates without needing a lot more steering that you would expect with musicgen. That being said, the license is still the way it is.

**Comment by mykeehu** [comment]
Thank you for fantastic work and this addon! I will use it!

**Comment by rsxdalv** [comment]
Thanks for reporting, fixed it, just update normally or do a git pull for a very quick update.

**Comment by chlowden** [comment]
It is fixed for me. Thank you very much. Now the fun begins.

**Comment by chlowden** [comment]
Well sort of ...
I have downloaded the checkpoint to the *data/models/stable-audio/* folder
but I'm getting the errors below when I try to load it in the webUI.

  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/queueing.py",
line 407, in call_prediction
    output = await route_utils.call_process_api(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/route_utils.py",
line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/blocks.py",
line 1550, in process_api
    result = await self.call_function(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/blocks.py",
line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/anyio/to_thread.py",
line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 2144, in run_sync_in_worker_thread
    return await future
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 851, in run
    result = context.run(func, *args)
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/utils.py",
line 661, in wrapper
    response = f(*args, **kwargs)
  File
"/mnt/5231ec3e-8240-4386-b11a-c8f7218327ab/tts-generation-webui-main/src/stable_audio/stable_audio.py",
line 115, in load_model_helper
    model_config=load_model_config(model_name),
  File
"/mnt/5231ec3e-8240-4386-b11a-c8f7218327ab/tts-generation-webui-main/src/stable_audio/stable_audio.py",
line 111, in load_model_config
    with open(path) as f:
*NotADirectoryError: [Errno 20] Not a directory:
'data/models/stable-audio/SD_AUDIO_V1_model.safetensors/model_config.json'*
Traceback (most recent call last):
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/queueing.py",
line 407, in call_prediction
    output = await route_utils.call_process_api(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/route_utils.py",
line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/blocks.py",
line 1550, in process_api
    result = await self.call_function(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/blocks.py",
line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/anyio/to_thread.py",
line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 2144, in run_sync_in_worker_thread
    return await future
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 851, in run
    result = context.run(func, *args)
  File
"/home/admin/anaconda3/envs/python310/lib/python3.10/site-packages/gradio/utils.py",
line 661, in wrapper
    response = f(*args, **kwargs)
  File
"/mnt/5231ec3e-8240-4386-b11a-c8f7218327ab/tts-generation-webui-main/src/stable_audio/stable_audio.py",
line 115, in load_model_helper
    model_config=load_model_config(model_name),
  File
"/mnt/5231ec3e-8240-4386-b11a-c8f7218327ab/tts-generation-webui-main/src/stable_audio/stable_audio.py",
line 111, in load_model_config
    with open(path) as f:
*NotADirectoryError: [Errno 20] Not a directory:
'data/models/stable-audio/model.ckpt/model_config.json'*

*Any ideas are most welcome  ..*
[image: image.png]

**Comment by rsxdalv** [comment]
Ok I think I figured it out:
There needs to be another folder, since you can have 100s of different Stable Audio models, so in your example moving the files to a new folder like this should work:

`data/models/stable-audio/my-first-stable-audio-model/model.ckpt`

**Comment by chlowden** [comment]
Got it working thanks to you.
I created a specific subfolder and put the model.ckpt in it ... but that did not work. The subfolder should also have the model_config.json file from the same huggingface page as the ckpt and then it all worked great. The webui shows the sub folder name, not the ckpt.
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6749130/d1b9026c-6aa0-4cff-babb-e64e2e2c0d74)

Another issue is that the output file is always overwritten in the tts-generation-webui folder. It would be great if it could show up in the outputs folder like the TTS and Musicgen do.

A passing note, the init audio button is not working for me.

Many thanks

**Comment by chlowden** [comment]
Concerning GPU memory, it has a very low memory footprint in comparison so Musicgen. My RTX 3090 has no problem with SD audio for the moment.

**Comment by rsxdalv** [comment]
So about the outputs - I want to avoid spending a huge amount of time on integrating with the old favorites system and move on to a new system.
When you want them saved, what is the main wish - full integration with the favorites and history and collections, or do you just want to have a _folder_ with all of the files and reasonable filenames/metadata?

**Comment by rsxdalv** [comment]
Now files are being saved to outputs-rvc/stableaudio/...

**Comment by rsxdalv** [comment]
Commercial use is now OK for *most* people, this makes Stable Audio one if not the best open source model we have! (Many other famous models are not open source, non-commercial etc) https://stability.ai/news/license-update

**Comment by chlowden** [comment]
Thank you for sharing this update. This is excellent news from SD. I was starting to worry that the SD project would fold to the GAFA pressure.

**Comment by chlowden** [comment]
> Now files are being saved to outputs-rvc/stableaudio/...

Hello
I have been doing tests. I now get individually named folders in outputs-rvc but they are empty. But the audio file still appears at the folder root and is overwritten each time. 
I replaced the stableaudio file in src with the new one but maybe there is something else to swap too?
Many thanks

**Comment by rsxdalv** [comment]
The audio file appearing at root - it's from the official package, strange
decision, they should stop doing that.

With the folders being empty - that is a bug. It doesn't happen for me on
windows so maybe it's scipy/wavfile problem and hopefully it can be seen as
an error in the logs. Do other tabs save properly, like bark or tortoise?

**Comment by chlowden** [comment]
Here is the error
`FileNotFoundError: [Errno 2] No such file or directory: 'outputs-rvc/Stable Audio/2024-07-10_16-30-30_((piano_solo))__acoustic__key_E_minor__minimalist_high_energy_4/4__120bpm__320kbps__48.0kHz_Stereo__Studio__sorrow__minimalism_genre__Classical__Avant-Garde__dynamic_rhythm_/2024-07-10_16-30-30_((piano_solo))__acoustic__key_E_minor__minimalist_high_energy_4/4__120bpm__320kbps__48.0kHz_Stereo__Studio__sorrow__minimalism_genre__Classical__Avant-Garde__dynamic_rhythm_.wav'
`
The system creates a  folder and sub-folder that use the prompt and it seems that for the export, the system does not find the path with folder names that are not same ...
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6749130/2ad3e52c-a7c4-418e-b84a-31fa64f625df)

**Comment by chlowden** [comment]
No problem with TTS or bark

**Comment by chlowden** [comment]
I'm using Rocky Linux 8.10

**Comment by chlowden** [comment]
Incidentally, with the latest stable diffusion file, all my outputs are now 48secs long, even if the total seconds are above or below 48secs?

**Comment by rsxdalv** [comment]
@chlowden 

> Here is the error
FileNotFoundError: [Errno 2] No such file or directory: 'outputs-rvc/Stable Audio/2024-07-10_16-30-30_((piano_solo))__acoustic__key_E_minor__minimalist_high_energy_4/4__120bpm__320kbps__48.0kHz_Stereo__Studio__sorrow__minimalism_genre__Classical__Avant-Garde__dynamic_rhythm_/2024-07-10_16-30-30_((piano_solo))__acoustic__key_E_minor__minimalist_high_energy_4/4__120bpm__320kbps__48.0kHz_Stereo__Studio__sorrow__minimalism_genre__Classical__Avant-Garde__dynamic_rhythm_.wav' 
The system creates a folder and sub-folder that use the prompt and it seems that for the export, the system does not find the path with folder names that are not same ...

So I think it could be the parenthesis and file system names, I will add a fix for removing the parenthesis, but could you try just a simple 'water' and see if that generation gets saved?

> No problem with TTS or bark

Ok, that helps a lot to know.

> Incidentally, with the latest stable diffusion file, all my outputs are now 48secs long, even if the total seconds are above or below 48secs.

Yes, I always saw that behaviour, have you ever seen it generate a different length? To me, if I put say 10s the audio will be silent but still output 48 seconds. I tried online demos and saw the same; so I was waiting for stable diffusion to fix this.


> ` seconds_total_slider = gr.Slider( minimum=0, maximum=512, step=1, value=sample_size // sample_rate, label="Seconds total", visible=has_seconds_total,` Maybe the value=sample_size // sample_rate, explains why everything is 48secs long

I will check this part. value here means the default value, but it could be related.

**Comment by rsxdalv** [comment]
I checked the source of Stable Audio and it does seem like sample_size as defined within their code could determine the output length, but the gradio API they have made does not allow changing the length. They have a more internal API but it still seems like their model generates the audio equivalent of 512 by 512.

**Comment by chlowden** [comment]
I've done so many tests that I am probably getting confused as to what I can do with what service.

**Comment by rsxdalv** [comment]
Got it, I see we are doing a lot of back and forth so it might be useful to go on the new discord server. I will be busy for a while but hopefully can do more from there.

https://discord.com/invite/3JbBrKrH

**Comment by chlowden** [comment]
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6749130/135a9836-cb02-4801-b7fc-10544de9c96c)
river works as you expect ..

**Comment by mykeehu** [comment]
> ` seconds_total_slider = gr.Slider( minimum=0, maximum=512, step=1, value=sample_size // sample_rate, label="Seconds total", visible=has_seconds_total,` Maybe the value=sample_size // sample_rate, explains why everything is 48secs long

The 48 seconds is interesting because the official limit is 47 seconds. I'm sorry that you can't set an custom length, but the website says it's fixed:
https://stability.ai/news/introducing-stable-audio-open

**Comment by rsxdalv** [comment]
> The filenames and folder names are really long, with a prompt you can easily reach the Windows 255 character path limit. I'd rather say the date-seed format could be more manageable, since the file you're describing is next to it anyway.

Fixed the filenames:

>>> def get_name(prompt):
...     return (
...         prompt.replace(" ", "_")
...         .replace(":", "_")
...         .replace("'", "_")
...         .replace('"', "_")
...         .replace("\\", "_")
...         .replace(",", "_")
...         .replace("(", "_")
...         .replace(")", "_")
...         .replace("?", "_")
...         .replace("!", "_")
...         .replace("&", "_")
...         # only first 15 characters
...         .replace("__", "_")[:15]
...     )
...
>>> # test get_name
>>>
>>> get_name("bamboo flute, zed, reiki, meditation music")
'bamboo_flute_ze'
>>> get_name("funk, disco, R&B, AOR, soft rock, and boogie")
'funk_disco_R_B_'
>>> get_name("Electro House, 320kbps")
'Electro_House_3'
>>> get_name("minimalism, piano, acoustic key E minor, 120bpm and 108bpm piano, Classical, Avant-Garde, dynamic rhythm")
'minimalism_pian'

**Comment by mykeehu** [comment]
> Fixed the filenames:
Great! Now you can better manage your folders and files, thank you!

**Comment by mykeehu** [comment]
Even the file names need a little fix. Stable Audio Generator produced such a prompt, and it is not saved because of the characters it contains:

```
Genre: Pop
Mood: Romantic, Atmospheric
Style: 90s
Instruments: Lead, Lead-off
Beats per Minute (BPM): 100
Additional Details: Create a dreamy and nostalgic atmosphere with lush synth pads, gentle piano melodies, a prominent lead melody, and a textural lead-off supporting the track. The music should build up to a cathartic moment filled with emotion and passion, capturing the essence of romanticism in the style of 90s pop.
```

**Comment by rsxdalv** [comment]
> Even the file names need a little fix. Stable Audio Generator produced such a prompt, and it is not saved because of the characters it contains:
> 
> ```
> Genre: Pop
> Mood: Romantic, Atmospheric
> Style: 90s
> Instruments: Lead, Lead-off
> Beats per Minute (BPM): 100
> Additional Details: Create a dreamy and nostalgic atmosphere with lush synth pads, gentle piano melodies, a prominent lead melody, and a textural lead-off supporting the track. The music should build up to a cathartic moment filled with emotion and passion, capturing the essence of romanticism in the style of 90s pop.
> ```
> 
> The problem is with the \n:
> 
> ```
> Traceback (most recent call last):
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
>     output = await route_utils.call_process_api(
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
>     result = await self.call_function(
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "I:\tts-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
>     response = f(*args, **kwargs)
>   File "I:\tts-generation-webui\tts-generation-webui\src\stable_audio\stable_audio.py", line 282, in save_result
>     os.makedirs(base_dir, exist_ok=True)
>   File "I:\tts-generation-webui\installer_files\env\lib\os.py", line 225, in makedirs
>     mkdir(name, mode)
> OSError: [WinError 123] File name, directory name or volume label syntax is incorrect: 'outputs-rvc\\Stable Audio\\2024-07-11_21-34-59_Format_Band_\nGe'
> ```

Should be fixed in the latest update https://github.com/rsxdalv/tts-generation-webui/pull/342

**Comment by mykeehu** [comment]
Great work! I tested it, the save works perfectly! Thank you!
