### ISSUE TITLE
Top-p and Temperature Value Correction

### ISSUE THREAD

**Issue by nehemiahgo** [rsxdalv/tts-generation-webui#32]
Hey there, great project! For the newly added MusicGen section, can you add support for smaller gradations when it comes to Top-p and Temperature? Right now it can only go up by whole digits rather than tenths. I receive "Please enter a valid value" if I try to input something like 0.9 for Temperature.

**Comment by rsxdalv** [comment]
Thank you!

https://github.com/rsxdalv/tts-generation-webui/commit/50b91baee97f34802ff7c3242e764983cb933234

I changed them to sliders with a 0.05 step and it seems to work.
However, for _top_p_ a value other than 0 will create an error in their code. I will see how I can update the package, maybe I have to use bleeding edge.

I will post in this thread once I have a solution. Alternatively install a newer version directly, perhaps this command will just work?

`pip install -U git+https://git@github.com/facebookresearch/audiocraft#egg=audiocraft  # bleeding edge`

**Comment by rsxdalv** [comment]
I changed audiocraft to be installed from git instead of pypi so this issue has been resolved for about a month.
