### ISSUE TITLE
Tortoise TTS V3 - installable ?

### ISSUE THREAD

**Issue by chlowden** [rsxdalv/tts-generation-webui#320]
Hello
Is there a way to install the ai-voice-cloning-3.0.7z
[](https://huggingface.co/Jmica/ai-voice-cloning/blob/main/ai-voice-cloning-3.0.7z)
Without breaking all your marvelous work?
Thank you

**Comment by rsxdalv** [comment]
I think it might be possible to install. But integrating it would force me
to change the license of my entire project, so I will refrain from that.
However, if you want to have some additional features in this UI, I could
work on those in particular.

Also, in general all tortoise models are cross compatible. So if you make a
model with some fork or other UI etc, you can bring that checkpoint file to
this project.

**Comment by rsxdalv** [comment]
One more detail - installing the ai voice cloning separately should not break anything. Installing ai voice cloning **inside** of TTS generation webui might break something, but the next update/install would fix it.

If there are more questions, please reopen.
