### ISSUE TITLE
output-rvc folder error

### ISSUE THREAD

**Issue by chlowden** [rsxdalv/tts-generation-webui#321]
Hello
A tiny bug concerning the UVR5 demo version tab page. The open outputs folder button opens  outputs-rvc folder but the renders are made into a folder called output-rvc and it deletes the previous folder.
Thanks for all the work

**Comment by rsxdalv** [comment]
Thank you for reporting this, and also for letting me know that UVR5 is being used!
I have made it use the same outputs-rvc folder.
I did not see it deleting the folder when generating, so I might still have more to fix.
https://github.com/rsxdalv/tts-generation-webui/pull/322

If you have more info about the folder being deleted please let me know.

**Comment by chlowden** [comment]
Quite simply, the folder only holds the last renders , therefore I presume that the script erases the previous folder of the same name.

**Comment by rsxdalv** [comment]
Strange, I tried with the new folder name and I'm not seeing this bug, I can start it, do uvr, close it, restart it etc, it doesn't seem to erase the previous data. I'm hopeful it works fine.

**Comment by RustoMCSpit** [comment]
@rsxdalv UVR5 is in this? https://github.com/Anjok07/ultimatevocalremovergui where is it in the models in the readme?

**Comment by rsxdalv** [comment]
This tts-generation-webui project contains UVR as a plugin that can be installed and then run with a Jupyter notebook. I have not added an UI for the plugin yet.
