### ISSUE TITLE
Some gradio tabs are broken after adding Stable Audio

### ISSUE THREAD

**Issue by ashleykleynhans** [rsxdalv/tts-generation-webui#327]
The following gradio tabs are broken after adding Stable Audio:
* Bark Voice Clone (bark_hubert_quantizer is missing)
* RVC Beta Demo (rvc_pkg is missing)
* UVR5 (rvc_pkg is missing)

<img width="1329" alt="Screenshot 2024-06-24 at 15 10 54" src="https://github.com/rsxdalv/tts-generation-webui/assets/886709/5caa54b7-43ff-4bd9-afd6-a3c15048424b">

When I try to reinstall `requirements_rvc.txt`, I get an error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'
```

And when I try to reinstall `requirements_bark_hubert_quantizer.txt`, I get an error:
```
ERROR: Cannot install -r requirements_bark_hubert_quantizer.txt (line 4) and fairseq because these package versions have conflicting dependencies.
```

Seems some conflicting requirements or something.

**Comment by rsxdalv** [comment]
Thank you for reporting, it was really important. I didn't have this happening so lots of work to be done. 

`FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'`

from this I am guessing that we are talking about a non-windows installation, is that correct?

before this update I also modified the fairseq requirements, so now it tries to install this:

`requirements_bark_hubert_quantizer.txt`
```
torch==2.0.0 # BSD 3-Clause - ensures torch is not reinstalled
# pre-install fairseq for bark_hubert_quantizer
fairseq @ https://github.com/Sharrnah/fairseq/releases/download/v0.12.4/fairseq-0.12.4-cp310-cp310-win_amd64.whl ; sys_platform == 'win32' # MIT License
fairseq==0.12.2 ; sys_platform == 'linux' or sys_platform == 'darwin' # MIT License
bark_hubert_quantizer @ git+https://github.com/rsxdalv/bark-voice-cloning-HuBERT-quantizer@bark_hubert_quantizer#egg=bark_hubert_quantizer # MIT License
```

I really wish the error was clearer. It says line 4, that would be the 
`fairseq==0.12.2 ; sys_platform == 'linux' or sys_platform == 'darwin' # MIT License`
line.

So please confirm which OS are you using and then we can see how to fix this. Also, if this is WSL or something similar also let me know.

**Comment by ashleykleynhans** [comment]
| from this I am guessing that we are talking about a non-windows installation, is that correct?

Yes, this is correct, I am using Ubuntu Linux 22.04 LTS.

**Comment by rsxdalv** [comment]
Alright, that is a helpful clue. Also, for reference, the Dockerfile builds successfully on ubuntu-latest runner.

https://github.com/rsxdalv/tts-generation-webui/actions/runs/9626988362/job/26553579383

**Comment by ashleykleynhans** [comment]
I'm also building a Docker image for Ubuntu 22.04 LTS.
There are no issues with building the Docker image, I only experience issues at runtime.

**Comment by rsxdalv** [comment]
I see, that clarifies it quite a bit - the problems don't show up during the build but are still there.

**Comment by ashleykleynhans** [comment]
This was my fault, I was using version 24.1 of pip which you mentioned breaks fairseq in the Dockerfile.

**Comment by rsxdalv** [comment]
I had a feeling it could be the case, but I wanted to confirm it myself.
Then I got stuck fighting with Google cloud.

**Comment by ashleykleynhans** [comment]
Looks like `protobuf` is still an issue though.  I was getting an error:

```
Error: cannot import name 'builder' from ‘google.protobuf.internal
```

So I upgraded to latest protobuf version 5.27.2 but then even more things broke, so I had to install `protobuf==4.25.3` then all tabs started displaying correctly without any errors.

**Comment by rsxdalv** [comment]
Great job! Can I ask why the magic number 4.25.3? I would like to include this in the installer, I have seen some protobuf errors on AI projects and let's just say they scare me, considering how core this library is.

**Comment by ashleykleynhans** [comment]
I got to the magic number of 4.25.3 by trial and error, I even installed a 3.xx.x version at a point, and the 4.25.3 version was the first version I attempted that didn't produce any errors when starting the gradio application, and all tabs displayed successfully.

**Comment by rsxdalv** [comment]
Thank you, seems to affect newer installs altogether, so I added it to the new installer!
