### ISSUE TITLE
Windows has protected the computer

### ISSUE THREAD

**Issue by doggi87** [rsxdalv/tts-generation-webui#336]
The new installer doesn't start normally as before.

Now I get "Windows has protected the computer
Microsoft Defender SmartScreen is protected by the launch of an unknown app. Running the app may pose a risk to the computer."

**Comment by rsxdalv** [comment]
Thanks for letting me know about it! To be honest I kind of expected this
kind of behavior because to Windows, it just seems like a random file,
hopefully they eventually uncensor it soon enough.
The old updater should still work.

**Comment by doggi87** [comment]
oh okay thanks, you can still start the file via more information in that window and then choose run anyway.

**Comment by rsxdalv** [comment]
Cheers, that will probably get it whitelisted

**Comment by rsxdalv** [comment]
Users have no longer reported this, so I guess that it got whitelisted.
