### ISSUE TITLE
Lock actual seed?

### ISSUE THREAD

**Issue by mykeehu** [rsxdalv/tts-generation-webui#337]
I have generated a track in Stable Audio, but I just want to set a few parameters. How can I lock the currently generated seed? I can't find a button.

**Comment by rsxdalv** [comment]
It is currently only in the console and needs to be copied out.

Stable audio currently still seems to be doing development so I am not adding a lot of customizations just yet, this could require modifying the internal code not just the UI.

**Comment by rsxdalv** [comment]
https://github.com/rsxdalv/tts-generation-webui/pull/342

Now the seed will update when pressing generate. I hope this is even more convenient than the button to restore last seed.
If you want to use a seed, just uncheck the 'randomize seed' option.

Once you confirm that this works for you, we can close the issue.

**Comment by mykeehu** [comment]
You did it perfectly! I just generated it twice with the same seed, then put it into Audacity, and the waves are the same, so it's an excellent solution, thank you very much!
