### ISSUE TITLE
Seamless Demo - local model install ?

### ISSUE THREAD

**Issue by chlowden** [rsxdalv/tts-generation-webui#338]
Hello
I am testing seamless but I am hitting a 5sec output limit. I cannot find the seamless model locally installed so I presume it is calling back to huggingface. Would installing the checkpoints locally unlimit the demo?
Thank you

**Comment by rsxdalv** [comment]
Freshly downloaded I can get 9 second outputs, although it does seem to
have some sort of a limit beyond that.

The models are saved in hugging face cache in your user/.cache folder this
in theory is good but practically it seems that people would prefer getting
everything in the apps model directory.
The idea is that if the models get updated (which nneeeever happens in the
AI audio space) you would get a faster and better install, also if you had
4-5 projects running with the same model. But most of us are not AI
researchers that will even have more than 1-2 AI apps with similar models.
So with the new models I usually build the system for saving them locally.
It's a bit more complicated but empowers the end users more.

**Comment by rsxdalv** [comment]
I think this issue should be resolved. As for the future - I will make all of the models locally 'visible' since I believe most of the users want that, rather than a very optimal but hard to manage cache.
If I'm mistaken, feel free to reopen the issue.
