### ISSUE TITLE
Bark Voice Clone TypeError

### ISSUE THREAD

**Issue by JeffoDogge** [rsxdalv/tts-generation-webui#343]
Hey. Downloaded/Started using today. Tried using Bark voice clone and I get this.

> File "E:\Programs\tts-generation-webui-main\installer_files\env\lib\site-packages\fairseq\dataclass\utils.py", line 399, in convert_namespace_to_omegaconf
>     composed_cfg = compose("config", overrides=overrides, strict=False)
> TypeError: compose() got an unexpected keyword argument 'strict'

Thanks

**Comment by rsxdalv** [comment]
Thanks for the report, are you using windows 11? This is a problem with
omegaconf - some libraries want a new version and fairseq wants an old one.
Fairseq is old but critical to RVC and Hubert.

**Comment by JeffoDogge** [comment]
This is on Windows 10. Is there any way I can resolve this?

Thanks

**Comment by rsxdalv** [comment]
Yes but it's a little finicky: assuming you are using the new installer,
you have to run installer_scripts/conda_env_cmd.bat then inside of that
`pip install hydra-core==1.1`

This should be enough to fix it.

Also if you could check what versions you have running now I could do a
better diagnostic and perhaps fix the installer mishap.

For that, running the same conda_env_cmd.bat
You should run
`pip show hydra-core omegaconf`
Before installing the 1.1 version

**Comment by JeffoDogge** [comment]
Looks like it's already on the right versions?

> Name: hydra-core
> Version: 1.1.0
> ---
> Name: omegaconf
> Version: 2.1.2

Running "pip install --force-reinstall -v hydra-core==1.1" led to this:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> fairseq 0.12.4 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.1.0 which is incompatible.
> fairseq 0.12.4 requires omegaconf<2.1, but you have omegaconf 2.1.2 which is incompatible.
> Successfully installed PyYAML-6.0.1 antlr4-python3-runtime-4.8 hydra-core-1.1.0 omegaconf-2.1.2

And I get the same TypeError.

**Comment by rsxdalv** [comment]
Thanks for the info, in my tests it worked with these versions. The older
versions are more-so guaranteed to work but musicgen won't be able to run.
I'll be back at my workstation after about 6 hours and then I can
investigate more.

**Comment by rsxdalv** [comment]
Ok, fixed. I had forgotten that fairseq works with versions before 1.1 or after 1.1, but not 1.1. Now the installer correctly installs hydra-core 1.3.2, hopefully if you automatically update it will fix it for you automatically (make sure to agree to updating packages when if it asks you to)

**Comment by JeffoDogge** [comment]
Great, that seems to have fixed it. Many thanks.

> fairseq works with versions before 1.1 or after 1.1, but not 1.1

very intuitive lol
