### ISSUE TITLE
Add stable audio open

### ISSUE THREAD

**Issue by erkinalp** [rsxdalv/tts-generation-webui#351]
Paper: https://arxiv.org/abs/2407.14358
Model: https://huggingface.co/stabilityai/stable-audio-open-1.0

**Comment by rsxdalv** [comment]
Thanks for the suggestion.

Currently stable audio is available within gradio interface for generation and inpainting:
![image](https://github.com/user-attachments/assets/8e4f0487-1632-4edb-89fd-46212513b229)

Would you like it to be added to React UI or for functionality other than generation/inpainting?

**Comment by rsxdalv** [comment]
Stable audio has been added, closing this issue.
