### ISSUE TITLE
RVC Not Installing

### ISSUE THREAD

**Issue by jakethesnake1126** [rsxdalv/tts-generation-webui#359]
Collecting rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc (from -r requirements_rvc.txt (line 1))
Cloning https://github.com/rsxdalv/Retrieval-based-Voice-Conversion to /tmp/pip-install-gvtxsng_/rvc_4587877b9b41411a9a6aeaeff152d51d
Running command git clone --filter=blob:none --quiet https://github.com/rsxdalv/Retrieval-based-Voice-Conversion /tmp/pip-install-gvtxsng_/rvc_4587877b9b41411a9a6aeaeff152d51d
Resolved https://github.com/rsxdalv/Retrieval-based-Voice-Conversion to commit c9ab4e72316b6b4a595cce12ff4b51a6cca5900d
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: av<12.0.0,>=11.0.0 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (11.0.0)
Requirement already satisfied: click<9.0.0,>=8.1.7 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (8.1.7)
Collecting fairseq<0.13.0,>=0.12.2 (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached fairseq-0.12.2.tar.gz (9.6 MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Installing backend dependencies: started
Installing backend dependencies: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
Collecting faiss-cpu<2.0.0,>=1.7.4 (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached faiss_cpu-1.8.0.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: librosa<0.11.0,>=0.10.1 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.10.2.post1)
Requirement already satisfied: numba>=0.59.0 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.60.0)
Collecting poethepoet<0.25.0,>=0.24.4 (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached poethepoet-0.24.4-py3-none-any.whl.metadata (5.0 kB)
Collecting praat-parselmouth<0.5.0,>=0.4.3 (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached praat_parselmouth-0.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (2.9 kB)
Requirement already satisfied: pydub<0.26.0,>=0.25.1 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.25.1)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.0.0)
Requirement already satisfied: python-multipart>=0.0.6 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.0.9)
Collecting pyworld<0.4.0,>=0.3.4 (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached pyworld-0.3.4.tar.gz (251 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: soundfile<0.13.0,>=0.12.1 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.12.1)
Collecting tensorboardx<3.0.0.0,>=2.6.2.2 (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached tensorboardX-2.6.2.2-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: torch<3.0.0,>=2.1.0 in ./installer_files/env/lib/python3.10/site-packages (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (2.3.1)
Collecting torchcrepe<0.0.23,>=0.0.22 (from rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached torchcrepe-0.0.22-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: cffi in ./installer_files/env/lib/python3.10/site-packages (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.16.0)
Requirement already satisfied: cython in ./installer_files/env/lib/python3.10/site-packages (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (3.0.10)
Collecting hydra-core<1.1,>=1.0.7 (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached hydra_core-1.0.7-py3-none-any.whl.metadata (3.7 kB)
Collecting omegaconf<2.1 (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached omegaconf-2.0.6-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
Using cached omegaconf-2.0.4-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.4 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/92/b1/4f3023143436f12c98bab53f0b3db617bd18a7d223627d5030e13a7b4fc2/omegaconf-2.0.4-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
Using cached omegaconf-2.0.3-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.3 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/29/08/a88210c2c1aa0a3f65f05d8a6c98939ccb84b6fb982aa6567dec4e6773f9/omegaconf-2.0.3-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
Using cached omegaconf-2.0.2-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.2 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/72/fe/f8d162aa059fb4f327fd75144dd69aa7e8acbb6d8d37013e4638c8490e0b/omegaconf-2.0.2-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
Using cached omegaconf-2.0.1-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.1 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/86/ec/605805e60abdb025b06664d107335031bb8ebdc52e0a90bdbad6a7130279/omegaconf-2.0.1-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
Using cached omegaconf-2.0.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: regex in ./installer_files/env/lib/python3.10/site-packages (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (2024.7.24)
Collecting sacrebleu>=1.4.12 (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached sacrebleu-2.4.2-py3-none-any.whl.metadata (58 kB)
Requirement already satisfied: tqdm in ./installer_files/env/lib/python3.10/site-packages (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (4.66.4)
Collecting bitarray (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached bitarray-2.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Requirement already satisfied: torchaudio>=0.8.0 in ./installer_files/env/lib/python3.10/site-packages (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (2.3.1)
Requirement already satisfied: numpy in ./installer_files/env/lib/python3.10/site-packages (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.23.5)
Requirement already satisfied: packaging in ./installer_files/env/lib/python3.10/site-packages (from faiss-cpu<2.0.0,>=1.7.4->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (24.1)
Requirement already satisfied: audioread>=2.1.9 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (3.0.1)
Requirement already satisfied: scipy>=1.2.0 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.14.0)
Requirement already satisfied: scikit-learn>=0.20.0 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.5.1)
Requirement already satisfied: joblib>=0.14 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (5.1.1)
Requirement already satisfied: pooch>=1.1 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1.1 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (4.11.0)
Requirement already satisfied: lazy-loader>=0.1 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.4)
Requirement already satisfied: msgpack>=1.0 in ./installer_files/env/lib/python3.10/site-packages (from librosa<0.11.0,>=0.10.1->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.0.8)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in ./installer_files/env/lib/python3.10/site-packages (from numba>=0.59.0->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (0.43.0)
Collecting pastel<0.3.0,>=0.2.1 (from poethepoet<0.25.0,>=0.24.4->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached pastel-0.2.1-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting tomli>=1.2.2 (from poethepoet<0.25.0,>=0.24.4->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: protobuf>=3.20 in ./installer_files/env/lib/python3.10/site-packages (from tensorboardx<3.0.0.0,>=2.6.2.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (4.25.3)
Requirement already satisfied: filelock in ./installer_files/env/lib/python3.10/site-packages (from torch<3.0.0,>=2.1.0->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (3.12.4)
Requirement already satisfied: sympy in ./installer_files/env/lib/python3.10/site-packages (from torch<3.0.0,>=2.1.0->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (1.12)
Requirement already satisfied: networkx in ./installer_files/env/lib/python3.10/site-packages (from torch<3.0.0,>=2.1.0->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (2.8.8)
Requirement already satisfied: jinja2 in ./installer_files/env/lib/python3.10/site-packages (from torch<3.0.0,>=2.1.0->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (3.1.4)
Requirement already satisfied: fsspec in ./installer_files/env/lib/python3.10/site-packages (from torch<3.0.0,>=2.1.0->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (2024.6.1)
Collecting resampy (from torchcrepe<0.0.23,>=0.0.22->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached resampy-0.4.3-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: pycparser in ./installer_files/env/lib/python3.10/site-packages (from cffi->fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) (2.22)
Collecting omegaconf<2.1 (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1))
Using cached omegaconf-2.0.6-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq<0.13.0,>=0.12.2->rvc@ git+https://github.com/rsxdalv/Retrieval-based-Voice-Conversion#egg=rvc->-r requirements_rvc.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
PyYAML (>=5.1.*)
~~~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install fairseq and rvc because these package versions have conflicting dependencies.

The conflict is caused by:
fairseq 0.12.2 depends on omegaconf<2.1
hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Failed to install RVC

**Comment by rsxdalv** [comment]
Hi, I have found the issue and it will be fixed in the new installer update. But to avoid a full reinstall you can manually fix it - 
first, open installer_scripts/conda_env_cmd or installer_scripts/conda_env_bash and do:
`pip install pip==23.3.2`

**Comment by jakethesnake1126** [comment]
After doing this and installing RVC, the UVR5 tab disappears

**Comment by rsxdalv** [comment]
Yes, old RVC broke and the new RVC hasn't implemented UVR5 yet (main
developer of RVC is busy). I tried fixing it before unsuccessfully, but I
can try again.

**Comment by rsxdalv** [comment]
Closing this issue as it is mostly about RVC and `pip` version 24.

As for UVR5, I have added an extension `extension_audio_separator` that uses the original UVR5 code but is not fully finished yet. I will create an issue for it. (RVC is actually not the originator of UVR5, it's a separate project). Here is the issue to follow for it: https://github.com/rsxdalv/tts-generation-webui/issues/398
If you wish it to be added faster, please add a message here or there, that **will** increase the priority.
