### ISSUE TITLE
Error After Installation

### ISSUE THREAD

**Issue by James-Slam** [rsxdalv/tts-generation-webui#36]
After installing I get a few errors and then it crashes

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading extensions:
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded extension: empty_extension
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.
Loading Bark models
        - Text Generation:               GPU: Yes, Small Model: Yes
        - Coarse-to-Fine Inference:      GPU: Yes, Small Model: Yes
        - Fine-tuning:                   GPU: Yes, Small Model: No
        - Codec:                         GPU: Yes
Traceback (most recent call last):
  File "C:\Projects\AI\audiogens\one-click-installers-tts-4.0\tts-generation-webui\server.py", line 14, in <module>
    from src.bark.clone.tab_voice_clone_demo import tab_voice_clone_demo
  File "C:\Projects\AI\audiogens\one-click-installers-tts-4.0\tts-generation-webui\src\bark\clone\tab_voice_clone_demo.py", line 7, in <module>
    from models.bark_voice_cloning_hubert_quantizer.hubert.pre_kmeans_hubert import (
  File "C:\Projects\AI\audiogens\one-click-installers-tts-4.0\tts-generation-webui\models\bark_voice_cloning_hubert_quantizer\hubert\pre_kmeans_hubert.py", line 16, in <module>
    import fairseq
ModuleNotFoundError: No module named 'fairseq'

Done!
Press any key to continue . . .

This is the output on launching start_windows.bat

**Comment by rsxdalv** [comment]
Thanks for reporting it, could you please tell me if you are on Windows 11?
Fairseq might have failed to install. The workaround is to disable audio
cloning for now, by commenting it out from server.py.

**Comment by rsxdalv** [comment]
Ok, now it should only disable the voice clone tab with the newest update:
https://github.com/rsxdalv/tts-generation-webui/pull/37

Fairseq sometimes fails to install, we can handle that as the second part of this issue.

**Comment by ttyksi** [comment]
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading extensions:
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded extension: empty_extension
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.
LLVM ERROR: Symbol not found: __svml_cosf8_ha

Done!
続行するには何かキーを押してください . . .

It did not start.
Windows 11.

**Comment by rsxdalv** [comment]
Thank you for reporting this issue. This might be a bumba/llvmlite related
bug. By chance, are you using an AMD CPU?

I read that there might be an incorrect file, but maybe it's possible to
fix it with an environment variable, without modifying the system. Source:
https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093

**Comment by ttyksi** [comment]
Thanks for your reply.
I am using an AMD CPU.
I will try about your method.
Thank you.

**Comment by James-Slam** [comment]
It installed properly for me now, thanks!
