### ISSUE TITLE
Do we have inference script of the toolkit?

### ISSUE THREAD

**Issue by underdogliu** [rsxdalv/tts-generation-webui#364]
Hello and many thanks for such amazing work! 

I wonder for this repo, do we have the inference sample script? By saying that I mean, we can have a python function/script where the input is text and voice defined (don't even a prompt to control the style), and output is the generated audio? Like,
```
output_audio = generate_audio(input_text, voice_id)
```
Also, do we have pre-built voices?

**Comment by rsxdalv** [comment]
Hi!
There's a lot of different models which have different APIs. Using this
repo to access them is possible but does not have a direct "API". Instead
it would be like importing the source project, i.e., tortoise, and doing
inference with that.

Is there a particular model you want to access?

**Comment by rsxdalv** [comment]
It's possible to access via python, but the question needs to be more specific. Closing for now.
