### ISSUE TITLE
Parler-TTS Support

### ISSUE THREAD

**Issue by nustato** [rsxdalv/tts-generation-webui#366]
Parler-TTS is currently the only model that allows prompt based dynamic generation. It is also the best cloning one at the moment requiring only 3 seconds of recording. Kindly consider adding support for Parler-tts.

https://github.com/huggingface/parler-tts

**Comment by rsxdalv** [comment]
Thank you, work to add this is in progress.

**Comment by rsxdalv** [comment]
Extension for this has been added in the latest update!
I will close this issue. If you need more features or have installation problems, feel free to post here or a new issue.
