### ISSUE TITLE
venv fails to install completely

### ISSUE THREAD

**Issue by srjghseruikg** [rsxdalv/tts-generation-webui#376]
title, trying to run the install scripts from the folder lends to a myriad of installer errors, and halting at some point in the install process.
this is probably the 5th different tts webui i've tried to install this past month that all couldn't even get past the venv part (or had issues once installed) so i don't think i'll try again, but i wanted to make this issue to see if anyone else has been having this problem.

**Comment by rsxdalv** [comment]
Provide error details.
