### ISSUE TITLE
Gradio Auth issues

### ISSUE THREAD

**Issue by theman23290** [rsxdalv/tts-generation-webui#38]
I am having an issue setting a username and password to the Gradio interface on this program. In the webui it allows the user to specify the username and password associated with the Gradio UI. I set the auth as username:password as Gradio Docs suggest to no avail. The error I get is when I restart and go to log into the webui. It will always display the incorrect login error. I tried to configure the same settinng in the config.json file and --gradio-auth-path flag with no changes. Is this something that I am doing wrong or is there a bug in the authentication page of this project?

-theman23290

Specs:
OS: Debian 11
CPU: Xeon E5 2670 v3 (25C)
RAM: 80GB
GPU: None

**Comment by rsxdalv** [comment]
Merged the fix in, the auth should now be as such: "username:password" and now only the username will be printed to console.

**Comment by theman23290** [comment]
Hotfix solved my issue. Thanks for the speedy turn around!
