### ISSUE TITLE
I Can’t Install It at All

### ISSUE THREAD

**Issue by Rodoxdexts** [rsxdalv/tts-generation-webui#383]
In one-click-installers-tts-6.0, when I start start_windows.bat, the cmd opens and closes abruptly.
I tested it with the ai fix:

`@echo off

cd /D "%~dp0"

echo "%CD%"| findstr /C:" " >nul && echo This script relies on Miniconda which cannot be silently installed under a path with spaces. && goto end

set PATH=%PATH%;%SystemRoot%\system32

@rem config
set INSTALL_DIR=%cd%\installer_files
set CONDA_ROOT_PREFIX=%cd%\installer_files\conda
set INSTALL_ENV_DIR=%cd%\installer_files\env
set MINICONDA_DOWNLOAD_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Windows-x86_64.exe
set conda_exists=F

@rem figure out whether git and conda need to be installed
call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" --version >nul 2>&1
if "%ERRORLEVEL%" EQU 0 set conda_exists=T

@rem (if necessary) install git and conda into a contained environment
@rem download conda
if "%conda_exists%" == "F" (
    echo Downloading Miniconda from %MINICONDA_DOWNLOAD_URL% to %INSTALL_DIR%\miniconda_installer.exe

    mkdir "%INSTALL_DIR%"
    call curl -Lk "%MINICONDA_DOWNLOAD_URL%" -o "%INSTALL_DIR%\miniconda_installer.exe" || ( echo. && echo Miniconda failed to download. && goto end )

    echo Installing Miniconda to %CONDA_ROOT_PREFIX%
    start /wait "" "%INSTALL_DIR%\miniconda_installer.exe" /InstallationType=JustMe /NoShortcuts=1 /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%CONDA_ROOT_PREFIX%

    @rem test the conda binary
    echo Miniconda version:
    call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" --version || ( echo. && echo Miniconda not found. && goto end )
)

@rem create the installer env
if not exist "%INSTALL_ENV_DIR%" (
    echo Packages to install: %PACKAGES_TO_INSTALL%
    call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" create --no-shortcuts -y -k --prefix "%INSTALL_ENV_DIR%" python=3.10 || ( echo. && echo Conda environment creation failed. && goto end )
)

@rem check if conda environment was actually created
if not exist "%INSTALL_ENV_DIR%\python.exe" ( echo. && echo Conda environment is empty. && goto end )

@rem activate installer env
call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" || ( echo. && echo Miniconda hook not found. && goto end )

@rem setup installer env
call python webui.py

echo.
echo Done!

:end
pause
`
but it didn't work.

**Comment by Rodoxdexts** [comment]
I'm not a senior programmer btw sussy baka.

**Comment by rsxdalv** [comment]
Hi the new one click installers are within the repository as
"start_tts_webui.bat".
I removed the old installers but people still keep finding them. I will try
to add warnings that they are out of date.

**Comment by Rodoxdexts** [comment]
Now it ran, but there was 1 error, I ran start_tts_webui.bat as administrator and it showed me this in cmd:

```
Transcription started, output file is
C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_scripts\output. log
"Checking if the Micromamba/Conda environment is already installed."
"Micromamba/Conda environment already installed in C:\WINDOWS\system32\installer_files\env, skipping installation"


Starting init app (version: 0.0.6)...


Checking conda installation...
>conda --version
conda 24.7.1
Pulling updates from tts-generation-webui
There was a problem while pulling updates. Aborting...
ENOENT: no such file or directory, open 'C:\WINDOWS\system32\.git\refs\heads\main'
Failed to init the app, exiting...
Press any key to continue. . .
```
![image (8)](https://github.com/user-attachments/assets/7aa04bf4-b8a5-47e2-bf7f-b49b679ed9b8)

**Comment by rsxdalv** [comment]
Try without admin, it changes the directory. Did it not work without admin?

**Comment by Rodoxdexts** [comment]
no, just a message saying it can't run on my computer like this
![Capture-13-515x285](https://github.com/user-attachments/assets/04eca34a-36e7-4a0f-98cd-2a2535ef3cbb)

**Comment by Rodoxdexts** [comment]
Quando rodo com admin, ele para nessa seção do installer_scripts -> root.ps1 -> 
```
& "$PSScriptRoot\init_app.bat"
if ($LASTEXITCODE -ne 0) {
    Write-Host "Failed to init the app, exiting..."
    exit 1
}
```
cmd:
```
"Checking if the Micromamba/Conda environment is already installed."
"Micromamba/Conda environment already installed in C:\WINDOWS\system32\installer_files\env, skipping installation"


Starting init app (version: 0.0.6)...


Checking conda installation...
>conda --version
conda 24.7.1
Pulling updates from tts-generation-webui
There was a problem while pulling updates. Aborting...
ENOENT: no such file or directory, open 'C:\WINDOWS\system32\.git\refs\heads\main'
Failed to init the app, exiting...
Press any key to continue. . .
```

**Comment by Rodoxdexts** [comment]
I created the main folder that 
`ENOENT: no such file or directory, open 'C:\WINDOWS\system32\.git\refs\heads\main'`
was asking, and this appeared:
```
Transcription started, output file is C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_scripts\output.log
"Checking if the Micromamba/Conda environment is already installed."
"Micromamba/Conda environment already installed in C:\WINDOWS\system32\installer_files\env, skipping installation"


Starting init app (version: 0.0.6)...


Checking conda installation...
>conda --version
conda 24.7.1
Pulling updates from tts-generation-webui
There was a problem while pulling updates. Aborting...
EISDIR: illegal operation on a directory, read
Failed to init the app, exiting...
Press any key to continue. . .
```

**Comment by rsxdalv** [comment]
Thanks for all of the info!
I'm encountering this for the first time.
What kind of windows is this?
And if I understand correctly, when it says "can't run this app on your PC"
it also gives the errors, right?

The core issue appears to be that there's no "curl" command, which should
have been available.

**Comment by Rodoxdexts** [comment]
It's Windows 10 pro in portuguese😅

I read the start_tts_webui.bat file to see where the error was leading (and also because I'm paranoid about viruses), and it took me to installer_scripts -> root.ps1, and I edited it with the Windows Powershell editor 
![image (9)](https://github.com/user-attachments/assets/c854e84b-0e0f-496f-95df-861194c4fe17)
and compared it with the cmd errors.

Yeah, it gives errors
```
Transcription started, output file is C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_scripts\output.log "Downloading micromamba from https://github.com/easydiffusion/ easydiffusion/releases/download/v1.1/micromamba.exe to C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\mamba\micromamba.exe" There is already a subfolder or a file C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\mamba.
'curl' is not recognized as an internal or external command, an operable program, or a batch file.
"There was a problem downloading micromamba. Cannot continue."
Press any key to continue. . .
The system cannot find the path specified.
'node' is not recognized as an internal or external command, operable program or batch file.
Failed to init the app, exiting...
Press any key to continue...
```

**Comment by rsxdalv** [comment]
> It's Windows 10 pro in portuguese😅
> 
> I read the start_tts_webui.bat file to see where the error was leading (and also because I'm paranoid about viruses), and it took me to installer_scripts -> root.ps1, and I edited it with the Windows Powershell editor ![image (9)](https://private-user-images.githubusercontent.com/139288429/371607884-c854e84b-0e0f-496f-95df-861194c4fe17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTc0OTgsIm5iZiI6MTcyNzQ1NzE5OCwicGF0aCI6Ii8xMzkyODg0MjkvMzcxNjA3ODg0LWM4NTRlODRiLTBlMGYtNDk2Zi05NWRmLTg2MTE5NGM0ZmUxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxNzEzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzFmMmNjYWMwNjlkNGUzYWZhMDJlYWYxM2Q4MmRhN2JlYzViNzk3MmYwMWEwZjVhZjM2NThmOTU1NDI4NDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fpscQBQRLoooIuKEMGodhWyt2vLEwFPlumr8LzgC0rg) and compared it with the cmd errors.
> 
> Yeah, it gives errors
> 
> ```
> Transcription started, output file is C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_scripts\output.log "Downloading micromamba from https://github.com/easydiffusion/ easydiffusion/releases/download/v1.1/micromamba.exe to C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\mamba\micromamba.exe" There is already a subfolder or a file C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\mamba.
> 'curl' is not recognized as an internal or external command, an operable program, or a batch file.
> "There was a problem downloading micromamba. Cannot continue."
> Press any key to continue. . .
> The system cannot find the path specified.
> 'node' is not recognized as an internal or external command, operable program or batch file.
> Failed to init the app, exiting...
> Press any key to continue...
> ```
> 
> Good Job!

By the way, if you are interested in AI projects and you want to feel safer, you can try out Docker options. You'll need to learn a little about docker, but you'll have a 'VM' that greatly increases the separation between the app and your OS. I don't know what the performance difference would be, but not a huge one since most of the time is spent on the GPU not on the CPU.

As for installing this project the one-click-way:
I see that you don't have 'curl', could you verify that with a simple powershell/cmd terminal to type `curl --help` and show what the output is? It's possible everyone installing the webui until this point had curl installed, so I assumed that it comes preinstalled with windows, but maybe I got it from `git` or `wsl`.

Also thanks for debugging this project, even if this does not give an immediate solution, maybe this will provide better stability 2-3 steps in the future.

Last, but not least, depending on your skill level/dedication you might do a manual install: 
https://github.com/rsxdalv/tts-generation-webui?tab=readme-ov-file#manual-installation-not-recommended
All the project needs to run is python 3 (highly recommended 3.10.11) with the dependencies - pytorch, and requirements files.
The more you install successfully the more will run. Virtual environments are highly encouraged and not using a venv might break your webui at some point. Automatic updates won't happen though.

**Comment by Rodoxdexts** [comment]
I did curl --help and it gave:
```
PS C:\Users\(User)> curl --help
curl : The remote name could not be resolved: '--help'
On line:1 char:1
+ curl --help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by rsxdalv** [comment]
> I did curl --help and it gave:
> 
> ```
> PS C:\Users\(User)> curl --help
> curl : The remote name could not be resolved: '--help'
> On line:1 char:1
> + curl --help
> + ~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> ```

Thanks, this means that powershell does have the curl alias for Invoke-WebRequest. In that case - please do `cmd.exe` to open the classic terminal and once again `curl --help` (for example powershell > cmd.exe > curl --help)

**Comment by rsxdalv** [comment]
Also, assuming, just assuming that curl is the only problem that will happen, you can also just download manually the micromamba.exe and save like this:

tts-generation-webui-main\installer_files\mamba\micromamba.exe 

You can probably use *any* recent micromamba version, but this is the micromamba.exe that the webui uses: https://github.com/easydiffusion/easydiffusion/releases/download/v1.1/micromamba.exe

**Comment by Rodoxdexts** [comment]
> > I did curl --help and it gave:
> > ```
> > PS C:\Users\(User)> curl --help
> > curl : The remote name could not be resolved: '--help'
> > On line:1 char:1
> > + curl --help
> > + ~~~~~~~~~~~
> >     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
> >    eption
> >     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> > ```
> 
> Thanks, this means that powershell does have the curl alias for Invoke-WebRequest. In that case - please do `cmd.exe` to open the classic terminal and once again `curl --help` (for example powershell > cmd.exe > curl --help)

He gives me this:
```
PS C:\Users\(User)> C:\WINDOWS\system32\cmd.exe
Microsoft Windows [version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.

C:\Users\(User)>curl --help
'curl' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by Rodoxdexts** [comment]
these links give different files:
![image (10)](https://github.com/user-attachments/assets/6c6ac98c-3dfe-4253-b982-70fbbb231e01)
![image (11)](https://github.com/user-attachments/assets/6040be5a-70c9-480a-a843-8e75d6033bb4)
These links give different files. Are they different versions for each dev's purposes?

**Comment by Rodoxdexts** [comment]
> Also, assuming, just assuming that curl is the only problem that will happen, you can also just download manually the micromamba.exe and save like this:
> 
> tts-generation-webui-main\installer_files\mamba\micromamba.exe
> 
> You can probably use _any_ recent micromamba version, but this is the micromamba.exe that the webui uses: https://github.com/easydiffusion/easydiffusion/releases/download/v1.1/micromamba.exe
> 
> edit: micromamba releases can be found here https://github.com/mamba-org/micromamba-releases/releases (they lack the .exe extension and need to be renamed manually, i.e. micromamba-win-64 -> micromamba.exe),

now it says:
```
Start-Transcript : Transcription cannot be started.
No C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_scripts\root.ps1:2
caractere:1
+ Start-Transcript -Path $logFile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Transcript], PSInvalidOperationException
    + FullyQualifiedErrorId : CannotStartTranscription,Microsoft.PowerShell.Commands.StartTranscriptCommand

"Checking if the Micromamba/Conda environment is already installed."
"Micromamba/Conda environment already installed in C:\Users\Matheus\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\env, skipping installation"
'DOSKEY' is not recognized as an internal command or external, an operable program or a batch file.

Starting init app (version: 0.0.6)...


Checking conda installation...
>conda --version
conda 24.7.1
Pulling updates from tts-generation-webui
>git pull
Already up to date.
No updates found, skipping...
'DOSKEY' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
Traceback (most recent call last):
  File "C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\server.py", line 11, in <module>
    import gradio as gr
  File "C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\components\annotated_image.py", line 9, in <module>
    import PIL.Image
  File "C:\Users\(User)\Downloads\tts-generation-webui-main\tts-generation-webui-main\installer_files\env\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: Não foi possível encontrar o módulo especificado.
""
""
App exitted or crashed.
Starting command prompt for user to run commands in case of failure...
""
cmd' is not recognized as an internal or external command, operable program or batch file.
Press any key to continue. . .
```

**Comment by rsxdalv** [comment]
This part baffles me - `'DOSKEY' is not recognized as an internal command or external, an operable program or a batch file.` 
It really seems like there's something unorthodox about this Windows system that does not have many tools.

This error should not happen, the installer is made to prevent it from happening.
`ImportError: DLL load failed while importing _imaging: Não foi possível encontrar o módulo especificado.`

Specifically, the installer installs `pillow==10.3.0` to prevent it from happening.

I'm leaning towards recommending Docker.

**Comment by Rodoxdexts** [comment]
> This part baffles me - `'DOSKEY' is not recognized as an internal command or external, an operable program or a batch file.` It really seems like there's something unorthodox about this Windows system that does not have many tools.
> 
> This error should not happen, the installer is made to prevent it from happening. `ImportError: DLL load failed while importing _imaging: Não foi possível encontrar o módulo especificado.`
> 
> Specifically, the installer installs `pillow==10.3.0` to prevent it from happening.
> 
> Estou inclinado a recomendar o Docker.

I'll test docker and get back to you later, thanks for the tip

**Comment by Rodoxdexts** [comment]
> This part baffles me - `'DOSKEY' is not recognized as an internal command or external, an operable program or a batch file.` It really seems like there's something unorthodox about this Windows system that does not have many tools.
> 
> This error should not happen, the installer is made to prevent it from happening. `ImportError: DLL load failed while importing _imaging: Não foi possível encontrar o módulo especificado.`
> 
> Specifically, the installer installs `pillow==10.3.0` to prevent it from happening.
> 
> I'm leaning towards recommending Docker.

I'm almost giving up on this, docker is too complicated

**Comment by rsxdalv** [comment]
There's also WSL. I am still wondering why are there so many differences in your system. Maybe it's not just you, but you are the first one to report these in more than a year.

WSL is like having linux inside of your windows. I've heard some surprising comments that WSL has better performance than pure windows, but again, it's something to learn.

By the way, would you be interested in having this webui be accessible as a website?

**Comment by Rodoxdexts** [comment]
![image](https://github.com/user-attachments/assets/0bc11912-90a3-437a-ab67-26f6a65fca6f)
Thank to God it worked!

**Comment by rsxdalv** [comment]
Great job! For more day-to-day assistance, feel free to join the discord.

**Comment by Rodoxdexts** [comment]
> There's also WSL. I am still wondering why are there so many differences in your system. Maybe it's not just you, but you are the first one to report these in more than a year.
> 
> WSL is like having linux inside of your windows. I've heard some surprising comments that WSL has better performance than pure windows, but again, it's something to learn.
> 
> By the way, would you be interested in having this webui be accessible as a website?

                                                                                  👆
                                                                                yes

**Comment by Rodoxdexts** [comment]
> Great job! For more day-to-day assistance, feel free to join the discord.

Thanks

**Comment by Rodoxdexts** [comment]
![image](https://github.com/user-attachments/assets/b4aaafa0-c463-4430-80f6-7bcf343a7845)
