### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by bbecausereasonss** [rsxdalv/tts-generation-webui#389]
Error during installation: Command failed with exit code 1
Command failed with exit code 1
Failed to init the app, exiting...
Press any key to continue . . .

**Comment by rsxdalv** [comment]
Thanks for the report. There could be many potential reasons therefore I'd like to ask for a more complete log, if possible. Also you may join the discord server to get more assistance with the installation.

**Comment by quantumalchemy** [comment]
btw how to uninstall  everything if used -> start_tts_webui.sh ?
seems to have left a bunch of config folders / files remnants and junk all over the place in debian

**Comment by rsxdalv** [comment]
Besides huggingface and torch hub there shouldn't be anything outside.
These two are used by most projects, so if you delete them, stable
diffusion might download some of them again, for example.
Could you mention the other config files? I could figure out if anything
else gets installed outside of the folder.
Also if you want to maintain your system state, the docker images should
have basically the same performance. However, setup, configuration and
running is more complex.

**Comment by SoftologyPro** [comment]
Same issue here under Windows.

Solving environment: failed

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package nodejs-22.9.0-h57928b3_0 is excluded by strict repo priority
  - package ffmpeg-4.4.2-lgpl_hf152e9b_13 is excluded by strict repo priority
  - package postgresql-16.4-hd835ec0_2 is excluded by strict repo priority


Error during installation: Command failed with exit code 1
Command failed with exit code 1
Failed to init the app, exiting...
Press any key to continue . . .
```

Full log attached.
[output.log](https://github.com/user-attachments/files/17353225/output.log)
Does that help?

**Comment by rsxdalv** [comment]
Thank you for the details, they help but I'm still confused and will need
to do more research. Win64 should work, just yesterday I successfully ran
the exact installation command that failed for your machine.
Maybe it was a sneaky conda update and I will need to deal with that.

**Comment by rsxdalv** [comment]
No, even the conda version matches. I will try to do more tests to see if I
can reproduce the error. I have a few ideas how to get the install to work
but no clear reason why the same can work yesterday but not today.

**Comment by SoftologyPro** [comment]
My second PC is dead so I cannot test it there until I get another GPU, but all I am doing is running this in a directory without spaces.  I will see if I can get other people to test it.

```
@echo off

cd
echo *** Deleting tts-generation-webui directory if it exists
if exist tts-generation-webui\. rd /S /Q tts-generation-webui

echo *** Cloning tts-generation-webui repository
git clone https://github.com/rsxdalv/tts-generation-webui
cd tts-generation-webui

echo *** Installing tts-generation-webui
call start_tts_webui.bat

echo *** Finished TTS Generatioon WebUI install
echo.
echo *** Scroll up and check for errors.  Do not assume it worked.
pause
```

I want to add support for it into Visions of Chaos as I have had some requests for it.

**Comment by SoftologyPro** [comment]
I just ran the same install on another PC with a 3090 and it installed fine.  Something with the 3090?
3090 log attached too if that helps work out why.
[output.log](https://github.com/user-attachments/files/17359380/output.log)

**Comment by SoftologyPro** [comment]
More issues from another user.  Gets past my first error above, but other problems.
![image](https://github.com/user-attachments/assets/a1fc0bd7-7e37-4d89-b75e-219fcf84afd2)
when interactive with the gradio version
[message.txt](https://github.com/user-attachments/files/17362356/message.txt)

**Comment by rsxdalv** [comment]
> om another user. Gets past my first error above, but othe

1. the pip errors are unavoidable when installing these projects together because the project devs have the incorrect versions listed (fairseq being a big issue here)
2. I will fix the Dataframe height but my next update will replace pip with uv and might once again cause issues. Overall things are getting better but for a app-in-app scenario you might want a separate update lane. One thing though is that stuff does break 'on it's own'. In this case as well - Gradio (again) did not obey semver and released a version (around 4.44) which is not compatible with 4.41, so even the previous installer will fail when installing this version. Docker containers are great for this because they are almost 'frozen' (besides plugin installation).
3. The API error is a new one.

**Comment by SoftologyPro** [comment]
I know all about versions not being specified or being the wrong verison.
https://softologyblog.wordpress.com/2023/10/10/a-plea-to-all-python-developers/

**Comment by rsxdalv** [comment]
Exact version numbers actually prevent multiple projects from being
installed together (and critical patches). So it's a painful balance.
It wouldn't matter much if you could fork everything, but you can't. Some
packages like xformers take hours to compile from source.
It still never ceases to amaze how well NPM handles it.

**Comment by SoftologyPro** [comment]
> Exact version numbers actually prevent multiple projects from being installed together (and critical patches). 
Not in my case.  You isolate specific versions in Python venvs.  I have hundreds of separate scripts working fine in their own environments on the same PC.  Until a package outside my control is messed up.

**Comment by SoftologyPro** [comment]
> Exact version numbers actually prevent multiple projects from being installed together (and critical patches).>

Not in my case.  You isolate specific versions in Python venvs.  I have hundreds of separate scripts working fine in their own environments on the same PC.  Until a package outside my control is messed up.

**Comment by rsxdalv** [comment]
Do you have issues with linking PyTorch installs to prevent large disk
usage?
I have not yet fully tested the impact of isolating each model in its own
process to see how much RAM and VRAM multiple PyTorches, Diffusers,
Transformers, xformers and fairseqs use.

**Comment by rsxdalv** [comment]
Ok, the API errors also probably originated from Gradio. The latest update uses the newest gradio version, solving 2. and 3. problems. I saw a bit of a visual problem with Firefox on darkmode but Chromium based browsers are fine. Hopefully Gradio will accept the fix soon.
