### ISSUE TITLE
missing config.json

### ISSUE THREAD

**Issue by ekswathi** [rsxdalv/tts-generation-webui#4]
config.json is missing

**Comment by rsxdalv** [comment]
Thank you for finding this issue!
I have fixed the automatic config.json creation, please test with the latest changes.
https://github.com/rsxdalv/tts-generation-webui/commit/2b71459f4b57c67206d2f2efc577d00593c77d8c


Also, for backup if this ever happens again, here's a simple config.json:
```json
{
  "model": {
    "text_use_gpu": true,
    "text_use_small": true,
    "coarse_use_gpu": true,
    "coarse_use_small": true,
    "fine_use_gpu": true,
    "fine_use_small": false,
    "codec_use_gpu": true,
    "load_models_on_startup": true
  },
  "load_models_on_startup": false
}
```

**Comment by thomasbidou** [comment]
I don't have the config error anymore.
However, I have this one :
Traceback (most recent call last):
  File "C:\AI\Audio\tts-bebui\tts-generation-webui\server.py", line 5, in <module>
    from generation_tab_bark import generation_tab_tortoise, generation_tab_bark
  File "C:\AI\Audio\tts-bebui\tts-generation-webui\generation_tab_bark.py", line 3, in <module>
    from gen_tortoise import generate_tortoise_
  File "C:\AI\Audio\tts-bebui\tts-generation-webui\gen_tortoise.py", line 10, in <module>
    from models.tortoise.tortoise.api import TextToSpeech, MODELS_DIR
ModuleNotFoundError: No module named 'models.tortoise'

**Comment by rsxdalv** [comment]
Updated the scripts,
https://github.com/rsxdalv/one-click-installers-tts/blob/main/webui.py#L56

**Comment by thomasbidou** [comment]
works like charme.
Thank you.

**Comment by AIhasArrived** [comment]
@ekswathi  @thomasbidou 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.

**Comment by ekswathi** [comment]
Sure i will👍🏼😊. Give me 2 days

**Comment by ekswathi** [comment]
bro, i used Seait(https://github.com/diStyApps/seait)for installing Bark. because seait do all the work for us. then we go to clone voice tab in the top there is a menu for adding your voice clip. we don't need long audio for that. just 1minute audio is working nice for me. but it must be really clear without background noise or instrument music behind. you can try first with some ted talk or podcast audios for testing purpose. good luck.
