### ISSUE TITLE
Cloning Voice is giving Metadate is None expection

### ISSUE THREAD

**Issue by bizrockman** [rsxdalv/tts-generation-webui#40]
After generation this function is called
`
def save_cloned_voice(
    full_generation: FullGeneration,
):
    voice_name = f"test_clone_voice{str(np.random.randint(100000))}"
    filename = f"voices/{voice_name}.npz"
    save_npz(filename, full_generation)
    return filename
`

using the method save_npz from npz_tools.py
`def save_npz(filename: str, full_generation: FullGeneration, metadata: dict[str, Any]):
    def pack_metadata(metadata: dict[str, Any]):
        return list(json.dumps(metadata))

    np.savez(
        filename,
        **{
            **compress_history(full_generation),
            "metadata": pack_metadata(metadata),
        },
    )
`

Seems that metadata is missing. What can I use as Metadata?

The is a test call when calling npz_tools directly. That sets the metadata this way:

`    
metadata_in = {
        "_version": "0.0.1",
        "_hash_version": "0.0.2",
        "_type": "bark",
        "is_big_semantic_model": True,
        "is_big_coarse_model": False,
        "is_big_fine_model": False,
        "prompt": "test",
        "language": None,
        "speaker_id": None,
        "hash": "98b14851692f09df5e89c68f0a8e2013",
        "history_prompt": "continued_generation",
        "history_prompt_npz": None,
        "history_hash": "98b14851692f09df5e89c68f0a8e2013",
        "text_temp": 0.7,
        "waveform_temp": 0.7,
        "date": "2023-06-07_16-56-09",
        "seed": "2039063546",
    }
`

Can simply copy paste this code to be used in save_cloned_voice? Or do I need to set the values like Language, speaker, prompt ...

**Comment by rsxdalv** [comment]
Fixed in https://github.com/rsxdalv/tts-generation-webui/pull/41

I also skipped the values that don't make sense for new cloned voices.

**Comment by rsxdalv** [comment]
Closing since this is resolved, if there's still problems with this, please comment or reopen.
