### ISSUE TITLE
During one-click install: "The system cannot find the path specified. 'node' is not recognized as an internal or external command,"

### ISSUE THREAD

**Issue by chanhee70** [rsxdalv/tts-generation-webui#406]
During the one-click install, I ran into this problem:

 
... checking for Visual Studio Build Tools installation...
Visual Studio Build Tools is installed, continuing...
The system cannot find the path specified.
'node' is not recognized as an internal or external command,
operable program or batch file.
Failed to init the app, exiting...
Press any key to continue . . .

Any suggestion to solve the problem will be greatly appreciated. Thanks.

**Comment by chanhee70** [comment]
Installing this seems to have solved the problem.

https://nodejs.org/en/download/prebuilt-installer

**Comment by chanhee70** [comment]
Now I get this problem during the installation:


Pulling updates from tts-generation-webui
>git pull
remote: Enumerating objects: 3389, done.
remote: Counting objects: 100% (1083/1083), done.
remote: Compressing objects: 100% (566/566), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5398 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
There was a problem while pulling updates. Aborting...
Command failed with exit code 1
Failed to init the app, exiting...
Press any key to continue . . .

**Comment by rsxdalv** [comment]
This appears to be a connection issue. I will try to make an offline mode where it still starts if it fails to get the updates, but because it still needs the models it might be difficult to run if there are any connection interruptions. 

Node being missing suggests that the initial setup failed, since nodejs should be installed automatically by conda.

**Comment by chanhee70** [comment]
Thank you for your help!

**Comment by chanhee70** [comment]
There seemed to be some progress, it was downloading, but then now I'm getting the following error:
 
![Screenshot 2024-10-29 104831](https://github.com/user-attachments/assets/935eb6e2-f287-438a-866f-a739c054c0e1)

Any suggestions to fix this problem would be greatly appreciated!
