### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by jdavid82** [rsxdalv/tts-generation-webui#409]
When I follow the simple installation steps and double click on `start_tts_webui.bat` it gets stuck trying to download this package:
![image](https://github.com/user-attachments/assets/473cdbae-8cac-4848-9617-0e35c9dada45)
The package is libcublas-dev-11.11.

**Comment by rsxdalv** [comment]
Thank you for reporting this issue.
I'm seeing some similarity to this:

https://github.com/ContinuumIO/anaconda-issues/issues/13092

Do you have any specific network settings like VPN or firewalls? Also, could you please check in task manager if it's completely frozen, or if the process is slowly downloading the packages?

**Comment by jdavid82** [comment]
I experienced network interruptions at the time, once I resolved my network issues I deleted everything and then installed it successfully, please mark this as closed.

**Comment by rsxdalv** [comment]
Got it, and thanks for the report. Network issues causing conda to freeze (but not show any error) could help some people. 
(A network test could probably be added to the installer/conda, but that's low priority.)
