### ISSUE TITLE
Feature request F5 TTS

### ISSUE THREAD

**Issue by Aamir3d** [rsxdalv/tts-generation-webui#413]
I've started using F5 TTS https://github.com/SWivid/F5-TTS for quick voice sampling.
It offers great audio quality and is very fast.
Is there a possibility to include this model in the GUI?

**Comment by rsxdalv** [comment]
It's there but the new gradio interface makes tabs hard to see. If you click the three dots at the end of the TTS tabs, you'll see it as an extension.

**Comment by Aamir3d** [comment]
> It's there but the new gradio interface makes tabs hard to see. If you click the three dots at the end of the TTS tabs, you'll see it as an extension.

Thanks - I didn't notice this. I'll bring attention to this in the post.

My thought for the interface, would it make more sense to have it as a dropdown or a left vertical tabs (while leaving the top menu as is?)

**Comment by rsxdalv** [comment]
> > It's there but the new gradio interface makes tabs hard to see. If you click the three dots at the end of the TTS tabs, you'll see it as an extension.
> 
> Thanks - I didn't notice this. I'll bring attention to this in the post.
> 
> My thought for the interface, would it make more sense to have it as a dropdown or a left vertical tabs (while leaving the top menu as is?)

The truth is that I'm in a bit of a bind. Updating gradio seems like a good idea but they both improve and break stuff at the same time. I will create an issue to specifically ask them to fix the tabs. I didn't need them to make the three dots and it's on by default, and it frankly just isn't a good solution at all.
Also new gradio versions seem to cause bugs with the React UI that I need to resolve.
But the real answer is to expand the React UI as much as possible, as that is the only place I can actually make good UX. I don't think I can even make left vertical tabs in gradio (without making a custom gradio component or a lot of CSS).
