### ISSUE TITLE
Fatal error during Pulling updates from tts-generation-webui

### ISSUE THREAD

**Issue by admdev24** [rsxdalv/tts-generation-webui#430]
Starting init app (version: 0.0.6)...

Checking conda installation...
>conda --version
conda 24.11.0

Pulling updates from tts-generation-webui
>git pull
fatal: unable to access 'https://github.com/rsxdalv/tts-generation-webui/': schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
There was a problem while pulling updates. Aborting...
Command failed with exit code 1
Failed to init the app, exiting...
Press any key to continue . . .

**Comment by admdev24** [comment]
Simple restart solved the issue.

**Comment by rsxdalv** [comment]
Thanks for the report, it might be useful to others! CRYPT_E_REVOCATION_OFFLINE - sounds like it was a network/internet issue.
