### ISSUE TITLE
"bark" and "tortoise" 

### ISSUE THREAD

**Issue by HobisPL** [rsxdalv/tts-generation-webui#5]
Is this two separate things, "bark" and "tortoise" or are you planning to somehow combine them so that "bark" can use the "tortoise" model?

**Comment by rsxdalv** [comment]
They are separate models, if anything I suspect there might be a way to reuse tortoises generations for some bark usage, but that is ways off for now.

Bark has a fast response time, while tortoise can generate massive amount of variations quickly.

**Comment by rsxdalv** [comment]
I still don't see this as being viable in the upcoming future. Most people won't have enough VRAM to load both models and even then tortoise is quite slow. The realistic usage right now is already possible - use tortoise to generate a wav and use it to clone voice in bark. And that's already possible as of now.
