### ISSUE TITLE
[Feature Suggestion] Combine efforts with gitmylo/audio-webui

### ISSUE THREAD

**Issue by underlines** [rsxdalv/tts-generation-webui#62]
You might or might not be aware of gitmylo/audio-webui which has very similar goals. Maybe it would make sense to combine forces with gitmylo?

https://github.com/gitmylo/audio-webui

**Comment by rsxdalv** [comment]
It's a newer repository. Currently mylos code is what powers the voice
cloning. There's also bark infinity and other repo's like mrq. However, so
far there's been no "convergence" of audio repo's yet.
I'm working on making the installation and deployment easier, maybe it'll
become a platform. But it will require updates and coordination in several
projects. This also includes license compatibilities.

**Comment by underlines** [comment]
> It's a newer repository. Currently mylos code is what powers the voice cloning. There's also bark infinity and other repo's like mrq. However, so far there's been no "convergence" of audio repo's yet. I'm working on making the installation and deployment easier, maybe it'll become a platform. But it will require updates and coordination in several projects. This also includes license compatibilities.

Sounds awesome! Thanks for your efforts.

Best of luck to you.
