### ISSUE TITLE
TTS-4.0  No module named deepspeed     (Ans. Install TTS-6.0)

### ISSUE THREAD

**Issue by Magenta-6** [rsxdalv/tts-generation-webui#69]
Hi again.
I'm using your TTS 4.0 on a daily basis.
I think its the most comprehensive and usable so far.
I ran the update_windows.bat to get the latest.
I saw that it brought in some changes, however when I later tried to start the app I ran into the following:

+++++++++++++++++++++++++++++++++++++
    from src.tortoise.gen_tortoise import generate_tortoise_long
  File "C:\SuperStableDiffusion2.0\TTS-4.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
  File "C:\SuperStableDiffusion2.0\TTS-4.0\installer_files\env\lib\site-packages\tortoise-2.4.2-py3.10.egg\tortoise\api.py", line 14, in <module>
    from tortoise.models.autoregressive import UnifiedVoice
  File "C:\SuperStableDiffusion2.0\TTS-4.0\installer_files\env\lib\site-packages\tortoise-2.4.2-py3.10.egg\tortoise\models\autoregressive.py", line 6, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'

Done!
Press any key to continue . . .
+++++++++++++++++++++++++++++++++++++++

I opened cmd and tried running >pip install deepspeed
but it cried out for torch, (which I know is already installed) but didn't want to stuff it up - so I decided to leave it.
Your thoughts?

**Comment by rsxdalv** [comment]
I had to update the installer because the dependencies can't be installed
all at once. One package requires hydra-core that the other package can't
use.

That's why now there's a second script: update.py that the new installer
calls (if you *had* to do it manually, that would be cmd_windows.bat -> `cd
tts-generation-webui` then `python update.py` but please see the Upgrade
section in readme.)

**Comment by Magenta-6** [comment]
I followed the instructions above.
It seemed to go well until the end:

+++++++++++++++++++++++++++++
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.40.1
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Failed to install RVC dependencies
+++++++++++++++++++++++++++++++++

So I found a link to your one click installer:
https://github.com/rsxdalv/one-click-installers-tts/archive/refs/tags/v6.0.zip

I ran it and it installed beautifully.
Then moved models and voices across to TTS-6.0

PS.  The Demucs Demo is amazing!

**Comment by Magenta-6** [comment]
Thanks for your work.

**Comment by rsxdalv** [comment]
Happy it got resolved!
Thanks for the feedback, I might improve the demucs module
