### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by MaximoXv** [rsxdalv/tts-generation-webui#71]
I tried use RVC Beta Demo so i get this error.
"RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'"
How can i fix this?

Specifications:
- f0 Up key = 0
- f0 Method = harvest
- Index Rate = 0,66
- Filter Radius = 3
- Resample SR = 0
- RMS Mix Rate = 1
- Protect = 0,33

Hubert
-Device = CPU (I did the installation for "CPU only")
- Use half precision model (Depends on GPU support) = [  ](not check)

**Comment by rsxdalv** [comment]
Should work with the latest update. The RVC backend code just straight up ignored the half parameter. I added a workaround, so now if is_half is unchecked, it will work on CPU.
https://github.com/rsxdalv/tts-generation-webui/pull/74

**Comment by MaximoXv** [comment]
> Should work with the latest update. The RVC backend code just straight up ignored the half parameter. I added a workaround, so now if is_half is unchecked, it will work on CPU. #74

Now works perfectly 👍
Thx
