### ISSUE TITLE
Where to put custom trained Tortoise models and voices?

### ISSUE THREAD

**Issue by Pashahlis** [rsxdalv/tts-generation-webui#72]
RVC models one just drops into the GUI, but how do I select a custom Tortoise model and voice that I trained myself?

I cannot find a Tortoise folder or data/models folder (which I saw some folks here mention) in my installtion directory, nor can I find a dropdown or other thing in the GUI where I could select custom models. Though I did find a selection for Tortoise voices, I could not find out where those are installed to add my own.

**Comment by rsxdalv** [comment]
For voices this is the directory, before I add a proper one:
one-click-installers-tts-main/installer_files/env/Lib/site-packages/tortoise/voices

At this very moment my internet has failed so I can't comment much about
the model selection.

**Comment by rsxdalv** [comment]
As for the models, they are located in <user>/.cache/tortoise/models or within the location specified by the environment variable TORTOISE_MODELS_DIR, however to reload them the UI needs to be restarted.
For tortoise, do you expect to change all of the models, override defaults or otherwise?

**Comment by rsxdalv** [comment]
Updated, hopefully this can make it sufficiently convenient: 
![localhost_7860_ (6)](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/ce1145e1-102f-4062-8ed4-13912b00004d)

**Comment by rsxdalv** [comment]
If there are more feature requests, please reopen the issue.
