### ISSUE TITLE
Possible bug: "cannot import name 'open_folder' from 'src.history_tab.open_folder'" on launch (WSL2)

### ISSUE THREAD

**Issue by Amajiro** [rsxdalv/tts-generation-webui#75]
Using the one-click installer, I got errors launching the webUI after installation:

```
Traceback (most recent call last):
  File "/home/***/tts-generation-webui/tts-generation-webui/server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "/home/***/tts-generation-webui/tts-generation-webui/src/tortoise/generation_tab_tortoise.py", line 2, in <module>
    from src.history_tab.open_folder import open_folder
ImportError: cannot import name 'open_folder' from 'src.history_tab.open_folder' (/home/***/tts-generation-webui/tts-generation-webui/src/history_tab/open_folder.py)
```
I resolved this by changing `elif sys.platform == "linux2"`: to `elif sys.platform == "linux":`" in src/history_tab/open_folder.py. Maybe something to do with how python recognises WSL2? Anyway that fixed it.

**Comment by rsxdalv** [comment]
Great, thanks! I will replace it with `sys.platform.startswith('linux')`

**Comment by rsxdalv** [comment]
By the way - quick question - is it possible to open a PR or is there some restriction I have forgotten?

**Comment by Amajiro** [comment]
There may well be lol but I'm a total GitHub noob.

**Comment by rsxdalv** [comment]
Added fix in: https://github.com/rsxdalv/tts-generation-webui/pull/77

I will close the issue, but if it's not fully resolved, please reopen it.
