### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by RakibRyan** [rsxdalv/tts-generation-webui#80]
This script relies on Miniconda which can not be silently installed under a path with spaces.
Press any key to continue . . .

**Comment by rsxdalv** [comment]
Please use a folder without any spaces.

**Comment by RakibRyan** [comment]
unfortunately on windows 11 it doesn't let me use my name without spaces. I can't even change folder name to single name as microsoft account uses both first & last name to create the users folder.

**Comment by rsxdalv** [comment]
Windows 11 is quite forceful. Is it possible to install it in a different location like `C:\` or `C:\ai_projects\tts-generation-webui`?

**Comment by RakibRyan** [comment]
how would I do that? if I just change the loaction of script to a folder & run the batch file would that work?

**Comment by rsxdalv** [comment]
Yes, if you would copy the files to a different place and run it from there.

**Comment by RakibRyan** [comment]
I got it working but at the end I got this warning.

Generating autoregressive samples..
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:55<00:00,  3.48s/it]
Computing best candidates using CLVP
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:31<00:00,  1.97s/it]
Transforming autoregressive outputs into audio..
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:34<00:00,  1.15s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:24<00:00,  1.24it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:24<00:00,  1.24it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:26<00:00,  1.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.50it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:26<00:00,  1.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:19<00:00,  1.50it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:23<00:00,  1.30it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:18<00:00,  1.58it/s]


G:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\processing_utils.py:171: UserWarning: Trying to convert audio automatically from float32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))

**Comment by rsxdalv** [comment]
Good to hear that!
This error means nothing. It's just something gradio library likes to spew
out.
