### ISSUE TITLE
Installation on cloud gpu

### ISSUE THREAD

**Issue by h3ndrik** [rsxdalv/tts-generation-webui#82]
Hey, i would like to run this somewhere in the cloud. Either on google colab, or a runpod.io container (that also has jupyter notebooks available).

Now the one click installer that is recommended, isn't very helpful in that case. I'd like to run this in a jupyter/colab notebook like people do with the other WebUIs out there. Is that an intended use case? Are there instructions floating around or do i have to adapt the manual installation instructions?

Regarding those manual installation: What do you mean with number 8:  "clone the repos in the ./models/ directory and install requirements under them". I can't find a directory with that name. do you mean "./data/models/"? And what do i clone there? Can you please specify the repositories somewhere or add them as git submodules?

I think all the other instructions could simply be included in such a notebook. Thanks.

**Comment by rsxdalv** [comment]
Hi, I did try to run it on Collab but that got deprioritized. It's
possible. If I'll find my code I'll share it.

As for the models - I'll remove that part. (Before the installation was so
"custom" that it downloaded several other repositories. Now those projects
have been made installable.)
