### ISSUE TITLE
Saving Demuxed files

### ISSUE THREAD

**Issue by Magenta-6** [rsxdalv/tts-generation-webui#85]
@rsxdalv - Is there a way to save demuxed files?
On the video there are three dots on the right hand side of the separated track with a save option but I'm guessing this is a demo version. Presumably you will set up a button to feed the track to a vocoder or to a voice cloner.
(Helpful video by the way).

regards

@Magenta-6
![screenshot 2023-07-21](https://github.com/rsxdalv/tts-generation-webui/assets/116250074/5d9ac799-5147-419c-83d2-ffe3ab582e6a)

**Comment by rsxdalv** [comment]
Oh, actually in chrome it has those buttons. I never knew that other
browsers don't give them. I'll add the download buttons. Thanks for the
feedback!
Until I add the download, I recommend trying another browser for this
specific use case.

**Comment by Magenta-6** [comment]
Perfect. I did not think about that. I always run stable diffusion and oogabooga in Chrome for exactly the same reason.
However because Firefox is my default browser it automatically opens when i launch the webui-.bat file.
![screenshot 2023-07-21a](https://github.com/rsxdalv/tts-generation-webui/assets/116250074/34550111-7b49-4010-8937-7c0d66259cc9)
