### ISSUE TITLE
RuntimeError: Input type (MPSHalfType) and weight type (torch.HalfTensor) should be the same for RVC with mps

### ISSUE THREAD

**Issue by xAIxxxxNAGI** [rsxdalv/tts-generation-webui#89]
Hi, I faced this issue when I tried to use RVC with mps (mac m2), and I got this issue.

```
没有发现支持的N卡, 使用MPS进行推理

logs...

RuntimeError: Input type (MPSHalfType) and weight type (torch.HalfTensor) should be the same
```

This is current GUI setting 

<img width="1322" alt="Screenshot 2023-07-21 at 19 50 12" src="https://github.com/rsxdalv/tts-generation-webui/assets/139841059/360f0246-65eb-4d2b-b1ac-1c4c0187338e">

<img width="975" alt="Screenshot 2023-07-21 at 19 50 29" src="https://github.com/rsxdalv/tts-generation-webui/assets/139841059/6688faf1-d7e0-46f6-a111-14d3d67abce4">

Can you please check this issue?

**Comment by xAIxxxxNAGI** [comment]
I found out that RVC config is automatically set device="mps" if mps is available. 
So that's why it shows logs as 没有发现支持的N卡, 使用MPS进行推理, then it caused mismatch of device setting.

I can make it work by adding this hard code here.

https://github.com/rsxdalv/tts-generation-webui/blob/main/src/rvc_tab/rvc_tab.py#L61

```
    if device == "cpu":  # Workaround for "slow_conv2d_cpu" not implemented for 'Half'
        config.is_half = is_half
        config.device = "cpu"
```

But I guess better solution is to enable mps for the device setting in UI, but I'm not sure if it is possible.

**Comment by rsxdalv** [comment]
I can add mps as an option, but I can't test if it will work outright. For now, here's the code to add it to the dropdown
https://github.com/rsxdalv/tts-generation-webui/blob/e14c4ca29a3acd679e9b0e1b2966ef7275d7b969/src/rvc_tab/rvc_tab.py#L217

python
```
                        ["cuda:0", "cpu", "mps"], label="Device", value="cuda:0"
```

python
```
with gr.Group():
                gr.Markdown("### Hubert")
                with gr.Row():
                    device = gr.Dropdown(
                        ["cuda:0", "cpu", "mps"], label="Device", value="cuda:0"
                    )
                    is_half = gr.Checkbox(
                        label="Use half precision model (Depends on GPU support)",
                        value=False,
                    )
                    gr.Button(
                        value="Clear Hubert (to reload on next generation)",
                        variant="secondary",
                    ).click(
                        fn=lambda: inject_hubert(None)
                    )  # type: ignore
```

**Comment by xAIxxxxNAGI** [comment]
Thanks! I tried to add the mps option in RVC section, and I got this error

```
NotImplementedError: The operator 'aten::_weight_norm_interface' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

It seems weight_norm_interface is not implemented yet in Pytorch, so looks like it is better to wait for the update.
I checked the thread here and found many votes for the implementation, so I hope it will be included soon.
 
https://github.com/pytorch/pytorch/issues/77764

**Comment by rsxdalv** [comment]
Interesting, I thought that they would have this set up since they force
RVC. If you'd like to test the CPU fallback you can put the

`PYTORCH_ENABLE_MPS_FALLBACK=1`

Inside of tts-generation-webui/.env and restart the webui. This file
gets overwritten only when you edit bark or model location settings.
