### ISSUE TITLE
Train on expressions

### ISSUE THREAD

**Issue by adhikjoshi** [rsxdalv/tts-generation-webui#94]
Hi, voice cloning is working good with bark, is there way of training more expressions in Bark?

**Comment by MiYakuGaming** [comment]
I've been doing great with Tortoise TTS using [I am very happy and sad,] Your emotional text
There's variants that have worked for me such as [I am very happy and yelling with excitement,] Your emotional text

**Comment by rsxdalv** [comment]
I will close the issue for now. Please reopen it if there are more questions.
