### ISSUE TITLE
Upload model/index in RVC demo issue 

### ISSUE THREAD

**Issue by sergedahdouh** [rsxdalv/tts-generation-webui#95]
when i press on the icon to upload i receive this error 
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/tts-generation-webui/src/tortoise/gr_reload_button.py", line 24, in <lambda>
    fn=lambda: open_folder(dirname),
  File "/content/tts-generation-webui/src/history_tab/open_folder.py", line 12, in open_folder
    subprocess.check_call(["xdg-open", "--", folder_path])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xdg-open', '--', '/content/tts-generation-webui/data/models/rvc/checkpoints']' returned non-zero exit status 1.
xdg-open: unexpected option '--'
Try 'xdg-open --help' for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/tts-generation-webui/src/tortoise/gr_reload_button.py", line 24, in <lambda>
    fn=lambda: open_folder(dirname),
  File "/content/tts-generation-webui/src/history_tab/open_folder.py", line 12, in open_folder
    subprocess.check_call(["xdg-open", "--", folder_path])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xdg-open', '--', '/content/tts-generation-webui/data/models/rvc/checkpoints']' returned non-zero exit status 1.

**Comment by rsxdalv** [comment]
Thanks for the log, it seems that xdg-open couldn't open the directory for rvc checkpoints. Could you try opening it manually `/content/tts-generation-webui/data/models/rvc/checkpoints`? The directory should exist, but that could be an issue.

**Comment by sergedahdouh** [comment]
> Thanks for the log, it seems that xdg-open couldn't open the directory for rvc checkpoints. Could you try opening it manually `/content/tts-generation-webui/data/models/rvc/checkpoints`? The directory should exist, but that could be an issue.

thank you for your reply, 
<img width="368" alt="Screenshot 2023-06-28 at 16 08 41" src="https://github.com/rsxdalv/tts-generation-webui/assets/40029858/27f1d02f-2639-435a-af2e-a7969b6b07de">

https://github.com/rsxdalv/tts-generation-webui/assets/40029858/71399526-45f6-4e0d-8de3-b686a2b7a832


actually i have add it manually but did not work

**Comment by rsxdalv** [comment]
I see, I think xdg-open might be impossible for google collab.

**Comment by sergedahdouh** [comment]
> I see, I think xdg-open might be impossible for google collab.

maybe we can use torch.load('model.pth')

**Comment by sergedahdouh** [comment]
> I don't have a google collab open right now but I think if you use the second part, and drag and drop or upload the files there it will work. ![image](https://user-images.githubusercontent.com/6757283/255674685-40316119-1040-4b97-a985-f2a9f4bbd0bf.png)

yes i upload them like that you need to remove and upload it serval times to work

**Comment by sergedahdouh** [comment]
also i have question how to upload more voices to tts as upload is not working which folders  ?

**Comment by rsxdalv** [comment]
Ok I launched the collab and I can see that it's having issues, I'll try to solve them within a few hours.

**Comment by rsxdalv** [comment]
Ok, when I placed the files like so it works:
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/029f3bf3-06b1-4ae4-84e4-ff3d13e12774)
Note - there needs to be a directory (with any name) under `./checkpoints`, like `./checkpoints/some_model/` for me I just have each model in it's own directory.
Once they are there, press the refresh button:
![image](https://github.com/rsxdalv/tts-generation-webui/assets/6757283/b1f2f36b-9ec6-48e2-a94f-550916e3fc21)


Also, when I uploaded them directly it gave me the NoneType error on the first try but second time I pressed "Convert" it worked.

**Comment by bucketcat** [comment]
Same problem on Docker.

**Comment by rsxdalv** [comment]
> Same problem on Docker.
> 
> Edit: Directory structure is completely broken on Docker, as you can't open a folder normally with it being containerized. So anything using 'xdg-open' is just non-functional (and a lot of Gradio related stuff).
> 
> Is the docker version actively maintained?@rsxdalv
> 
> Edit 2: Setting up a default bind mount to access local dirs might be a smart idea, albeit technically unsafe as you defeat the whole point of containerizing. Currently, a lot of Gradio UI also breaks (visually and functionally), buttons related to opening local directories. This would solve files not importing during runtime, accessing outputs locally, custom voices locally and most likely fix the graphical bugs. Screenshot included.
> 
> ![broken_ui](https://user-images.githubusercontent.com/91589201/273579375-27204428-252d-46f9-ae37-d388f1eabcba.png)

Just for reference: I don't get emails nor notifications for edits. If it's a bigger update, feel free to post another comment. This time I never realized you were trying to reach me.

The docker version is maintained though yes xdg open wouldn't work on it. Did you build the container yourself or use an image? I'm worried there might be out of date images but they shouldn't be too old. I'd say that *generally* the purpose of the docker version is more towards deploying this as a service. While it's nice that it allows more users to launch the project, the lack of file persistence after deleting the container and inability to easily "see" the files is just a fact. Perhaps the open folder icons should also give a file upload option in the future.

Using a local mount sounds like a great alternative. It does split the use cases, but maybe there's a way to satisfy both.

The icons use a font that has failed to load in the picture. When I switch to react I'll be able to make it bundle the font.

**Comment by rsxdalv** [comment]
I'd say we should create a new issue for docker to track these problems separately.
