### ISSUE TITLE
Please delete - wrong app

### ISSUE THREAD

**Issue by Majestic81** [rsxdalv/tts-generation-webui#97]

**Comment by rsxdalv** [comment]
Hi, thank you for the report. Selecting Mac OS is for M1 chip installation.
If you have Nvidia you don't need it.

**Comment by rsxdalv** [comment]
Just a sanity check, these are the v6.0 installers right? I'm looking at the error messages mention text generation webui so I need to check.
Command '. "/Users/user/Desktop/Web-UI/installer_files/conda/etc/profile.d/conda.sh" && conda activate "/Users/user/Desktop/Web-UI/installer_files/env" && git clone https://github.com/oobabooga/text-generation-webui.git' failed with exit status code '-9'. Exiting...
(base) user@user-mbp Web-UI % "/Users/user/Desktop/Web-UI/installer_files/conda/etc/profile.d/conda.sh" && conda activate "/Users/user/Desktop/Web-UI/installer_files/env" && git clone https://github.com/oobabooga/text-generation-webui.git' failed with exit status code '-9
